### ISSUE TITLE
play() not working when media not finished loading

### ISSUE THREAD

**Issue by AgentSmith0** [vidstack/player#1003]
### Current Behavior:

It is not possible to use the play() method while the media is still loading (e.g. after source change).

### Expected Behavior:

play() method starts playing the media after it has finished loading.

### Steps To Reproduce:

```
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/vidstack@^1.0.0/player/styles/default/theme.min.css"
/>
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/vidstack@^1.0.0/player/styles/default/layouts/audio.min.css"
/>

<script
  src="https://cdn.jsdelivr.net/npm/vidstack@^1.0.0/cdn/with-layouts/vidstack.js"
  type="module"
></script>

<media-player id="player" title="Sprite Fight" src="https://samplelib.com/lib/preview/mp3/sample-3s.mp3">
  <media-provider></media-provider>
  <media-audio-layout></media-audio-layout>
</media-player>

<button onclick="play()">play</button>

<script>
  function play() {
    var player = document.getElementById('player');
    player.src = { src: "https://media-files.vidstack.io/sprite-fight/audio.mp3" };

    // none of these two work:
    player.play();
    player.dispatchEvent(new CustomEvent('media-play-request'));
  };
</script>
```

In the example, press the play button below and see that the media changes but doesn't start playing. The second time you press the button it will work, because the media is cached, but it should also work the first time.

### Environment:

- Framework: CDN
- Device: Any
- OS: Any
- Browser: Any

**Comment by mihar-22** [comment]
The iterable should be resolved now and you can call `media-play-request` before media is ready. You cannot call the play method unless media is ready otherwise it will throw an error. You can use the play request event OR you can do `player.paused = false` which will also queue the operation.

**Comment by mihar-22** [comment]
I can't repro but it should be resolved in the next release. I think it's caching at the network layer because we weren't hashing our provider file names.
