### ISSUE TITLE
Unclear how to style captions with Web Components + Tailwind CSS

### ISSUE THREAD

**Issue by sedubois** [vidstack/player#1007]
### Current Behavior:

When styling web components with Tailwind CSS (no Default Layout), one is forced to copy-paste custom captions CSS in the project. This is at least what is done in the [example](https://stackblitz.com/edit/vidstack-examples-ktzh8p) which defines then imports its own custom captions.css file.

### Expected Behavior:

Perhaps captions CSS could be made available to import from Node/CDN, just like when using Default Layout:

```diff
@import 'vidstack/player/styles/base.css';
+ @import 'vidstack/player/styles/captions.css'; /* Such a file should be created. */
@tailwind base;
@tailwind components;
@tailwind utilities;
```

An alternative could be to instruct to add the class `vds-captions` anyway, then use `vidstack/player/styles/default/captions.css`. Hybrid of using one's own Tailwind layout and using a bit of the Default Layout.

Perhalps a single CSS file could be made available which would serve both purposes, by providing a selector such as:
```diff
- :where(.vds-captions) {
+ :where(.vds-captions, media-captions) {
  // ...
}
```

(BTW I am not very experienced with CSS, I don't know why there is a `:where` instead of just putting the selector directly.)

### Steps To Reproduce:

See [Tailwind CSS example](https://stackblitz.com/edit/vidstack-examples-ktzh8p) (index.html, base.css and captions.css).

### Anything Else?

1. This situation seems to partly arise from the fact that (at least in the example) `media-captions` is defined as an empty HTML tag and its children `<div data-part="cue-display" ... ><div data-part="cue">...</div></div>` are only added to the DOM at runtime, so it's not possible to define everything inline using Tailwind classes? Would it be possible to somehow define all of the HTML tags upfront so that Tailwind CSS classes can be added inline? Although it is nice that one is not forced to do so, and can just use the Default Layout CSS for this specific aspect.
2. Perhaps similar comments can be made about other elements I haven't noticed (e.g. I haven't been using chapter markers and thumbnails so far).

**Comment by sedubois** [comment]
I just discovered that one can also simply `@import 'media-captions/styles/captions.css';`. I found a link to `media-captions` on the [documentation page](https://www.vidstack.io/docs/wc/player/components/display/captions?styling=tailwind-css).

**Comment by mihar-22** [comment]
I'll respond properly tomorrow but you can import the default captions theme like so:

```js

import 'vidstack/player/styles/default/captions.css';
```

All defaults are available in that directory.

**Comment by sedubois** [comment]
That file will only work if using a `vds-captions` class. But such a class is not present in the web components + tailwind stackblitz example. It's nothing blocking for me as I just import the media-captions CSS file, but the documentation could be improved.

**Comment by mihar-22** [comment]
I've now added a docs callout above all relevant examples on our site and in the repo that you can import these styles and that you need to apply the `vds-captions` class. It's also included in the new styling examples for the captions component on our site. 

Our default theme is not automatically applied as some use-cases might require mixed player styles (some default, some custom). Classes also makes it clear where the styles are coming from. It's a small inconvenience for added flexibility but I understand your point. It'd also be a breaking change now so we can't do it.
