### ISSUE TITLE
Showing poster should hide the video in the background

### ISSUE THREAD

**Issue by dennisspohr** [vidstack/player#1008]
### Current Behavior:

When loading the player with a poster, where the poster has a smaller resolution than the video, both are shown (the video is always in the background). Tested on latest version 1.5.6.

### Expected Behavior:

The video should be hidden and the playback starts.

### Example:

https://jsfiddle.net/wqz2mdvy/

**Comment by dennisspohr** [comment]
Additionally the format of the video is not shown correctly as well. The video is a vertical one.

**Comment by mihar-22** [comment]
Thanks for reporting! Ah I see, you can easily fix this with some CSS since the poster doesn't cover the video:

```css
media-poster {
  background-color: black;
}
```

I'll also contemplate adding this to the default theme.
