### ISSUE TITLE
Poster randomly disappears when combined with bg-black

### ISSUE THREAD

**Issue by sedubois** [vidstack/player#1010]
### Current Behavior:

When setting `bg-black` on `media-poster`, on mac Safari (perhaps other browsers too) for some screen resolutions when resizing the window the poster randomly appears and disappears and instead the player is just black (i.e. the background appears on top of the poster image).

NB: I needed to put `bg-black` in order to avoid having this strange play icon (1) appear in the native Android Web View while loading.

### Expected Behavior:

1. Poster consistently shows up even when setting a background color.
2. Don't show the play icon (1) in Android Web View while loading. Instead the area should just be a uniform color with a loading indicator.

### Steps To Reproduce:

Please let me know if I should assemble a precise reproduction case.

### Environment:

- Vidstack: 1.5.6
- Framework: Ruby on Rails, Web Components, Tailwind CSS
- Device: macbook M2 & Galaxy A03
- OS: macOS Sonoma 14 & Android 13
- Browser: Safari 17 & Android Web View

### Anything Else?

(1) 
![Screenshot_20231116_164404](https://github.com/vidstack/player/assets/4217871/e20a9bc1-38b2-4efc-8a0f-80669022e8f2)

**Comment by mihar-22** [comment]
I actually have no idea what's happening here, not sure why that play icon is there either? If you can give me a repro I'd love to get on top of this to see what's up. I haven't noticed this anywhere.

**Comment by mihar-22** [comment]
Closing for now until a repro is provided.

**Comment by brendanahart** [comment]
I actually have this same exact issue. I noticed that instead of the webview preview, a black screen initially shows up when I include the crossOrigin property on my MediaPlayer
