### ISSUE TITLE
Other pointerdown events cause a sticky timeline dot when fast-forwarding

### ISSUE THREAD

**Issue by MakFred86** [vidstack/player#1012]
### Current Behavior:

If you integrate a pointerdown event on the player's website, e.g. execute alert('test') or open new window/popup etc., and fast-forwarding in the player on the timeline, the third party pointerdown event is executed as expected. If you then close it/return to the player, the cursor is stuck on the timelines dot.

(This may also affect other events, I have not tested any further.)

### Expected Behavior:

release the sticky dot and stop the timeslider thumbnails. Click should just play the new desired position.

### Steps To Reproduce:

Integrate this on the html page with the player:
`    <script>
    document.addEventListener('pointerdown', function() {
      alert('pointerdown');
      console.log('pointerdown');
    });
    </script>`
reload & click on the progress bar to fast forward somewhere. 

### Environment:

Chrome 119
Windows@11
vidstack/examples.git 1.5.6@next (Web Components -> Default Theme -> Video Player)

### Anything Else?

https://github.com/vidstack/player/assets/77133851/496dbd0d-239b-4649-ad52-f5434c1abce5

**Comment by mihar-22** [comment]
I don't think there's much we can do here since the `pointerup` event is interrupted by the alert. It's a little old firing an alert when clicking the page, don't think it's good UX but not sure on full context.

From MDN:

> The alert dialog should be used for messages which do not require any response on the part of the user, other than the acknowledgement of the message. Dialog boxes are modal windows - they prevent the user from accessing the rest of the program's interface until the dialog box is closed. For this reason, you should not overuse any function that creates a dialog box (or modal window).

I'll close this out as there's not much we can do here. Ideally this alert should be shown in a more user-friendly way rather than clicking anywhere on the document.
