### ISSUE TITLE
v1.6.0 - Uncaught TypeError: t.qualities[$.g] is not a function

### ISSUE THREAD

**Issue by wplit** [vidstack/player#1016]
Not having much luck with v1.6.0 using web components. 

Everything seems to work correctly, apart from whenever I use Youtube as the src. (tried the various formats from the docs) i hit the same error and nothing is adding in the player.

Apologies if it's just me doing something wrong. Tried setting up again fro scratch following the docs, but keep hitting the same.

Screenshots below showing the console.

![SCR-20231124-njvb](https://github.com/vidstack/player/assets/43051571/95ba6351-0d6b-44ce-a681-f3d39d55f4dc)
![SCR-20231124-nkey](https://github.com/vidstack/player/assets/43051571/0d99d97e-c33a-4ecd-b511-0a6418089948)

**Comment by mihar-22** [comment]
Sorry about that, please try again in `1.6.1@next` :)
