### ISSUE TITLE
Chapter 1 is not displayed

### ISSUE THREAD

**Issue by piszczu4** [vidstack/player#1019]
Hi, chapter 1 is not displayed at the start of the video. It's replaced by `title` (if provided) or empty. Here is the example from official examples: https://stackblitz.com/edit/vidstack-examples-queupa?file=src%2Fplayer.tsx&showSidebar=1&title=Vidstack%20Player%20-%20React%20(Default%20Layout)

**Comment by aaa3334** [comment]
I have the same issue - is this how it is meant to work? Doesnt come up in the menu either

**Comment by aaa3334** [comment]
I had this same issue when I was putting together my own file - seems like the solution (if anyone else gets this issue) is to ensure there is an enter after WEBVTT - if there is no enter it will not read the first line of subs

So eg:

WEBVTT

00:00 --> 00:02
The Forest

00:02 --> 00:05
Camp Site
