### ISSUE TITLE
The 'Normal' item label in the Speed submenu does not use translation

### ISSUE THREAD

**Issue by wave-ys** [vidstack/player#1021]
### Current Behavior:

The 'Normal' item label in the Speed submenu does not use the translation passed into `translations` in `<DefaultVideoLayout />` component, while the label in the top right does use it:

<img width="333" alt="image" src="https://github.com/vidstack/player/assets/141913268/f04cec50-5edf-4430-ac10-d0191e0b7580">

### Expected Behavior:

The 'Normal' menu item should also use the `Normal` item of `translations` prop in `<DefaultVideoLayout />` component.

### Steps To Reproduce:

Pass translations into `<DefaultVideoLayout />` component.
```js
<DefaultVideoLayout icons={defaultLayoutIcons} translations={translations}/>
```

### Environment:

- Framework: React
- Meta Framework: Next.js

### Anything Else?

In [packages/react/src/hooks/options/use-playback-rate-options.ts](https://github.com/vidstack/player/blob/4b6493d3a07420026ca8776e549c7696ee20a0ad/packages/react/src/hooks/options/use-playback-rate-options.ts#L6), the 'Normal' label is hardcoded and not be processed using `translations`, which might be the reason for this bug.

<img width="697" alt="image" src="https://github.com/vidstack/player/assets/141913268/d0369bb3-386a-4f21-a36e-934459d97269">

**Comment by mihar-22** [comment]
Thanks for letting me know, fixed! Releasing shortly today in `1.7.0` :)
