### ISSUE TITLE
Bad connection issues with HLS

### ISSUE THREAD

**Issue by garder500** [vidstack/player#1025]
### Current Behavior:

The player stop loading for an unlimited amount of Time
### Expected Behavior:
The player work great and the video Load as it should do

I Just have a bad connection (The same m3u8 file work great in VLC) 
### Steps To Reproduce:
Just try to change the network settings in Devtools to emulate a change in your connection

**Comment by mihar-22** [comment]
There's not enough information here for me to reproduce the bug. If you can share a repro or provide more information I'll re-open.
