### ISSUE TITLE
Fullscreren on safari when playing

### ISSUE THREAD

**Issue by Mister-Hope** [vidstack/player#1026]
When using the default provider and with safari, clicking the play button ALWAYS trigger a toogle to fullscreen.

I think this should be a bug.

A reproduction； https://plugin-components.vuejs.press/guide/media/vid-stack.html

Testing env: iPadOS 17.1.1

Component file [here](https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/components/src/client/components/VidStack.ts) just in case you doubt I write something wrong

---

Additional info: if this feature is expected to solve some issues, I still curious why an audio should have "fullscreen"

**Comment by mihar-22** [comment]
> When using the default provider and with safari, clicking the play button ALWAYS trigger a toogle to fullscreen.

You'll need to set `playsinline` on the player to prevent fullscreen on play when interacting via touch. It's now [mentioned in the installation docs](https://www.vidstack.io/docs/player/getting-started/installation/vue?provider=video&styling=default-layout#12-playsinline-optional).

```html
<media-player playsinline>
```

> I still curious why an audio should have "fullscreen"

Maybe for a poster and captions. We don't include the fullscreen button for audio in our default layout, and you can hide it yourself with CSS if needed for a custom layout:

```css
media-player[data-media-type="audio"] media-fullscreen-button {
  display: none;
}
```

If the fullscreen button is appearing for any reason in the default audio layout please raise a new issue.

Thanks :)

**Comment by Mister-Hope** [comment]
Nope, I am reporting that clicking play button of audio also triggersfullscreen.

I don't think that's reasonable because I am getting a blank screen in this case.
