### ISSUE TITLE
YouTube not holding aspect ratio

### ISSUE THREAD

**Issue by Mister-Hope** [vidstack/player#1027]
Other providers are working well, except YouTube.

Reproduction can be found at: https://plugin-components.vuejs.press/guide/media/vid-stack.html#demo

Component file [here](https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/components/src/client/components/VidStack.ts) just in case you doubt I write something wrong

---

Updated: I am not finding any css file which is like `vidstack/player/styles/default/layouts/youtube.css`, not sure if I miss anything.

**Comment by mihar-22** [comment]
Thanks for reporting! Fix rolling out today.
