### ISSUE TITLE
Since ~v1.6.0 changing media title after initialization not possible anymore

### ISSUE THREAD

**Issue by AgentSmith0** [vidstack/player#1028]
### Current Behavior:

It is not possible to set the title of the current media anymore using the `title` option.

### Expected Behavior:

Change the media title using the `title` option is possible like it was before v1.6.0 or so was published.

### Steps To Reproduce:

1. Create media-player element (optionally with title set)
2. Try changing the media title by running something like `document.querySelector('media-player').title = "new title";`
3. See the option value changed but not the text inside the media player

### Environment:

- Framework: CDN
- Device: Any
- OS: Any
- Browser: Any

**Comment by mihar-22** [comment]
In my testing right now it is. CDN might not have updated yet.
