### ISSUE TITLE
Video not rendered on initial load from Svelte(Kit). (Only during local dev)

### ISSUE THREAD

**Issue by Leftium** [vidstack/player#1030]
### Current Behavior:

- Video is not rendered on initial load. Specifically, the `<media-provider>` tag is not populated with a `<video>` element.
- *Note: although the video is not rendered, it can be played/paused (audio is heard.)*
- *Note: video is rendered on client navigation and HMR.*
- *Note: Only during local dev. (Video is rendered correctly after build + deploy/preview.)*

---

- Also the `player.paused` prop does not match the state of the video.
    - I thought this was related, but it seems to be a separate issue.
    - If `player` is saved to `window.player` from `onMount()` the correct `paused` state can be checked from the devtools console.

### Expected Behavior:

- Video is rendered on initial load. Specifically, the `<media-provider>` tag is populated with a `<video>` element.
- The `player.paused` prop matches the state of the video.

### Steps To Reproduce:

1. Clone this branch: https://github.com/Leftium/kit-demos/tree/vidstack
      - OR: Follow steps 1-9 from [Svelte Installation Guide](https://www.vidstack.io/docs/player/getting-started/installation/svelte?provider=video&styling=css)
3. `npm run dev`
4. Load site in browser.
5. Use button to toggle `paused` state of video.

### Environment:

```
$ npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}
  System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 7.98 GB / 23.86 GB
  Binaries:
    Node: 18.18.2 - V:\scoop\apps\nodejs-lts\current\node.EXE
    npm: 9.8.1 - V:\scoop\apps\nodejs-lts\current\npm.CMD
    pnpm: 8.10.5 - V:\scoop\shims\pnpm.EXE
  Browsers:
    Edge: Chromium (119.0.2151.93)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.1
    @sveltejs/kit: ^1.20.4 => 1.27.6
    svelte: ^4.0.5 => 4.2.7
    vite: ^4.4.2 => 4.5.0
```

### Anything Else?

**Workaround:** force Svelte to destroy and rebuild the `<media-provider>` element after `onMount()`.

All screenshots below taken while video was playing. (Note speaker icon in tab.)

#### Without workaround

![image](https://github.com/vidstack/player/assets/381217/d8801cd6-ec61-4991-92cb-65046745927a)

#### With workaround

![image](https://github.com/vidstack/player/assets/381217/26492372-9857-4fd0-8663-f01cf0a41b35)

**Comment by mihar-22** [comment]
Sorry for the late response, this is because there is a hydration issue with Custom Elements in Svelte. There's a warning that's logged that you should be able to see in your `Console`:

<img width="557" alt="image" src="https://github.com/vidstack/player/assets/14304599/50de15bd-4a90-4572-820d-f06bb360c142">

To resolve this, move all of the Vidstack Player stuff to a separate file (e.g., `Player.svelte`), and then dynamically import it like so:

```svelte
{#await import('./Player.svelte') then {default: Player}}
  <svelte:component this={Player} />
{/await}
```
