### ISSUE TITLE
Can't change media title when view-type attribute is set

### ISSUE THREAD

**Issue by AgentSmith0** [vidstack/player#1037]
### Current Behavior:

Changing the media title isn't possible if the `view-type` attribute is set.

### Expected Behavior:

It works...

### Steps To Reproduce:

```
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/vidstack@1.8.3/player/styles/default/theme.min.css"
/>
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/vidstack@1.8.3/player/styles/default/layouts/audio.min.css"
/>

<script
  src="https://cdn.jsdelivr.net/npm/vidstack@1.8.3/cdn/with-layouts/vidstack.js"
  type="module"
></script>

<!-- removing the view-type attribute makes changing the title possible -->
<media-player id="player" title="Sprite Fight" src="https://samplelib.com/lib/preview/mp3/sample-3s.mp3" view-type="audio"> 
  <media-provider></media-provider>
  <media-audio-layout></media-audio-layout>
</media-player>

<button onclick="test()">test</button>

<script>
  function test() {
    var player = document.getElementById('player');
    player.title = "test";
  };
</script>
```

Try to change the title via the test button.

### Environment:

- Framework: CDN
- Device: Any
- OS: Any
- Browser: Any

**Comment by mihar-22** [comment]
I'm testing this exactly as provided and it's working?

**Comment by mihar-22** [comment]
Everything looks good to me. Is there something going on in your setup?

**Comment by mihar-22** [comment]
Okay found the issue. Fixed in `1.9.4`, sorry about that.

**Comment by mihar-22** [comment]
Closing because I just can't repro this. It might be a caching issue on the CDN-side which may resolve soon.

**Comment by mihar-22** [comment]
I actually can't repro it, and view-type has nothing to do with the title code so I don't understand?
