### ISSUE TITLE
[Youtube] Quality is not available 

### ISSUE THREAD

**Issue by qlaffont** [vidstack/player#1038]
### Current Behavior:

Actually, you can change quality for a video.

### Expected Behavior:

For YOUTUBE video only :
- Quality menu is not display

### Steps To Reproduce:

https://stackblitz.com/edit/vidstack-examples-dpvjh7?file=src%2Fplayer.tsx

**Comment by mihar-22** [comment]
There is no API available via the YouTube embed to set playback quality so we don't show it.

**Comment by qlaffont** [comment]
It seems strange because in the embed player we ca' change the quality?

**Comment by qlaffont** [comment]
After checking, Google seems to removed this feature in 2019 : https://developers.google.com/youtube/iframe_api_reference?hl=en#october-24,-2019
