### ISSUE TITLE
Subtitle or Caption text tracks not showing with Youtube & Vimeo Providers

### ISSUE THREAD

**Issue by wplit** [vidstack/player#1047]
Web components / default theme

Can be seen on the examples, after changing the src URL to either Youtube or Vimeo. 

The subtitles never show, same for captions text tracks. We see the subtitle options appear inside the settings menu as expected, but the words don't actually show in the player.

https://stackblitz.com/edit/vidstack-examples-mllagx?file=video-player.html

**Comment by mihar-22** [comment]
Thanks for letting me know! Fixed in `1.9.6@next` :)
