### ISSUE TITLE
React Warning: Invalid DOM property `autocomplete`. Did you mean `autoComplete`?

### ISSUE THREAD

**Issue by djfarly** [vidstack/player#1048]
### Current Behavior:

This warning comes up in latest next.js/react + latest vidstack (see below):

```
[vidstack]: dev mode!
Warning: Invalid DOM property `autocomplete`. Did you mean `autoComplete`?
    at div
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/@vidstack+react@1.9.6_@types+react@18.2.33_react@18.2.0/node_modules/@vidstack/react/dist/dev/chunks/vidstack-_akU-X8V.js:9594:17)
```
(the rest of the callstack seems irrelevant…)

The error points to this file: https://github.com/vidstack/player/blob/098ebae4ecc664b1d73767e1bb7d99bbf43fe98d/packages/vidstack/src/components/ui/sliders/slider/slider-controller.ts#L78

I monkey patched `autocomplete` to be `autoComplete` which makes the error go away. I could not find any good information on the internet if `setAttribute` expects the HTML or the JS name for attributes but some crude testing showed that both work. React does seem to care though. ;)

Because of that I'm not sure this is the correct fix or if the attributes should be auto-converted on their way to become react attributes.

On that note, if `autocomplete` warns… why doesn't `tabindex`? It's right above and react loves complaining about that as well. 🫣

### Expected Behavior:

There should not be warnings…

### Steps To Reproduce:

Use a slider component in the described environment.

### Environment:

```
"@vidstack/react": "^1.9.6",
"next": "14.0.5-canary.6",
```

**Comment by djfarly** [comment]
Is this code in maverick doing anything magical with tabIndex that it does not to for autoComplete? I'm just poking around, though ;)
https://github.com/maverick-js/maverick/blob/702fe16780531afb25cca93f474d5f9183e1e10e/packages/maverick/src/react/server-component.ts#L43

**Comment by mihar-22** [comment]
Ah, thanks heaps for locating the source of the issue! I've been told about this before but didn't have time to trace it. Ye... you caught me I was being super lazy in Maverick and not mapping all attrs/props 🫣 To avoid future issues I need to go fix that. Open to a PR if you'd like to tackle it, otherwise I'll look into it asap.

**Comment by djfarly** [comment]
You send me on a super interesting journey. 😇
I was wondering how react handles those props it complains about.

React keeps a list of things it warns about in [react-dom-bindings/src/shared/possibleStandardNames.js](https://github.com/facebook/react/blob/0cdfef19b96cc6202d48e0812b5069c286d12b04/packages/react-dom-bindings/src/shared/possibleStandardNames.js).

The actual implementation that sets props can be found in [react-dom-bindings/src/client/ReactDOMComponent.js](https://github.com/facebook/react/blob/0cdfef19b96cc6202d48e0812b5069c286d12b04/packages/react-dom-bindings/src/client/ReactDOMComponent.js#L377).
Plus in [react-dom-bindings/src/shared/getAttributeAlias.js](https://github.com/facebook/react/blob/0cdfef19b96cc6202d48e0812b5069c286d12b04/packages/react-dom-bindings/src/shared/getAttributeAlias.js) which contains all the string accepting attributes/props that are not handled by the other function.

Curiously `autoComplete` has no special handling when being applied as a prop (besides being warned about), so I guess react is just being pedantic here? 🤷
On the other hand `possibleStandardNames.js` contains a few attributes which i cannot imagine making sense for maverick (`dangerouslySetInnerHtml`?).

So I am not really sure what would be the best way to map "all attrs/props" because I am not even sure what all the props that need to be mapped are 🫣

btw: There is also [this package](https://github.com/remarkablemark/react-dom-core) which uses react 15 though, so I am not sure it's the best source…

**Comment by mihar-22** [comment]
Thank you so much for the deep dive! Super helpful. I think for now I'll use the `possibleStandardNames` to manually map a few common attrs to props. I wish React exported it, that would make this super simple.

**Comment by djfarly** [comment]
Awesome thank you! Glad it helped 😇
