### ISSUE TITLE
Multiple captions of the same language

### ISSUE THREAD

**Issue by XanXus96** [vidstack/player#1049]
iIn the captions menu, if we have multiple captions of the same language, the media radio buttons value take the same value, so the selection of one caption triggers the selection of all the other captions of the same language (because they have the same value)

<img width="274" alt="Screenshot 2023-12-12 at 17 16 13" src="https://github.com/vidstack/player/assets/39890594/22bf6ff5-a12a-4943-bb00-e6e0987f6cb6">
<img width="496" alt="Screenshot 2023-12-12 at 17 16 31" src="https://github.com/vidstack/player/assets/39890594/fbff41ca-80d0-41cc-8ff5-a60e6e11a959">

**Comment by mihar-22** [comment]
Not sure what we can do here, this is how radio groups work. You'll need to make sure each option is unique. It's not clear looking at the menu what the difference here is either. Closing this out because this seems to be more of an issue in your captions options.

**Comment by XanXus96** [comment]
> Not sure what we can do here, this is how radio groups work. You'll need to make sure each option is unique. It's not clear looking at the menu what the difference here is either. Closing this out because this seems to be more of an issue in your captions options.

I use the track tag to add my subtitles it's vidstack that internally creates the media-radio tags

**Comment by mihar-22** [comment]
Ah I see, sorry I misunderstood should've clarified. Is one of the tracks captions and the other subtitles. What's the difference here between the tracks?

**Comment by XanXus96** [comment]
> Ah I see, sorry I misunderstood should've clarified. Is one of the tracks captions and the other subtitles. What's the difference here between the tracks?

the tracks are of the same kind
multiple tracks may have the same label and srclang
file is unique

**Comment by XanXus96** [comment]
Ok, so based on the PR i need a unique id

**Comment by mihar-22** [comment]
Releasing fix shortly for better defaults. For your situtation you'll need to provider an `id` on the track to help differentiate them.

```html
<track :id="subtitle.file" ... />
```
