### ISSUE TITLE
Roadmap and Changelog

### ISSUE THREAD

**Issue by Mister-Hope** [vidstack/player#1050]
Thanks for the awesome project, I've been following since 0.2.0 to 1.9.4 now.

I think v1 is stable enough to use (bug exists though).

> Managed Media Source support, Document PIP support, AirPlay, Chromecast, IMASDK integration, and much more

Some of the things discussed in https://github.com/vidstack/player/discussions/935 is already added, and the docs are almost completed.

There are 2 things I concern, and I believe this can be improved.

## V1 Stable / V2

The first thing is can we have a clear roadmap of v1, probably a project board in https://github.com/vidstack/player/projects describing Dones and TODOS.

And what's the future, will V1 touch stable when roadmap task list completed, or we are moving on V2?

## Changelog

The project lacks a changelog, I always need to review commit msg manually to see changes across versions. As v1 is stable for production, can we introduce pkgs like `commitizen` to perform a changelog update automatically?

I belive there are more users moving to v1 instead of staying in the old 0.6.0 at this time. A changelog could benifit users.

---

And again, thanks for the awesome project.

**Comment by mihar-22** [comment]
Thank you for the feedback! We now have:

- [Changelog](https://github.com/vidstack/player/blob/main/CHANGELOG.md).
- Moved the old version to [Releases](https://github.com/vidstack/player/blob/main/RELEASES.md).

In terms of a roadmap, the only feature we have left for 1.0 is the Plyr Layout and some small things. We'll definitely look into it after 1.0 as we're at the end now. Some of the things mentioned in the release notes will move after 1.0.
