### ISSUE TITLE
MediaPlayer instance being recreated rather than reused in conditional rendering of `Modal`

### ISSUE THREAD

**Issue by thisKeeWord** [vidstack/player#1053]
### Related Problem:

I currently am trying to render the video on the page (successful in doing so). However, I added a button to render that instance in a Modal (for our business needs). I added the code snippet below as well as a video

```
const VidstackPlayer = () => {
  const [isTimelinePlayerOpen, setIsTimelinePlayerOpen] = useState(false)

  const player = useRef(null)
  const mediaRef = useRef()
  const { controlsVisible } = useMediaStore(player)

  const togglePlayerContainer = () => {
    setIsTimelinePlayerOpen(!isTimelinePlayerOpen)
  }

  const vidPlayer = (
    <MediaPlayer
      ref={player}
      crossorigin
      title="Sprite Fight"
      className="player"
      src="https://stream.mux.com/VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU/low.mp4"
    >
      <MediaProvider ref={mediaRef}>
        <Poster
          className="vds-poster"
          src="https://image.mux.com/VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU/thumbnail.webp?time=268&width=1200"
          alt="Girl walks into campfire with gnomes surrounding her friend ready for their next meal!"
        />
        {textTracks.map((track) => (
          <Track {...track} key={track.src} type={track.type} />
        ))}
      </MediaProvider>

      <DefaultAudioLayout ... />
      <DefaultVideoLayout ... />
    </MediaPlayer>
  )

  return (
    <>
      <div className="player-container2">
        {vidPlayer}
        {controlsVisible && (
          <button className="timeline-button" onClick={togglePlayerContainer}>
            Timeline
          </button>
        )}
      </div>
      <Modal isOpen={isTimelinePlayerOpen} onClose={togglePlayerContainer}>
        <ModalOverlay bg="blackAlpha.800" />
        <ModalContent maxW="60vw">
          <Box>{vidPlayer}</Box>
        </ModalContent>
      </Modal>
    </>
  )
}
```
![Screenshot 2023-12-13 at 4 46 10 PM](https://github.com/vidstack/player/assets/13548758/b1a3af58-9f9b-47aa-9261-4151e270ed54)

### Describe:

It should ideally keep the MediaPlayer instance and maintain state rather than creating a new instance.

**Comment by mihar-22** [comment]
This is actually how React works, you're creating new DOM nodes at each of the `{vidPlayer}` locations. If you'd like to move the player to a new place in the DOM like a Modal, you'll most likely need to use [React portal](https://react.dev/reference/react-dom/createPortal) to do so.

**Comment by thisKeeWord** [comment]
i wasn't able to get it to work with React's portal, since it would need conditional placement based on if the Modal is present or not (though I'm pretty sure it's possible). I ended up using https://github.com/httptoolkit/react-reverse-portal.
