### ISSUE TITLE
Ability to change volume on mobile player view

### ISSUE THREAD

**Issue by AgentSmith0** [vidstack/player#1055]
### Related Problem:

It is not possible to change the player volume on mobile devices.

### Describe:

It would be nice to get some kind of slider, e.g. inside the floating settings menu under speed and quality settings.

### Alternatives:

None.

### Anything Else?

![image](https://github.com/vidstack/player/assets/67276662/a4197cf3-269c-4cda-8792-697693f066ab)
Volume slider inside this menu would be nice.

**Comment by mihar-22** [comment]
Volume can't be set on mobile, it defaults to system setting.

**Comment by mihar-22** [comment]
Hey Agent, changing volume has no effect on mobile and having a slider for something that is controlled on your device makes no sense.

**Comment by mihar-22** [comment]
Ah........ you're issue is that the volume slider is missing in the small layout when it's displayed on desktop. Good point, I'll look into it.
