### ISSUE TITLE
Flv video support

### ISSUE THREAD

**Issue by thisKeeWord** [vidstack/player#1056]
### Describe:

I saw in the Discord group that flv videos are not supported since they're old video formats. In the off chance, would it be possible to get support for it? If the benefits aren't worth the addition / support for flv, no worries and feel free to close out. We're currently trying with flv.js as a wrapper for Vidstack, but might not be as compatible as we expected.

There's a discussion post from a few months back here: https://github.com/vidstack/player/discussions/857

Thanks.

**Comment by mihar-22** [comment]
Thank raising this but unfortunately out of scope for us right now. We can consider revisiting it in the future.
