### ISSUE TITLE
YouTube: related videos showing if the source is a YouTube short

### ISSUE THREAD

**Issue by Thornus** [vidstack/player#1058]
### Current Behavior:

Related videos appear when I pause a player if I use a YouTube Short as the src.

### Expected Behavior:

Related videos should not appear.

### Steps To Reproduce:

1. Pass a YouTube Short as src to the MediaPlayer.
2. Play the video
3. Pause the video

My code:

```tsx
<MediaPlayer
        onPlaying={onPlaying}
        src={url}
        playsinline
        load="eager"
        className=''
      >
        <MediaProvider>
          { hasPlayed ? '' : <Poster src={"https://img.youtube.com/vi/${getVideoId(url)}/0.jpg"} alt="Recipe Video Poster" className='player-poster absolute object-cover w-full'/>}
        </MediaProvider>

        <div className="absolute top-0 left-0 z-50 pt-3">
          <ShareIcon className="absolute h-6 w-6 text-white bottom-20 right-3" onClick={router.back} />
          <ChevronLeftIcon className="absolute h-6 w-6 text-white" onClick={router.back}/>
        </div>

        <DefaultVideoLayout icons={defaultLayoutIcons} />
      </MediaPlayer>
```

### Environment:
- Framework: React
- Meta Framework: Next.js
- Node: 20.9
- Device: MacBook 2017 
- OS: MacOS Monterey
- Browser: Chrome 120

### Anything Else?
<img width="767" alt="Screen Shot 2023-12-18 at 4 23 42 PM" src="https://github.com/vidstack/player/assets/17854170/21d10ed4-3756-4546-b428-58b26c5e1ff3">

**Comment by mihar-22** [comment]
Unfortunately this is not in our control, if our height hack doesn't work then there's no other API to do it.

**Comment by brenjt** [comment]
I have gotten this to work on shorts with the `rel` attribute

**Comment by GoMino** [comment]
@brenjt how did you pass the rel attribut ?
