### ISSUE TITLE
Unable to change left/right tooltip alignment

### ISSUE THREAD

**Issue by wplit** [vidstack/player#1059]
Web components / default theme

Top, top start, top end, bottom. bottom start, bottom end all working correctly as values for the tooltip placement, but the left/right ones aren't.

See example where I'm changing the placement of the tooltip on the caption button (line 142 on the video-player.html) to left center. It's always appearing as if it's stuck as 'left end'. left start, left center isn't changing it. Same issue with all the right placements also.

[https://stackblitz.com/edit/vidstack-examples-r4evpr?file=video-player.html](https://stackblitz.com/edit/vidstack-examples-r4evpr?file=video-player.html)

**Comment by mihar-22** [comment]
The default theme doesn't include left/right styles at the moment. I'll look into adding it.
