### ISSUE TITLE
Some components can't be clicked at top of player when player in fullscreen mode

### ISSUE THREAD

**Issue by wplit** [vidstack/player#1061]
I can't quite figure out if it's just z-index somewhere, or a pointer-events issue, but I was able to replicate on the examples just by copying the existing bottom controls and adding to the top of the player.

https://komododecks.com/recordings/LyX5eIfYnItOCzKbFy6A

https://stackblitz.com/edit/vidstack-examples-zb3fkb?file=video-player.html

Notice how (with fullscreen mode on) both the settings menu and the captions toggle have issue when being hovered, it's not reliably picking up the hover. It's as if something is blocking it. And then the actual media menu buttons inside the settings can't be clicked at all when in fullscreen.

As far as I can tell, it happens only when the controls are placed away from the bottom of the player. I couldn't figure it out just from inspecting and looking at the CSS.

**Comment by Apezdr** [comment]
In my case I had a issue where the Links weren't clickable in mobile. Turns out if I don't have a container element inside of the button I added it won't work right, see below.

```javascript
export function GoBack({ goBack, tooltipPlacement }) {
  return (
    <Tooltip.Root>
      <Tooltip.Trigger asChild>
        <>
          <Link
            href={goBack}
            className="absolute top-6 left-8 p-2 text-white rounded-full hover:bg-gray-700 hover:bg-opacity-30"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-12 h-12"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18"
              />
            </svg>
          </Link>
        </>
      </Tooltip.Trigger>
      <Tooltip.Content className={tooltipClass} placement={tooltipPlacement}>
        Go Back to List
      </Tooltip.Content>
    </Tooltip.Root>
  )
}
```

**Comment by mihar-22** [comment]
This seems to be resolved, not sure if it was accidentally fixed. If it persists after the next release then we can reopen and investigate. Thanks!
