### ISSUE TITLE
SRT Thumbnails 

### ISSUE THREAD

**Issue by rafiksargsyan** [vidstack/player#1065]
### Current Behavior:

Thumbnails from [thumbnails.vtt](https://pub-d2241617edc04f33a37863bcbece1a85.r2.dev/vidstack-thumbnails/thumbnails.vtt) are not displaying

### Expected Behavior:

Thumbnails must be shown

### Steps To Reproduce:

1. Create a basic player and pass the URL to **DefaultVideoLayout** component

### Environment:

- Framework: React
- Node: 21.0.0
- Device: Mac
- OS: MacOS
- Browser: Chrome

### Anything Else?

N/A

**Comment by mihar-22** [comment]
Hey there! The file provided is not a valid VTT format. The millisecond time unit separator should be a dot (`.`), not a comma (`,`) which is used in the SRT format.

**Comment by rafiksargsyan** [comment]
@mihar-22 Would it be possible to add support for that format too? I was previously using Plyr and have a lot of thumbnail files generated in the format and it was working with Plyr. Now I want to migrate to vidstack, but this will be a blocker.

**Comment by mihar-22** [comment]
Are you able to modify the response `content-type` header to return `text/srt`? That would resolve the issue.

**Comment by rafiksargsyan** [comment]
> Are you able to modify the response `content-type` header to return `text/srt`? That would resolve the issue.

I changed the thumbnail generation code, so that future thumbnail VTT files will be in the correct format. So changing `Content-Type` will be a little troublesome. My only option is to go through all the old files and edit them changing `,` to `.`. If the code could be changed in a way that would support the case it would be awesome (it would also keep backward compatibility for Plyr), but I understand that it might make the code less beautiful.

**Comment by mihar-22** [comment]
Right now with how it's all implemented it's a little tricky supporting SRT on the fly because we parse response streams. We support SRT but it just needs to be specified in the `content-type` header. If this becomes an issue for a larger number of users I'll come back and review it. Hopefully it shouldn't be too hard from your end mapping `,` to `.` or setting the header.
