### ISSUE TITLE
When Vidstack tries to resume playing a live stream, it starts pinging an already non-existent video segment instead of a manifest

### ISSUE THREAD

**Issue by e965** [vidstack/player#1071]
### Current Behavior:

I have an HLS stream configured via [Restreamer](https://github.com/datarhei/restreamer). When it's live, everything is fine. When I interrupt it, the player stops playing - this is the expected behavior. But when I press the Play button, Vidstack (or hls.js?) pings a video fragment that already does not exist on the server many times, and when I start the stream again, the player's state is not updated - because it does not know that the stream has resumed, since it pings an outdated file

### Expected Behavior:

When trying to resume playback, Vidstack pings the m3u8 manifest to see if the stream has resumed or not (maybe?)

### Steps To Reproduce:

Described above

### Environment:

- Framework: React 18
- Meta Framework: Next.js 14
- Node: 20
- Browser: Chrome@121 beta

### Anything Else?

If this is all expected behavior, then I would like to know how to work around it.

Network section screenshot:

<img width="786" alt="Screenshot 2024-01-03 at 12 20 16" src="https://github.com/vidstack/player/assets/18071040/9c4199ff-331c-441c-991d-9e8eff5119c1">

**Comment by e965** [comment]
Also, there is a related problem - when we have autoplay on a player with live mode, Vidstack requests the manifest exactly once - and that’s it. At the same time, there is a loader on top of the player, deceiving the user.

**Comment by Curetix** [comment]
> Also, there is a related problem - when we have autoplay on a player with live mode, Vidstack requests the manifest exactly once (receiving a 404 response) - and that’s it. At the same time, there is a loader on top of the player, deceiving the user.

That behaviour is from hls.js, when it encounters a 4xx or CORS related error during playlist load, it does not further retry and throws an error. See here: https://github.com/video-dev/hls.js/blob/master/src/utils/error-helper.ts#L74

**Comment by e965** [comment]
@Curetix hls.js allows to override the default behaviour
https://github.com/video-dev/hls.js/blob/master/docs/API.md#shouldretry

**Comment by Curetix** [comment]
> @Curetix hls.js allows to override the default behaviour https://github.com/video-dev/hls.js/blob/master/docs/API.md#shouldretry

Yeah, it's a new feature in the v1.5.0 beta. I've been using it for a while now, since our livestream manifests return 404 when the streams are offline, and I would like the player to retry loading indefinitely in that case.
