### ISSUE TITLE
Stop preloading the HLS video before start playing

### ISSUE THREAD

**Issue by abdullaanasanu** [vidstack/player#1081]
When I used the HLS video, the complete video was loaded before clicking the play button.

Can you help me by implementing this feature?
- I want to limit the preloading video before the user initiates the play
- When playing, can we limit the preloaded video duration to 30 seconds or 1 minute upfront instead of loading the complete video as Video.js is doing?

If it is already available please guide me to implement it.

**Comment by mihar-22** [comment]
Hey @abdullaanasanu!

> I want to limit the preloading video before the user initiates the play

By default, the media will only load at the moment when it's visible on screen. You can configure when media is loaded by specifying a [load strategy](https://www.vidstack.io/docs/player/core-concepts/loading?styling=default-theme#load-strategies). You can opt to use the [custom load strategy](https://www.vidstack.io/docs/player/core-concepts/loading?styling=default-theme#custom-load-strategy) for more control.

Side note, we have an new load option coming in the next release called `play` which will only load the provider and media on play. You can still achieve this today using the custom strategy mentioned above and calling start load in the `onPlay` callback.

> When playing, can we limit the preloaded video duration to 30 seconds or 1 minute upfront instead of loading the complete video as Video.js is doing?

I'm not sure which framework you're using but you need to [configure HLS](https://www.vidstack.io/docs/player/api/providers/hls?styling=default-theme#configuring). Specifically the strangely named `maxMaxBufferLength` option:

```tsx
import {
  isHLSProvider,
  type MediaProviderAdapter,
  type MediaProviderChangeEvent,
} from '@vidstack/react';

function onProviderChange(
  provider: MediaProviderAdapter | null,
  nativeEvent: MediaProviderChangeEvent,
) {
  if (isHLSProvider(provider)) {
    provider.config = {
      // Limit loading ahead to 30 seconds, this may affect playback experience.
      maxMaxBufferLength: 30, 
    };
  }
}

<MediaPlayer onProviderChange={onProviderChange} />
```
