### ISSUE TITLE
Display chapter markers even when not in full screen

### ISSUE THREAD

**Issue by aaa3334** [vidstack/player#1086]
### Related Problem:

The chapter markers are an awesome feature! But unfortunately they only show when the video is on full screen and not when it is sitting as a video.

### Describe:

That the chapter markings in the time slider should show up when the video is not full screened

### Alternatives:

Tried to build my own slider but wondering if that is overkill..

### Anything Else?

Currently it looks like this when it is not full screened
<img width="345" alt="Screenshot 2024-01-15 at 09 28 00" src="https://github.com/vidstack/player/assets/63257282/f9d6ddf7-2212-477b-9fa0-2cd1c498b224">

Would be good to have the chapters like this though even when the video is not full screened

<img width="1470" alt="Screenshot 2024-01-15 at 09 28 13" src="https://github.com/vidstack/player/assets/63257282/76ea0f33-d164-49e6-b803-e1e6aeab4276">

**Comment by mihar-22** [comment]
If you're referring to the default layout, there's a `sliderChaptersMinWidth` prop coming in the next release that will help control when you want to show it.

**Comment by aaa3334** [comment]
Perfect! Can't wait for the new release! Will wait until then to finish up the player :)
