### ISSUE TITLE
Order of the src array seems to matter

### ISSUE THREAD

**Issue by endaquigley** [vidstack/player#1087]
### Current Behavior:

The order of the `src` array seems to matter on iPhone (iOS 17.2).

Vidstack player attempts to load the `webm` source even though it doesn't have support for this file format.

```jsx
<MediaPlayer
  src={[
    { type: "video/mp4", src: "/video.mp4" },
    { type: "video/webm", src: "/video.webm" },
  ]}
>
  <MediaProvider />
  <DefaultVideoLayout icons={defaultLayoutIcons} />
</MediaPlayer>
 ```
 
 If I swap the order of the `src` elements the video plays on my iPhone
 
 ```js
src={[
  { type: "video/webm", src: "/video.webm" },
  { type: "video/mp4", src: "/video.mp4" },
]}
```

### Expected Behavior:

Should work the same as a native `video` element:

```jsx
<video controls playsInline>
  <source type="video/mp4" src="/video.mp4" />
  <source type="video/webm" src="/video.webm"  />
</video>
```

### Steps To Reproduce:

https://codesandbox.io/p/sandbox/vidstack-webm-6lq83y

### Environment:

- Framework: React
- Device: iPhone@14 Pro
- OS: iOS@17.2

### Anything Else?

https://github.com/vidstack/player/assets/753515/ae713349-e8a4-4cc4-b3bd-8cf90842a25c

**Comment by RaoulHC** [comment]
Just bumped into this issue, is this going to get a release soon @mihar-22? Does make it harder to support iOS with it's lack of vp9 support.

**Comment by mihar-22** [comment]
Working through docs right now, pretty close and then all I have to do is write up release notes. Should be released in about 2-3 days :)
