### ISSUE TITLE
Issue on TimeSlider.Video component

### ISSUE THREAD

**Issue by brkcrdk** [vidstack/player#1090]
### Current Behavior:
When i want to use `TimeSlider.Video` component video preview is not displayed but i noticed that it renders video element and element has `data-error` as an attribute. When i try with src property i get i get `Uncaught RangeError: Maximum call stack size exceeded`. warning on my console and preview still not renders. I tried to trigger `onError` event on `TimeSlider.Video` element it didn't trigger for some reason. 

I've used `TimeSlider.Video` component like this:

```jsx
<TimeSlider.Root>
...
<TimeSlider.Preview>
{/* 
<TimeSlider.Video /> => this didn't work
<TimeSlider.Video src="https://www.youtube.com/watch?v=bTqVqk7FSmY" />  => this didn't work
<TimeSlider.Video src="https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8" /> => this didn't work
*/}
  <TimeSlider.Video src="/mylocalvideopath.mp4" /> // this did work
  <TimeSlider.Value className="media-slider-value" />
</TimeSlider.Preview>
...
</TimeSlider.Root>
```

NOTE: This error happens when i use external video urls like:
- https://www.youtube.com/watch?v=bTqVqk7FSmY
- https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

but not happens when i use local video. 

As a hack i created this custom video thumbnail component. I don't really know is this performant or is the correct way. But worked.

```jsx
import { useRef } from 'react';

import { MediaPlayer, MediaPlayerInstance, MediaProvider, useMediaRemote, useMediaState, useSliderStore } from '@vidstack/react';

function CustomVideoPreview() {
  const currentSrc = useMediaState('currentSrc');
  const player = useRef<MediaPlayerInstance>(null);
  const remote = useMediaRemote(player);
  const duration = useMediaState('duration');

  const { pointerPercent } = useSliderStore();

  if (typeof currentSrc.src !== 'string') return null;

  return (
    <MediaPlayer
      title="Sprite Fight"
      ref={player}
      src={currentSrc.src}
      onCanPlay={() => remote.changeQuality(0)}
      currentTime={(duration * pointerPercent) / 100}
    >
      <MediaProvider />
    </MediaPlayer>
  );
}
export default CustomVideoPreview;

``` 

### Expected Behavior:

When i use `TimeSlider.Video` component inside of `MediaPlayer` it can reach all the state and props so it should be able to work without any property like `TimeSlider.Value` did.

### Environment:

- Framework: React
- Meta Framework: Next.js@14.0.4
- Node: 18.17.1
- Device: Macbook M1 Pro
- OS: macOS 14.2.1 (23C71)
- Browser: Arc v1.25.1 (45028)

**Comment by mihar-22** [comment]
The `TimeSlider.Video` component only accepts whatever is supported natively by the browser as it uses the `<video>` element. We might upgrade to use the actualy player itself in the future but not planned at the moment.
