### ISSUE TITLE
.m3u8 links for audio players not displaying well

### ISSUE THREAD

**Issue by mikeyhodl** [vidstack/player#1093]
### Current Behavior:

When embedding .m3u8 links for live radio encording, the UI is a bit off. I get this huge black box without audio controls
![image](https://github.com/vidstack/player/assets/49108305/86f5bb51-56e8-41c5-96b0-a24c139ecc39)

### Expected Behavior:

This is what I expected, although this is for .aac audio encoding
![image](https://github.com/vidstack/player/assets/49108305/620da468-970a-4f1e-8d9d-541fe1b17cf6)

### Steps To Reproduce:

Am getting this for both development and in production

### Environment:

- Framework: Next.js 13.4.19
- Node: 20.11.0
- Device: Windows 11
- Browser: Chrome@120.0.6099.217

**Comment by mihar-22** [comment]
👋 It's mentioned in the docs that the `viewType` and `streamType` should be set for the best results. In the case of audio and HLS, `viewType` must be set.

```tsx
<MediaPlayer viewType="audio" streamType="live">
```

**Comment by mikeyhodl** [comment]
> 👋 It's mentioned in the docs that the `viewType` and `streamType` should be set for the best results. In the case of audio and HLS, `viewType` must be set.
> 
> ```tsx
> <MediaPlayer viewType="audio" streamType="live">
> ```

This worked, Thank You.
