### ISSUE TITLE
Refactor use of eval

### ISSUE THREAD

**Issue by thgh** [vidstack/player#1094]
### Related Problem:

There is a project with a content security policy (csp) where `eval` is not allowed. (`unsafe-eval`)

### Describe:

Suggested solution is to refactor `eval` to `matchMedia` in [vidstack/src/core/query-list.ts](https://github.com/vidstack/player/blob/main/packages/vidstack/src/core/query-list.ts)

### Alternatives:

This is the current local fix that resolves the error, but I don't know what it will break.
```
window.eval = console.log
```

### Anything Else?

Sorry for the limited context 😬

**Comment by mihar-22** [comment]
It will be completely removed in the next release. We're dropping player queries as they were a mistake, not performant and lack security.

**Comment by wplit** [comment]
We'll need to use CSS container queries from now on for this?

**Comment by mihar-22** [comment]
Yes or you can set it via a prop function, itll be mentioned in the release notes.

**Comment by leonfrischauf314** [comment]
Great! Having eval removed will allow us to also use your project inside our software. :)

Do you have any information about when the next release will be? @mihar-22 

Best and a nice Sunday,
Leon
