### ISSUE TITLE
Player is broken for SSR

### ISSUE THREAD

**Issue by codercms** [vidstack/player#1101]
### Current Behavior:
When content is rendered during SSR vidstack inherits incorrect --player-width, --player-height variables
```html
<media-player 
class="player s-E9_ygDPpv--5" 
src="https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8" 
playsinline="" data-can-load="" 
style="--player-width: 0px; --player-height: 0px; --media-width: 0px; --media-height: 18px;" aria-busy="false" data-stream-type="on-demand" data-can-play="" data-controls=""><media-provider class="s-E9_ygDPpv--5">
```

<details>
<summary>See screenshot</summary>

![image](https://github.com/vidstack/player/assets/4526911/fdca93fb-7d85-4506-809c-a1dedba9f015)

</details>

BTW is this behavior needed for player to be rendered? Couldn't it be just sized like any normal HTML block element (display: block) to occupy all available size of block, like player UI controls already do?

### Expected Behavior:
Player UI works correct for SSR

### Steps To Reproduce:
Just run Svelte default layout or default theme example on SvelteKit and see it's broken

### Environment:
Framework: SveteKit
Vidstack: 1.9.8

**Comment by mihar-22** [comment]
Svelte has a hydration bug when working with Custom Elements. Raised it ages ago but it hasn't been worked on. A warning should be logged to your console in the event this happen. The fix is to dynamically load the player.

1. Create a new `Player.svete` file with all the player code.

2. Load it like so:

```svelte
{#await import('./Player.svelte') then { default: Player }}
  <svelte:component this={Player} />
{/await}
```

**Comment by mihar-22** [comment]
The player width and height being 0 on initial render makes sense as it doesn't exist on the server. They are just CSS variables exposed for styling needs. They don't determine the actualy width/height of the player itself.

**Comment by codercms** [comment]
@mihar-22 thx for explanation :)
BTW , there's also working fix to render player only in CSR:
```
	let mounted = false;
	onMount(() => {
		mounted = true;
	});

// ....

	{#if mounted}
		<Player />
	{/if}
```

**Comment by silasabbott** [comment]
Here's the relevant issue for reference: https://github.com/sveltejs/svelte/issues/7379
