### ISSUE TITLE
[SvelteKit + Svelte 4] Menu hint is not rendered while using custom theme

### ISSUE THREAD

**Issue by codercms** [vidstack/player#1102]
### Current Behavior:

I use following example to create menu - https://www.vidstack.io/docs/wc/player/components/menus/menu?styling=default-theme
But there's no menu hints rendered.

<details>
<summary>See screenshot</summary>

![image](https://github.com/vidstack/player/assets/4526911/b6db9f26-9097-4c05-8562-13adb96cbd10)
</details>

### Expected Behavior:
Menu hint is rendered like in example

### Steps To Reproduce:
```html
<media-menu class="vds-menu">
  <media-menu-button class="vds-menu-button vds-button" aria-label="Settings">
    <media-icon type="settings" class="vds-rotate-icon vds-icon"></media-icon>
  </media-menu-button>

  <media-menu-items class="vds-menu-items" placement="top" offset="0">
    <media-menu>
      <!-- Button -->
      <media-menu-button class="vds-menu-button">
        <media-icon type="chevron-left" class="vds-menu-button-close-icon"></media-icon>
        <media-icon type="odometer" class="vds-menu-button-icon"></media-icon>
        <span class="vds-menu-button-label">Speed</span>
        <span class="vds-menu-button-hint" data-part="hint"></span>
        <media-icon type="chevron-right" class="vds-menu-button-open-icon"></media-icon>
      </media-menu-button>

      <!-- Items -->
      <media-menu-items class="vds-menu-items">
        <media-speed-radio-group class="vds-radio-group" normal-label="Normal">
          <template>
            <media-radio class="vds-radio">
              <div class="vds-radio-check"></div>
              <span class="vds-radio-label" data-part="label"></span>
            </media-radio>
          </template>
        </media-speed-radio-group>
      </media-menu-items>
    </media-menu>
  </media-menu-items>
</media-menu>
```

### Environment:
Vidstack: 1.9.8
Framework: SvelteKit

**Comment by Curetix** [comment]
When I paste your provided code into a Vidstack example project, the menu and hint work fine. It must be some other part of your code.

[Example](https://stackblitz.com/edit/vidstack-examples-akjggs?file=video-player.html%3AL152-L152&showSidebar=1&title=Vidstack%20Player%20-%20Web%20Components%20(Default%20Theme))

**Comment by codercms** [comment]
@Curetix it looks really strange, here is your example wrapped into SvelteKit (with SSR rendering disabled) and hint is not rendered - https://stackblitz.com/edit/sveltejs-kit-template-default-mobhuu?file=src%2Froutes%2F%2Bpage.svelte

Seems like it's somehow related to SvelteKit

**Comment by codercms** [comment]
Closing this issue since I can't reproduce this with new [1.10](https://github.com/vidstack/player/discussions/1116) version

**Comment by mihar-22** [comment]
Svelte seems to do something really strange during hydration, I raised an issue a while ago but it's just been pending for years. Hopefully Svelte 5 fixes it. For now, we probably need to use a `MutationObserver` with a `data-part` attribute filter and detect hint element as it's added/removed.

**Comment by codercms** [comment]
@mihar-22 I just tested this in Svelte 5 and... it works :)
