### ISSUE TITLE
Extreme height of iframe while using YouTube Provider and default theme

### ISSUE THREAD

**Issue by svwezel** [vidstack/player#1104]
### Current Behavior:

Using the YouTube provider and the default theme.
The YouTube iframe is set to height: 1000% this ruins the layout of the containing page.
Is this a typo maybe?

The video itself is in the correct aspect ratio.

### Expected Behavior:

Have the height of the iframe be 100% not 1000%

### Steps To Reproduce:

1. Go to https://github.com/vidstack/examples/tree/1de5c48857d21b507411dbd590b2a08aa83412fe/player/svelte/default-theme
2. Open it in stackblitz
3. Click YouTube source.
4. The source buttons disappear from view because the player becomes very high
5. You can also check with inspect element on the embedde iframe to see: eight: ~3000px, width: ~600px

The css responsible:
iframe.vds-youtube[data-no-controls] {
  height: 1000%;
}

### Environment:
- Framework: SvelteKit
- OS: Ubuntu
- Browser: Chrome / Firefox

**Comment by svwezel** [comment]
Maybe this is intended to hide some YouTube ui?
Setting `overflow: hidden; would then be appropriate probably?

**Comment by wplit** [comment]
Add overflow:hidden or contain:paint to the media-provider component.
