### ISSUE TITLE
Youtube video replay problem

### ISSUE THREAD

**Issue by vkgencer** [vidstack/player#1105]
### Current Behavior:

I use Vidstack together with youtube provider. 

I have 2 problems when the video ends.

1. currentTime and duration are not equal so there is a gap at the end of the time slider.
2. On the replay button the label remains Pause and when clicked the video does not play again.

### Expected Behavior:

The video needs to be restarted when the replay button is clicked.

#### Rebuild Steps:

1. Add Youtube video link as source.
2. Wait for the video to finish.
3. Click the replay button and see that the button does not work.

#### Environment:

- Framework: React
- Meta Framework: Next.js
- Node: v20.11.0
- Device: Apple M1
- OS: MacOS 13.4
- Browser: Chrome@120.0.6

#### Anything else?

![image](https://github.com/vidstack/player/assets/5902234/f7eb1c79-e4a2-4e17-b6aa-517e712a952f)
![image](https://github.com/vidstack/player/assets/5902234/a7f103ca-d5d6-4abd-9f9c-919f47323a09)

**Comment by mihar-22** [comment]
This has been fixed for the next release, happy to re-open if it persists after testing it again :)
