### ISSUE TITLE
Event bugs on youtube videos.

### ISSUE THREAD

**Issue by brkcrdk** [vidstack/player#1107]
### Current Behavior:

- When we trigger `seek` event with `SeekButton` `onSeeked` callback won't work. I tried to do it manually and it didn't work either. When i trigger seek event from `TimeSlider`,`onSeeked` callback works fine.
- `onSeeking` callback not triggers on YouTube providers. But `seeking` state works fine and i have to keep listen `seeking` state instead of using `onSeeking` callback.
- `onAbort` callback won't work for YouTube videos but it works fine with hls videos
### Expected Behavior:

- When we use YouTube providers, `SeekButton` should trigger `onSeeked` callback.
- When we use YouTube providers, `onSeeking` callback should work. 

NOTE: I keep say it won't work on YouTube providers because i only test with YouTube videos and hls videos. These events should work for all providers because these events work partially. 

### Steps To Reproduce:

I created this reproduction on stackblitz. I added two video src files and commented one of them. 

- To test YouTube provider behaviour comment out m3u8 src
- To test hls provider behaviour comment out youtube src
- When callback's work it shows on the console. 

https://stackblitz.com/edit/stackblitz-starters-ue5ato?file=src%2FApp.tsx

**Comment by mihar-22** [comment]
This has been resolved for the next release. Happy to reopen if the issue persists after testing it, just let me know here :)

**Comment by brkcrdk** [comment]
Thank you @mihar-22 can't wait for the next release 🤘🏻
