### ISSUE TITLE
data-live attribute removed when video played

### ISSUE THREAD

**Issue by wplit** [vidstack/player#1110]
Once the video is played, all indicators that it's a live stream disappear (including the live button by default and the red color on the time slider) as they depend on that attribute on the player. But after pressing play, the attribute is removed.

Here's an example live stream Youtube URL for testing - https://www.youtube.com/watch?v=aB_UzUMr-Vc

**Comment by mihar-22** [comment]
I can't remember but I might've fixed this indirectly fixing something else. Let's circle back after the release.

**Comment by wplit** [comment]
This is still the case for Youtube live URLs in v1.10.2

**Comment by mihar-22** [comment]
Not finding a stable way to detect if it's live. There's a `isLive` prop in video data but it's never `true`. I recommend setting `streamType="live"` on the player if you know it's live. If you can tell me a reliable way to detect it then we can add it.

**Comment by wplit** [comment]
Fair enough, I think what was throwing me is that there was a data-live attribute being added, when I was adding a live Youtube URL, so I figured it must be picking it up. It doesn't seem to be added anymore, so I won't worry about it.
