### ISSUE TITLE
iOS 16 - [vidstack]: captions text track created without label: 'undefined'

### ISSUE THREAD

**Issue by uvarov-frontend** [vidstack/player#1115]
### Current Behavior:

After initialization in iOS 16 error: `[vidstack]: captions text track created without label: 'undefined'`

### Environment:

- Framework: React
- Meta Framework: Next.js
- Node: 18.18.2
- Device: iPhone@11 Pro on browserstack.com
- OS: iOS@16
- Browser: Chrome and Safari any

### Anything Else?
![Screen-Shot-2024-01-30-09-00-39-1706594445](https://github.com/vidstack/player/assets/82662379/3ac47cc7-2b84-47fd-91e1-14713db754cc)

The error occurs regardless of whether I use subtitles in the player or not. Having completely disabled any subtitles and code associated with it, the error is still there.

**Comment by uvarov-frontend** [comment]
Additional Information.
Meta Framework: Next.js v14.1.0
Provider: HLS.js

My master.m3u8:
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1126291,RESOLUTION=1280x546,FRAME-RATE=25.000,CODECS="avc1.640029,mp4a.40.2"
index-f1-v1-f3-a1.m3u8?token=st=1706708850~exp=1706795250~acl=/hls/
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=428147,RESOLUTION=640x272,FRAME-RATE=23.980,CODECS="avc1.640029,mp4a.40.2"
index-f2-v1-f3-a1.m3u8?token=st=1706708850~exp=1706795250~acl=/hls/
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=128000,CODECS="mp4a.40.2"
index-f3-a1.m3u8?token=st=1706708850~exp=1706795250~acl=/hls/
```

**Comment by mihar-22** [comment]
Thanks for reporting! Unforunately no luck reproducing issue in iOS simulator, closing for now. If you can provide a [repro](<https://github.com/vidstack/player/blob/main/.github/REPRO.md>) then I'm happy to reopen.

**Comment by sukijun** [comment]
hi @mihar-22 , this is the video I recorded when I encountered this error. I think it's related to "provider-change" event and native hls on IOS

https://github.com/vidstack/player/assets/92907658/4af69934-6368-4554-9b44-068fd538d786
