### ISSUE TITLE
Cannot find module node_modules\vidstack\plugins.js

### ISSUE THREAD

**Issue by bjarnef** [vidstack/player#1117]
### Current Behavior:

I have followed the guide here to bundle Vidstack:
I https://www.vidstack.io/docs/player/getting-started/installation/vue?bundler=nuxt&provider=youtube&styling=default-layout

Furthermore we are using Nuxt v3.9.2 and Vue v3.3.8

However when running `npm run dev` I get the following error:

![image](https://github.com/vidstack/player/assets/2919859/e215af0a-c371-47d8-a9c5-4a9aa5cfbbbb)

In `node_modules\vidstack\plugins.d.ts` it has:

```
import * as _esbuild from 'esbuild';
import * as _rollup from 'rollup';
import * as _vite from 'vite';
import * as _unplugin from 'unplugin';

type FilterPattern = Array<string | RegExp> | string | RegExp | null;
interface UserOptions {
    include?: FilterPattern;
    exclude?: FilterPattern;
}
declare const unplugin: _unplugin.UnpluginInstance<UserOptions | undefined, boolean>;
declare const vite: (options?: UserOptions) => _vite.Plugin<any> | _vite.Plugin<any>[];
declare const rollup: (options?: UserOptions) => _rollup.Plugin<any> | _rollup.Plugin<any>[];
declare const webpack: (options?: UserOptions) => WebpackPluginInstance;
declare const rspack: (options?: UserOptions) => RspackPluginInstance;
declare const esbuild: (options?: UserOptions) => _esbuild.Plugin;

export { type FilterPattern, type UserOptions, esbuild, rollup, rspack, unplugin, vite, webpack };
``` 

### Expected Behavior:

To be able to bundle Vidstack with Nuxt and Vite.

### Environment:

Example:
- Framework: Vue
- Meta Framework: Nuxt.js
- Node: 20.11.0

**Comment by mihar-22** [comment]
What version are you on? It was included in 1.10.3@next because I forgot to include it package files.

**Comment by bjarnef** [comment]
Sorry for not mentioning, it's on v1.10.1
I see there the newly released v1.10.2

Upgraded to latest release and it builds now 🎉🥳

I don't see the custom element rendered though.

```
<media-player title="Sprite Fight" src="https://stream.mux.com/VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU/low.mp4">
    <media-provider></media-provider>
</media-player>
```

I tried configuring the `isCustomElement` here in `nuxt.config.ts`:

![image](https://github.com/vidstack/player/assets/2919859/65e04e18-e002-4d6b-af00-f35de5c40004)


and in component:

```
<script lang="ts" setup>

import 'vidstack/bundle';

</script>

<template>
  <div class="video">
    <media-player title="Sprite Fight" src="https://stream.mux.com/VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU/low.mp4">
      <media-provider></media-provider>
    </media-player>
    Video
  </div>
</template>
```

anything missing?

**Comment by mihar-22** [comment]
You have no layout? You can use either the Default Layout, Plyr Layout, or build your own :)

**Comment by mihar-22** [comment]
Default Layout needs to be selected, not Default Theme. The Default Theme is for building your own layout using our theme. I need to add more information to the styling step to help with deciding between the options. Sorry about the confusion.

**Comment by bjarnef** [comment]
Thanks, I see the difference now at "11. Player Markup".

I was also wondering why I couldn't select both as I think "layout" is how/where the elements are rendered in DOM and "theme" how the elements are styled. Some plugins use theme/skin how the component is styling, but often only a single layout (or possible to configure via some options).
