### ISSUE TITLE
Storage only works for hls provider.

### ISSUE THREAD

**Issue by brkcrdk** [vidstack/player#1122]
### Current Behavior:

Currently storage provider not works correctly on youtube provider but works fine on HLS providers. As an example when i set my volume to 0.5 and i can see that it updated on localStorage to 0.5. But when i refresh the page youtube volume is set to 1 which is default for me. 

### Expected Behavior:

Storage should work with all providers.

### Steps To Reproduce:

https://stackblitz.com/edit/stackblitz-starters-i5p6ou?file=src%2FApp.tsx

- First video is youtube video and when i toggle video to mute state and refresh the page it starts with mute state false.
- Second video is hls video and when i toggle video to mute state and refresh the page it keeps the mute state true.

**Comment by wplit** [comment]
Same for me, when using web components also. I can see the key/value in the browser is there for volume, muted, captions etc, but it's not being used by the player when I reload the page. It goes back to default.
