### ISSUE TITLE
Preview of YouTube video is upscaled

### ISSUE THREAD

**Issue by bjarnef** [vidstack/player#1123]
### Current Behavior:

With default layout of player I added an YouTube video: https://www.youtube.com/watch?v=CQJIl2xoDhc
However the preview seems to be blurry.

![image](https://github.com/vidstack/player/assets/2919859/4ebc7889-f25f-4db4-af1f-1e59942258e3)

I noticed it seems youtube video overwrite height with 1000% - I guess this was a typo?
![image](https://github.com/vidstack/player/assets/2919859/eeef0926-b91a-4ee9-a21d-b96d7b1f0493)

### Expected Behavior:

![image](https://github.com/vidstack/player/assets/2919859/c6347fb6-085c-4d57-a2af-215566a94746)

![image](https://github.com/vidstack/player/assets/2919859/e37361fe-d8df-4069-9a7e-b9bbc15057a6)

**Comment by mihar-22** [comment]
It's correct, it hides the YouTube embed popups but distorts the thumbnail. Add the poster component:

**HTML**

```html
<media-player>
  <media-provider>
    <media-poster class="vds-poster" alt="..."></media-poster>
  </media-provider>
</media-player>
``` 

**React**

```html
<MediaPlayer>
  <MediaProvider>
    <Poster className="vds-poster" alt="..." />
  </MediaProvider>
</MediaPlayer>
``` 

I need to add this to the installation player markup code snippet when using YouTube or Vimeo.

**Comment by bjarnef** [comment]
I added `<media-poster>` 

```
<media-player 
      class="player"
      :src="src"
      crossorigin
      playsinline
      @provider-change="onProviderChange"
      @can-play="onCanPlay">
      <media-provider>
        <media-poster class="vds-poster" alt=""></media-poster>
      </media-provider>
      <!-- Layouts -->
      <media-audio-layout />
      <media-video-layout />
</media-player>
```

But it didn't seem to make a difference.

![image](https://github.com/vidstack/player/assets/2919859/1f06484b-6045-4653-ad10-dbb91a175545)

![image](https://github.com/vidstack/player/assets/2919859/623b40e9-b3aa-4d33-97f5-2c766852086a)

The `<img>` element inside `<media-poster>` is the expected quality though:
https://i.ytimg.com/vi_webp/CQJIl2xoDhc/maxresdefault.webp

**Comment by mihar-22** [comment]
Can you upgrade to `1.10.3@next` and let me know if that resolves it? It is dynamically loaded.

**Comment by bjarnef** [comment]
Yes, it seems to the issue using `1.10.3@next` instead of `1.10.2@next`.

```
<media-player 
      class="player"
      :src="src"
      crossorigin
      playsinline
      @provider-change="onProviderChange"
      @can-play="onCanPlay">
      <media-provider>
        <media-poster
          class="vds-poster"
          alt="">
        </media-poster>
      </media-provider>    
      <!-- Layouts -->
      <media-audio-layout />
      <media-video-layout />
</media-player>
```

**Comment by wplit** [comment]
> Same issue on `vidstack@1.10.3`. I temporary fixed it by adding to my css
> 
> ```css
> iframe.vds-youtube[data-no-controls] {
>     height: 100% !important;
> }
> ```

Are you adding a poster image? Because just setting the height to 100% isn't an idela solution, as it means the Youtube branding and recommeded videos become visible. The idea with the large height in vidstack is to purposely stretch the iframe to hide all that stuff, and then hide the stretching with the poster image component over the top.
