### ISSUE TITLE
player.duration is always -1.

### ISSUE THREAD

**Issue by wplit** [vidstack/player#1125]
Unable to get the duration of the media.

After all the media has loaded, player.duration should give us the number of seconds for the entire things, but it seems to always be stuck at -1.

I was trying to get the duration, so I could check that the clipEndTime isn't larger than it, otherwise it makes the player go a bit crazy, but realised I couldn't get the value.

**Comment by mihar-22** [comment]
When are you checking and with what provider? Need more information.

**Comment by wplit** [comment]
Ah sorry,.. with any provider as far as I can tell. tried after the video has already started playing, when the duration must be known as it's being shown in the time component.

Tried Youtube/Vimeo and also tried to get direct from the example shown on the Vidstack site, I'm able to change the duration through the browser console, if i change to 300 then it correctly changes the duration to 5 minutes, however, I can't get the information FROM the player, always is -1 regardless of the actual length of the video.

![SCR-20240131-tkpi](https://github.com/vidstack/player/assets/43051571/97891809-7cc3-4008-85a6-37eecf8ddebb)

**Comment by mihar-22** [comment]
Ah ye I know why, it's because we now have a duration prop so it's overriding the internal state. I can fix it tomorrow.
