### ISSUE TITLE
Persist selected text track in storage

### ISSUE THREAD

**Issue by DerStimmler** [vidstack/player#1128]
### Related Problem:

Currently only those properties are saved to storage:

```
{
    "volume": 0.47,
    "muted": false,
    "lang": "DE",
    "captions": false,
    "rate": 1.25
}
```

It would be awesome if the current selected text track could also be saved.

### Describe:

When I change the text track it should persist the selected text track to storage. I think the `language` property on `TextTrack` type would be a fitting discriminator.

When I refresh the page it should automatically load the last text track from storage and select the corresponding text track.
If this text track is not available it should just disable captions.

### Anything Else?

I'm currently on version `1.10.3`. Maybe this is already in the pipeline?

**Comment by mihar-22** [comment]
There was a bug in the track selection process, it'll be resolved in the next release `1.10.4@next`. The language will be used to select the initial track and then it'll fallback to the default, otherwise none.
