### ISSUE TITLE
Add possibility to configure which settings are persisted to storage

### ISSUE THREAD

**Issue by DerStimmler** [vidstack/player#1129]
### Related Problem:

I want to persist all settings around the player like volume, playback rate, captions, etc. to storage but every video should start from the beginning. So I don't want to persist the progress of each video.

### Describe:

It would be convenient if you could configure which data are persisted to storage.

**Comment by mihar-22** [comment]
No unfortuntely not atm.

**Comment by DerStimmler** [comment]
@mihar-22 thanks for the info 👍

**Comment by DerStimmler** [comment]
> You can do this by providing your own storage or extending our local storage:
> 
> ```ts
> import { LocalMediaStorage } from 'vidstack';
> 
> class CustomMediaStorage extends LocalMediaStorage {
>   async getTime() {
>     return null
>   }
>   
>   async setTime() {
>     // no-op
>   }
> }
> 
> // Provide the storage to the player via `storage` prop.
> player.storage = new CustomMediaStorage();
> ```

@mihar-22 I tried it like this, but can't make it work.

---

When I extend the `LocalMediaStorage` like this:
```
import {LocalMediaStorage} from "vidstack";

export class CustomLocalMediaStorage extends LocalMediaStorage {
}
```
and set the storage like this 
`this.player.storage = new CustomLocalMediaStorage();`
**ONLY** the time gets saved to local storage.

Therefore if I override the `getTime()` and `setTime()` methods like in the example above nothing gets written to local storage.

It seems like the change detection for all storage properties except time is broken when providing a custom storage object, or am I missing something?

Also while testing I noticed that I can't import the `SerializedVideoQuality` type from `"vidstack"` like this:
```
import {SerializedVideoQuality} from "vidstack"
```

**Comment by mihar-22** [comment]
Thanks I'll look into it!

**Comment by mihar-22** [comment]
I'm sorry it took me a while to get to this, there's been heaps of other things being worked on for the next release. It's been fixed and should be out this week with the other stuff :)

**Comment by mihar-22** [comment]
I'm testing in the next release exporting the core and player constructors, so you can do:

```html
<script type="module">
  import { VidstackPlayer, LocalMediaStorage } from "https://cdn.vidstack.io/player";
  
  class MyLocalStorage extends LocalMediaStorage {}
  
  const player = await VidstackPlayer.create({
    // ...
    storage:  MyLocalStorage
  })
</script>
```
