### ISSUE TITLE
Broken image icon briefly visible before poster is loaded

### ISSUE THREAD

**Issue by Curetix** [vidstack/player#1143]
### Current Behavior:

Before the poster has been loaded in, you can briefly the see the small broken image icon along with the image alt text.

### Expected Behavior:

Nothing should be visible until the poster has loaded (or failed to load).

### Steps To Reproduce:

Start an example Vidstack project, repeatedly refresh the page. 

### Environment:

Vidstack React v1.10.4

### Anything Else?

The moment before the poster loads:

![image](https://github.com/vidstack/player/assets/15160542/e2c1464a-1d76-4059-b5b4-b2739b8c384d)

**Comment by gustavjf** [comment]
Hello, I can still see this issue on v1.12.12

Here is a repo with the reproduction on the last commit of main: https://github.com/gustavjf/vidstack-broken-poster-image

The issue isn't present if the [alt tag](https://github.com/gustavjf/vidstack-broken-poster-image/blob/b22332dc9e6b830fac74325ec000c55457aa7b66/src/app/components/video-player/video-player.tsx#L21) for `<Poster>` is removed.
