### ISSUE TITLE
Cast button showing up irrespective of settings

### ISSUE THREAD

**Issue by joshcawthorne** [vidstack/player#1144]
### Current Behavior:

Using the most basic implementation of Vidstack with no layout, and controls set to false, a button to cast media still appears in the top-left of media in Chromium-based browsers.

### Expected Behavior:

Control to appear only if specified.

### Steps To Reproduce:

See [this codesandbox](https://codesandbox.io/p/devbox/vidstack-cast-9fsqj4) for basic reproduction. Tested using Chrome v121.0.6167.139 on MacOS.

### Environment:

Framework: React
Meta Framework: Next.js
Device: Macbook Pro
Browser: Chrome v121.0.6167.139

### Anything Else?

See screenshot for additional clarification; button is top left.

![ScreenShot 04-02-2024 at 12 29 09](https://github.com/vidstack/player/assets/17056399/86606b8b-5e32-42a6-a36e-3685cc1fa71d)

**Comment by mihar-22** [comment]
I don't see it. Could it be coming from a plugin or something you're using. That's not rendered by our player.

**Comment by wplit** [comment]
> I don't see it. Could it be coming from a Chrome plugin or something you're using? That's not rendered by our player.

I see it also. Chrome/Macbook See screenshot below.

![SCR-20240207-mqrp](https://github.com/vidstack/player/assets/43051571/7acba51e-f542-4d89-b3cc-73dbcf3c99d7)

Being added by the browser if casting is available. Can be hidden with CSS..

`video::-internal-media-controls-overlay-cast-button {
    display: none;
}`

**Comment by mihar-22** [comment]
Oh I see, this is just standard video element behaviour. Typically need to add `disableRemotePlayback` to the `<video>` element to prevent this showing. We can't determine when to add that from our end so you can either use CSS to hide as @wplit has shown above, or you can set the `disableRemotePlayback` prop on the `<video>` element. Refer to [this link](https://www.vidstack.io/docs/player/api/providers/video?styling=default-theme#element) on how to get the element reference.

**Comment by joshcawthorne** [comment]
Thanks for the suggestion @wplit. 

For anyone who stumbles here in the future looking for an answer on how to disable this for your browser globally (vs just via CSS on a specific site), disabling the [media-remoting-without-fullscreen flag](chrome://flags#media-remoting-without-fullscreen) in chrome://flags will stop the button from displaying!
