### ISSUE TITLE
Using Props

### ISSUE THREAD

**Issue by abvas** [vidstack/player#1146]
Hello!

Can't get some Props to work

For example, how to use "controls"?

I'm using CDN-Video-Default Layout

```
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vidstack@^1.0.0/player/styles/default/theme.min.css"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vidstack@^1.0.0/player/styles/default/layouts/video.min.css"/>
<script src="https://cdn.jsdelivr.net/npm/vidstack@^1.0.0/cdn/with-layouts/vidstack.js" type="module"></script>
</head>

<body>
<media-player title="Sprite Fight" 
  src="https://stream.mux.com/VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU/low.mp4" 
  controls=false>
   <media-provider></media-provider>
   <media-video-layout thumbnails="https://image.mux.com/VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU/storyboard.vtt"></media-video-layout>
</media-player>
</body>
```

By adding "controls=false" I want to disable the controls, but it doesn't work and I get the error:
Uncaught TypeError: Cannot set property controls of #<Re> which has only a getter
![Image 54](https://github.com/vidstack/player/assets/47285364/ec1f96a4-1b18-4013-9d34-ff085ff134d0)

Or, for example, clipStartTime=60 there is no error, but it still doesn’t work.

Please tell me what exactly I'm doing wrong.
Thank you.

**Comment by mihar-22** [comment]
You need to set attributes correctly using kebab-case and quotes (e.g., `clip-start-time="60"`) in HTML, and if you want to set properties you need to set them in JS by getting a reference to the player. You might need to review how HTML and the DOM works.

**Comment by abvas** [comment]
Thank you.
It works with clip-start-time="60".

But I was never able to disable the control panel.

I'm trying to do this:
```
const instance = document.querySelector("media-player");
instance.setAttribute("controls", false);
```

But I still get the error:
`Bug in custom code TypeError: Cannot set property controls of #<Re> which has only a getter`

**Comment by mihar-22** [comment]
You don’t need to disable anything. The controls attribute is for native UI. You’re currently using a custom layout, if you simply remove the media-video-layout there will be no controls.
