### ISSUE TITLE
Video Player Disappears: A Nextjs 14

### ISSUE THREAD

**Issue by OmarTaheri** [vidstack/player#1147]
### Current Behavior:
![image](https://github.com/vidstack/player/assets/86674378/3c6ab59c-964d-46fa-b64c-dfa3f2265094)

when i change the src the player disapear from the ui, and i am getting this error:
![image](https://github.com/vidstack/player/assets/86674378/148496fd-81ce-4804-a7bb-6336f7ed5907)

### Expected Behavior:
When i change a video it should be showen in the place of the old video.

### Environment:
Nextjs 14

**Comment by mihar-22** [comment]
Fixing another bug caused a regression, it's resolved now and I'll release in a moment.
