### ISSUE TITLE
Setting controls prop causes warning irrespective of how it's set

### ISSUE THREAD

**Issue by c0bra** [vidstack/player#1149]
### Current Behavior:

`<MediaPlayer ... controls={true}>` causes this warning: <code>Received the string `true` for the boolean attribute `controls`. Although this works, it will not work as expected if you pass the string "false". Did you mean controls={true}?`</code>

### Expected Behavior:

`<MediaPlayer ... controls={true}>` should cause no warning.

### Steps To Reproduce:

```jsx
<MediaPlayer
  src={...}
  controls={true}
>
  <MediaProvider />
</MediaPlayer>
```

### Environment:

- Framework: React
- Meta Framework: Next.js
- Node: 20
- Device: Macbook
- OS: Macos
- Browser: Chrome@121

**Comment by c0bra** [comment]
This line, possibly?

https://github.com/vidstack/player/blob/06353d82d467e2f3499914789915ed3fe420fcb0/packages/react/src/components/provider.tsx#L156

**Comment by mihar-22** [comment]
Sorry for the delay, I've been off helping family with renovations. That looks like the issue, nice catch. Fixed and I'll release today.
