### ISSUE TITLE
Action display should trigger on click to play/pause

### ISSUE THREAD

**Issue by BlakeB415** [vidstack/player#1150]
### Related Problem:

Pressing space triggers action display, while clicking on the video player to pause it does not.

### Describe:

When clicking the player to play or pause, the action display should show up for that state change.

**Comment by mihar-22** [comment]
For now I'm limiting this to keyboard actions to keep it simple. I'm not sure why YT shows it on presses, might be a bug or just how they prefer it. Happy to reconsider in the future.
