### ISSUE TITLE
Vimeo - Quality settings not available from menu

### ISSUE THREAD

**Issue by wplit** [vidstack/player#1151]
With some Vimeo videos, even if the original video when watched at the Vimeo site has quality options, it doesn't get picked up by the player.

Example where quality setting is available at Vimeo, but isn't showing inside settings menu...

https://vimeo.com/95995610

Example where both quality & speed settings are available both on Vimeo site and when inside Vidstack player

https://vimeo.com/367311357

**Comment by mihar-22** [comment]
We're using the embed APIs available to us, not sure we can do much here. Maybe it's a pro feature or something?
