### ISSUE TITLE
VTTContent type does not work as described in 1.10 release discussion

### ISSUE THREAD

**Issue by mnervik** [vidstack/player#1152]
### Current Behavior:

When using the code as described in the 1.10 release discussion, the types don't work as intended

The bellow is code copied from the 1.10 release discussion
```tsx
import { type VTTContent } from '@vidstack/react';

const content: VTTContent = {
  regions: [],
  cues: [
    { startTime: 0, endTime: 5, text: '...' },
    { startTime: 5, endTime: 10, text: '...' },
  ],
};

// Provide JSON directly (can also be serailized - JSON.stringify).
<Track content={content} label="English" kind="captions" lang="en-US" type="json" />;
```

The above code does not work / gives typescript errors, more specifially it's this part
```tsx
const content: VTTContent = {
  regions: [],
  cues: [
    { startTime: 0, endTime: 5, text: '...' },
    { startTime: 5, endTime: 10, text: '...' },
  ],
};
```

### Environment:

- Framework: React
- Meta Framework: Next.js

### Anything Else?

This code works though, so my guess is that your're missing the array-part in the type decralation
```tsx
const content: VTTContent = {
    regions: { id: '', scroll: '' },
    cues: { startTime: 0, endTime: 5, text: '...' }
}
```

**Comment by MrVibe** [comment]
This is still not resolved. Facing similar issue. Also, JSON.parse is added which means we have to send JSON.stringify in the content part.

**Comment by mihar-22** [comment]
Tested on latest and it's working as expected. You don't need to `JSON.stringify` but it's supported.
