### ISSUE TITLE
Full screen button doesn't work on iOS for YouTube (mp4 works)

### ISSUE THREAD

**Issue by rustam-abraham** [vidstack/player#1154]

**Comment by mihar-22** [comment]
YouTube embed doesn’t expose a fullscreen method so we can’t support it. iOS on iPhone doesn’t support the Fullscreen API yet but it’s actually coming in iOS 7.4 which will mean this will finally work.

**Comment by wplit** [comment]
> YouTube embed doesn’t expose a fullscreen method so we can’t support it. iOS on iPhone doesn’t support the Fullscreen API yet but it’s actually coming in iOS 17.4 which will mean this will finally work.

is it not possible to trigger the native IOS full screen if the fullscreen button is pressed? Basically recreate what would happen if we clicked the Youtube embed directly, which opens it up to full screen? Similar to if playsinline is off?

**Comment by mihar-22** [comment]
No there's no API for it. We can only access the API exposed through the `<iframe>` using `postmessage`, there's no `<video>` element to request fullscreen on.

**Comment by AVargas89** [comment]
Fullscreen button still not showing in iOS v18.3.2?
