### ISSUE TITLE
Vidstack Player fails to register on a clean install of SvelteKit

### ISSUE THREAD

**Issue by silasabbott** [vidstack/player#1156]
### Current Behavior:

'vidstack/bundle' doesn't appear to register any styles or elements in the latest versions of SvelteKit. Importing each style/script manually has the same behavior.

### Expected Behavior:

The video should be loaded and all UI elements should appear.

### Steps To Reproduce:

[**Reproduction** →](https://stackblitz.com/edit/sveltejs-kit-template-default-g9v9mx?file=src%2Flib%2Fplayer%2FPlayer.svelte)

1. Set up a fresh SvelteKit project with create-svelte
2. Install vidstack and create a Player.svelte component according to the official documentation for SvelteKit
3. Ensure the Player.svelte element only imports/executes in the browser
4. Run the project and observe that media does not load, ui doesn't appear, and there are no errors thrown

### Environment:

- Framework: Svelte
- Meta Framework: SvelteKit
- Node: 18.19.x
- Device: Macbook Pro M1 2021, iPhone 13
- OS: macOS Ventura 13.4.1
- Browser: Firefox 121.01, Arc 1.27.3, Safari 16.5.2

### Anything Else?

Here is a [simple reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-g9v9mx?file=src%2Flib%2Fplayer%2FPlayer.svelte). I observed this in my own project initially. In some cases, depending on which 'vidstack/...' files are imported, the vite dev server will hang until exited.

**Comment by mihar-22** [comment]
Turns out it's the order of the plugins. The Vidstack plugin must come before the SvelteKit plugin. I'll update docs accordingly.

```ts
import { sveltekit } from '@sveltejs/kit/vite';
import { vite as vidstack } from 'vidstack/plugins';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [vidstack({ include: /player\// }), sveltekit()]
});
```

**Comment by silasabbott** [comment]
Awesome 🎉 yep that seems to fix it.

In my own project, all scripts and style are now loading except for `'vidstack/player/styles/default/theme.css'`. It's causing this error in the browser:
```
TypeError: error loading dynamically imported module: src/lib/components/player/Player.svelte
```

Looks like a separate problem though so I'll create another issue for that one.
