### ISSUE TITLE
Vidstack layout is deformed in preview

### ISSUE THREAD

**Issue by devpapi0891** [vidstack/player#1158]
### Current Behavior:

Im creating a project using sveltekit and vidstack. The play looks good and ok with pnpm dev. But after I did pnpm build then pnpm preview, its layout was deformed same with using node ./build. Here is what it looks like on preview
WIDE screen
![image](https://github.com/vidstack/player/assets/97945953/141c42eb-0e4a-4cc6-a201-179e0b78b13c)

Mobile screen
![image](https://github.com/vidstack/player/assets/97945953/a6201f1f-0d09-4acf-8c00-40d70579fec5)

I am just following the most simplest instruction in the documentation. Again this happened only on build but in dev its okay

Here is my pattern
1. Select Framework: Svelte
2. Select Bundler: None, also tried Sveltekit
3.  Select Provider: Hls
4. Select Styling: Default Layout

```bash
npm i vidstack@next hls.js
```
Then follow steps as how it was given in the documentation.

Then using adapter-node i did 

```bash
pnpm build

pnpm preview
```

Again the bug only be seen in build preview

**Comment by devpapi0891** [comment]
I also tried and reproduce the bug to reproduce

Docs step I followed


My steps

```bash
pnpm create svelte@latest

npm i vidstack@next hls.js

```

I followed this steps

https://www.vidstack.io/docs/player/getting-started/installation/svelte?bundler=none&provider=hls&styling=default-layout

```bash
pnpm build
pnpm preview
```
![image](https://github.com/vidstack/player/assets/97945953/ab63a73a-598b-4636-af47-552a8d92a179)
![image](https://github.com/vidstack/player/assets/97945953/053d840e-aa4e-4a18-a580-47c5f23acbfb)

**Comment by mikeyhodl** [comment]
Am also getting the same problem since today, was working well before

**Comment by mihar-22** [comment]
I'm testing it now and it's working as expected. Followed the exact same steps. It installed `@sveltejs/kit@2.5.0` and `vite-plugin-svelte@3.0.2`

**Comment by mihar-22** [comment]
By the way, there was a small mistake in our SvelteKit bundler option. The plugin order was incorrect. [See the fix](https://github.com/vidstack/player/issues/1156#issuecomment-1937040174) if you'd like to use it instead.

**Comment by devpapi0891** [comment]
Thanks! I tested it on new setup of svelte project and it works good. I also want to mention that for some reason I need to remove purgeCss() to the actual project for vidstack to work properly. I also tried rearranging their position but the one the works for me is to disable it. I hope this helps.

![image](https://github.com/vidstack/player/assets/97945953/d635dd31-4ff9-4e31-8121-5bf31c0b2872)
