### ISSUE TITLE
Settings menu unclickable in mobile

### ISSUE THREAD

**Issue by vpreponen** [vidstack/player#1163]
### Current Behavior:

Clicking the settings icon in the Svelte or Web Components default layout with `size="sm"` opens the settings menu to the bottom of viewport and the menu options can't be clicked because the menu closes with every click.

### Expected Behavior:

React default layout works as expected https://stackblitz.com/edit/vidstack-examples-jv627c

### Steps To Reproduce:

1. Go to https://stackblitz.com/edit/vidstack-examples-wn3zz2
2. Resize preview until layout has attribute `size="sm"`
3. Click settings and try to click a menu option such as speed or captions

![image](https://github.com/vidstack/player/assets/1275980/64df48d3-1e78-4d4a-9388-c32bd75f4af3)

**Comment by abvas** [comment]
Yes, I noticed that too. This happens because pointer-events: none;
Can be seen on the demo page: https://www.vidstack.io/docs/wc/player/components/layouts/default-layout?styling=default-theme
![Image 67](https://github.com/vidstack/player/assets/47285364/911a4d96-6dcb-4a98-8c22-1abaf32dff84)

**Comment by Aksentijevic** [comment]
Same thing on the desktop. When data-resizing is set, settings is not clickable.

**Comment by mihar-22** [comment]
Sorry everyone, I stuffed up some code and I was away for a bit helping family with renovations. Fixed and rolling it out today.
