### ISSUE TITLE
Trigger Keyboard Action Display on gestures

### ISSUE THREAD

**Issue by Curetix** [vidstack/player#1176]
### Describe:

It would be nice if the Default Layout Keyboard Action Display would also trigger for gesture actions (double tap to seek), similar to YouTube on mobile.

### Anything Else?

Screenshot from YouTube mobile player after double-tapping:

![Screenshot_20240220_234121_YouTube.jpg](https://github.com/vidstack/player/assets/15160542/1e9ab3bb-b0d6-4dfc-9bc0-93e005455ed6)

**Comment by mihar-22** [comment]
Thanks for the suggestion Curetix, I like this feature but it's not planned for now as I'm trying to wrap everything up, display is mainly focused on keyboard for now.
