### ISSUE TITLE
Storage & End of Video UX Problem 

### ISSUE THREAD

**Issue by langsys** [vidstack/player#1185]
This may be considered a bug as well.

When a user completes a video, but then later may return to the video, they do not expect the video player to fast forward to the last second, typically showing a black screen.  The user will be confused while looking for that little replay icon that replaces the play button.

Consider on playback complete, clear the currentTime storage so that subsequent loads of the video start fresh at the poster / 0 for a better user experience.

I do know I could customize your storage solution to do this myself, but I figured since its a core issue of User Experience, you might want to do it on your end?

**Comment by mihar-22** [comment]
This was reverted but you can manually add it if desired in the release:

```ts
onEnded() {
  // Clear saved time.
  player.storage?.setTime(-1);
}
```
