### ISSUE TITLE
Question regarding multiple sources

### ISSUE THREAD

**Issue by Sof2222** [vidstack/player#1189]
### URL:

I am looking at:
https://www.vidstack.io/docs/player/api/providers/video?styling=default-theme

From reading the documentation, I thought it meant we could add multiple videos inline - so for example if we had 2 videos, it would play the first, then the second video. However I cannot get it to work.. if it is meant to work like that then it is not working.
Else if it is supposed to just provide different formats upon request (unsure how to get that to work, but it is not in my use case at least) then the documentation does not really suggest that is what providing multiple src's to it does..

I am guessing I will be able to build the multiple video thing (so having a rough video combine thing) by using remotion, but that is going to be more complicated so want to check to see if this multiple src thing is meant to be what the docs imply it is, or if the docs need an update to show it is just to provide different formats.

### Describe:

For example in this one:
https://stackblitz.com/edit/vidstack-examples-ruyo1u?file=src%2Fplayer.tsx&showSidebar=1&title=Vidstack%20Player%20-%20React%20(Default%20Theme)

I tried updating player.tsx to this:

`import '@vidstack/react/player/styles/default/theme.css';

import { useEffect, useRef, useState } from 'react';

import styles from './player.module.css';

import {
  isHLSProvider,
  MediaPlayer,
  MediaProvider,
  Poster,
  Track,
  type MediaCanPlayDetail,
  type MediaCanPlayEvent,
  type MediaPlayerInstance,
  type MediaProviderAdapter,
  type MediaProviderChangeEvent,
  type MediaViewType,
} from '@vidstack/react';

import { AudioLayout } from './layouts/audio-layout';
import { VideoLayout } from './layouts/video-layout';
import { textTracks } from './tracks';

export function Player() {
  let player = useRef<MediaPlayerInstance>(null),
    [src, setSrc] = useState(''),
    [viewType, setViewType] = useState<MediaViewType>('unknown');

  useEffect(() => {
    // Initialize src.
    changeSource('audio');

    // Subscribe to state updates.
    return player.current!.subscribe(({ paused, viewType }) => {
      // console.log('is paused?', '->', paused);
      setViewType(viewType);
    });
  }, []);

  function onProviderChange(
    provider: MediaProviderAdapter | null,
    nativeEvent: MediaProviderChangeEvent,
  ) {
    // We can configure provider's here.
    if (isHLSProvider(provider)) {
      provider.config = {};
    }
  }

  // We can listen for the `can-play` event to be notified when the player is ready.
  function onCanPlay(detail: MediaCanPlayDetail, nativeEvent: MediaCanPlayEvent) {
    // ...
  }

  function changeSource(type: string) {
    const muxPlaybackId = 'VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU';
    switch (type) {
      case 'audio':
        setSrc('https://media-files.vidstack.io/sprite-fight/audio.mp3');
        break;
      case 'video':
        setSrc(`https://stream.mux.com/${muxPlaybackId}/low.mp4`);
        break;
      case 'hls':
        setSrc(`https://stream.mux.com/${muxPlaybackId}.m3u8`);
        break;
      case 'youtube':
        setSrc('youtube/_cMxraX_5RE');
        break;
      case 'vimeo':
        setSrc('vimeo/640499893');
        break;
    }
  }

  return (
    <>
      <MediaPlayer
        className={`${styles.player} media-player`}
        title="Sprite Fight"
        src={[
          { src: 'https://media-files.vidstack.io/720p.ogv', type: 'video/ogg' },
          { src: 'https://media-files.vidstack.io/720p.avi', type: 'video/avi' },
          { src: 'https://media-files.vidstack.io/720p.mp4', type: 'video/mp4' },
        ]}
        crossorigin
        playsinline
        onProviderChange={onProviderChange}
        onCanPlay={onCanPlay}
        ref={player}
      >
        <MediaProvider>
          
          {/* {textTracks.map((track) => (
            <Track {...track} key={track.src} />
          ))} */}
        </MediaProvider>

        {/* Layouts */}
        {/* {viewType === 'audio' ? (
          <AudioLayout />
        ) : viewType === 'video' ? ( */}
          <VideoLayout thumbnails="https://image.mux.com/VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU/storyboard.vtt" />
        {/* ) : null} */}
      </MediaPlayer>

      <div className={styles.srcButtons}>
        <button onClick={() => changeSource('audio')}>Audio</button>
        <button onClick={() => changeSource('video')}>Video</button>
        <button onClick={() => changeSource('hls')}>HLS</button>
        <button onClick={() => changeSource('vimeo')}>Vimeo</button>
      </div>
    </>
  );
}
`

**Comment by mihar-22** [comment]
It's for different formats which is implied by the same file names but different URL extensions and source types. We'll add a clarifying note to the docs for this.
