### ISSUE TITLE
hls autoStartLoad false not working

### ISSUE THREAD

**Issue by roshaninet** [vidstack/player#1190]
### Current Behavior:

in hls configuration when i set autoStartLoad false, player cant load video 

```
provider.library = Hls;
            provider.config = {
                autoStartLoad: false,
            };
```

### Expected Behavior:

play button must be apear and when i click on that, video must play.

### Steps To Reproduce:

you need just install player and set hls configuration autoStartLoad: false

**Comment by mihar-22** [comment]
See our [load strategies](https://www.vidstack.io/docs/player/core-concepts/loading?styling=default-theme#load-strategies) section.

**React**

```tsx
<MediaPlayer load="play">
```

**HTML**

```html
<media-player load="play">
```
