### ISSUE TITLE
Work with Remotion <Player> component

### ISSUE THREAD

**Issue by aaa3334** [vidstack/player#1193]
### Related Problem:

Note there are no examples of how it works with the remotion player, so I am not sure if it is possible or not, but what I have tested at least it does not seem to be.

### Describe:

When using Remotion, we sometimes want to display a video which has not yet been properly rendered. This could be in dev or in prod. This uses the 'Player' component
https://www.remotion.dev/docs/player/player
While this component can be used by itself, it would be nice for a streamlined approach to the actual player being used (as well as being able to use the different features vidstack offers but remotion does not).

### Alternatives:

This could be possible already, but I could not figure it out - so alternatively better examples of remotion + docs on how to do this.

**Comment by mihar-22** [comment]
We support Remotion through our [Remotion Provider](https://www.vidstack.io/docs/player/api/providers/remotion?styling=default-layout) which uses the same rendering process and options as Remotion Player. See our [Remotion Installation](https://www.vidstack.io/docs/player/getting-started/installation/react?provider=remotion&styling=default-layout) and the provider page linked for more options. The React examples can be used to guide with styling.
