### ISSUE TITLE
YouTube play failed with the error "Timed out"

### ISSUE THREAD

**Issue by creta-coder** [vidstack/player#1194]
When I pause player with api and after try to play getting error message "Timed out"

Vidstack version - 1.10.8

**Comment by mihar-22** [comment]
If you can provide a [repro](https://github.com/vidstack/player/blob/main/.github/REPRO.md) that would help a ton as I'm not sure what to look for right now. I can reopen when a repro is provided.

**Comment by creta-coder** [comment]
[repro](https://stackblitz.com/edit/vidstack-examples-qawbcv)

**Comment by creta-coder** [comment]
@mihar-22
