### ISSUE TITLE
Android: Fullscreen on mobile doesn't adapt to screen-rotation

### ISSUE THREAD

**Issue by dennisspohr** [vidstack/player#1202]
### Current Behavior:

Tested on Android: After playing a video in fullscreen and rotating the phone, the video doesn't rotate.
This is problematic for vertical videos: users want to watch the video in vertical-mode, so they can see the video in a bigger size. Currently the video doesn't adapt when rotating the phone.

### Expected Behavior:

The video-orientation should adapt in fullscreen mode, when rotating the phone.

### Screenshot:
<img src="https://github.com/vidstack/player/assets/10246331/f0048f2e-1b0a-4a11-b1fc-cb9be85e18f4" width="300">

**Comment by mihar-22** [comment]
The `fullscreenOrientation` player property or `fullscreen-orientation` attribute determines whether the screen orientation is _locked_ or not. By default it's set to `landscape`. You can disable it to allow screen rotations by setting it to `undefined`.

In the next release, you'll also be able to provide the string `"no"` to disable it.
