### ISSUE TITLE
Add option to silence `[vidstack] dev mode!`

### ISSUE THREAD

**Issue by insertmike** [vidstack/player#1203]
### Current Behavior:

`[vidstack] dev mode!` warning is raised on every rebuild while development. 

### Expected Behavior:

Add option to silence the warning. Whole development team is getting the message.

### Attachments

![image](https://github.com/vidstack/player/assets/45242072/e74bad25-c01c-4b68-b3c7-58510c1a7c19)

**Comment by mihar-22** [comment]
Sounds like you have a strange dev mode if it rebuilds constantly, and not sure what you mean by whole dev team is getting the message. It's normal for libs to log dev mode as it's not safe for prod. There's no real issue here, you can try filtering console logs if it bothers you that much.
