### ISSUE TITLE
Google Cast button shows when no casting devices exist

### ISSUE THREAD

**Issue by arghhhhh** [vidstack/player#1206]
### Current Behavior:

The Google Cast icon shows in the DefaultVideoLayout even when no Chromecast devices are available.

### Expected Behavior:

When casting is not available, the icon should disable or disappear. Either that, or a message should appear stating that no Chromecasts are available.

### Steps To Reproduce:

1. Open stackblitz link below and play the video.
2. On Firefox browser (windows), no cast icon is visible. This would be the correct behavior. However, on chromium browsers (both Windows and Android), a cast icon is visible.
3. Clicking the icon either does nothing (Android) or produces a floating media controller that seems to think a cast is occurring. 

**Reproduction Link:** 

[demo](https://stackblitz.com/edit/vidstack-player-focus-issue-akj1sy?file=README.md)

### Anything Else?

**Footage from Microsoft Edge**
![5b4d460f3dc3deb156af0c9361c49cf3](https://github.com/vidstack/player/assets/2746147/ec07d003-b555-4a4f-822b-fc52df3a767e)

**Console log from the demo**
![image](https://github.com/vidstack/player/assets/2746147/07961d36-b68a-4615-9c8e-98d0e353be4d)

**Comment by mihar-22** [comment]
I've improved error handling for Google Cast requests for the next release. By default it will now show a small toast at the top of the screen when no devices are available.

<img width="400" src="https://github.com/vidstack/player/assets/14304599/c89b5f2e-cb2c-4280-9a62-c7748cedd11b">

---

You will be able to handle the error yourself in the next release like so in React:

```tsx
function onGoogleCastPromptError(error: GoogleCastPromptError, nativeEvent: Event) {
  if (error.code === 'NO_DEVICES_AVAILABLE') {
    nativeEvent.preventDefault(); // prevent showing default toast.
    // do your own thing.
  }
}

<MediaPlayer onGoogleCastPromptError={onGoogleCastPromptError}>
```

**Comment by mihar-22** [comment]
I've temporarily reverted this while I find a more reliable way to detect no cast devices being available. It seems the cast framework was incorrectly saying there was none in a few cases.
