### ISSUE TITLE
Hide Youtube Recommendation after finish

### ISSUE THREAD

**Issue by zerowu49** [vidstack/player#1209]
### Current Behavior:

 After finish video, there **are** Youtube Video Recommendations
![end vidstack yt](https://github.com/vidstack/player/assets/22422143/9888be75-f4d6-4854-9cbd-73234f3bff57)

### Expected Behavior:

 After finish video, there is **nothing** to show (**hide** the recommendation)

### Steps To Reproduce:

1. Use module **@vidstack/react** 
2. Code:

```
import { MediaPlayer, MediaProvider } from "@vidstack/react";
import {
  PlyrLayout,
  plyrLayoutIcons,
} from "@vidstack/react/player/layouts/plyr";
import "@vidstack/react/player/styles/base.css";
import "@vidstack/react/player/styles/plyr/theme.css";

export const YoutubeVideo = ({ url }) => {
  return (
    <MediaPlayer src={url} autoplay playsInline>
      <MediaProvider />
      <PlyrLayout
        icons={plyrLayoutIcons}
        controls={[
          "play",
          "progress",
          "current-time",
          "mute+volume",
          "captions",
          "fullscreen",
        ]}
      />
    </MediaPlayer>
  );
};
```

### Environment:

- Framework: React
- Meta Framework: Next.js
- Node: 20.7.0
- OS: macOS@12.6.5
- Browser: Microsoft Edge@122.0.2365.92

**Comment by mihar-22** [comment]
You can place whatever you like at the end with some HTML and CSS:

```tsx
<MediaPlayer className="player">
  <MediaProvider>
    <div className="blocker" />
  </MediaProvider>
</MediaPlayer
```

```css
.player[data-ended] .blocker {
  /* ... */
}
```
