### ISSUE TITLE
iOS - [vidstack]: captions text track created without label: 'undefined'

### ISSUE THREAD

**Issue by sukijun** [vidstack/player#1216]
### Current Behavior:

After initialization in iOS, error: [vidstack]: captions text track created without label: 'undefined'

### Environment:

- Framework: React
- Meta Framework: Next.js
- Node: v20.9
- Device: iPhone X
- OS: iOS 16.7.4
- Browser: Chrome and Safari

I think it's related to "provider-change" event and native HLS on IOS

https://github.com/vidstack/player/assets/92907658/0d4f0a26-899c-4a37-a06d-de71df633d72

**Comment by nossila** [comment]
I'm having the same issue, using @vidstack/react version 1.10.9

**Comment by mihar-22** [comment]
This is dev only error. Your text tracks need labels so they show correctly in the menus. I've relaxed this to a console warning from an error.
