### ISSUE TITLE
Player jumps to end of video when video source chnaged

### ISSUE THREAD

**Issue by Viiprogrammer** [vidstack/player#1217]
### Current Behavior:

Player jumps to end of video when source changed

### Expected Behavior:

Player starts from 00:00

### Steps To Reproduce:

1. Go to https://stackblitz.com/edit/vidstack-examples-iqz5p6?file=src%2FPlayer.vue
2. Run play
3. Click "change"

### Environment:

- Framework: Vue
- OS: Ubuntu 22.04
- Browser: Electron / Firefox (I think other too)

**Comment by mihar-22** [comment]
It's because you're switching the source to a live stream.
