### ISSUE TITLE
The audio gain control mutes the video.

### ISSUE THREAD

**Issue by wplit** [vidstack/player#1224]
Using web components, both with either default layout or default theme.

Here's an example just with the default layout from the CDN doing the same thing..

https://codepen.io/wplit/pen/mdaNyjz

The video will play with sound at first, until you change the audio gain setting and then no sound. I hit the same issue when building a custom UI using the 'media-audio-gain-slider' component.

**Comment by mihar-22** [comment]
Console warning, need to add `crossorigin` to the player it seems. I wonder if we can detect this too.

<img width="479" alt="image" src="https://github.com/vidstack/player/assets/14304599/5649b6b1-997b-46c2-bb46-3cf54bef95f3">
