### ISSUE TITLE
Doesn't work without installing dashjs

### ISSUE THREAD

**Issue by DerStimmler** [vidstack/player#1225]
### Current Behavior:

Can't use the player without installing dashjs.

```
Error: node_modules/.pnpm/vidstack@1.11.6/node_modules/vidstack/dist/types/vidstack-Co2t7r7t.d.ts:3:23 - error TS2307: Cannot find module 'dashjs' or its corresponding type declarations.

3 import * as DASH from 'dashjs';
                        ~~~~~~~~




× Failed to compile.
```

When I install dashjs v4.7.4 the build succeeds.

### Expected Behavior:

Should be able to use vidstack with hls.js without installing dashjs.

### Steps To Reproduce:

Install vidstack v1.11.6 and use it with hls.js. Don't install dash.js.

### Environment:

- vidstack: 1.11.6
- Angular: 17

**Comment by mihar-22** [comment]
We can't remove those types but from your end it shouldn't be an issue. I think `skipLibCheck` is missing in your `tsconfig`?

**Comment by DerStimmler** [comment]
That's it. Thanks.

**Comment by kzwr** [comment]
I also encountered the same problem, now it is solved
