### ISSUE TITLE
Plyr Layout broken with Web Component

### ISSUE THREAD

**Issue by moomerman** [vidstack/player#1228]
### Current Behavior:

I've just upgraded from `1.10.9` to `1.11.7` and the Plyr Layout has broken.

Using the Web Component example from the docs:

```
<media-player title="Sprite Fight" src="https://files.vidstack.io/sprite-fight/720p.mp4">
  <media-provider></media-provider>
  <media-plyr-layout thumbnails="https://files.vidstack.io/sprite-fight/thumbnails.vtt"></media-plyr-layout>
</media-player>
```

on `1.10.9` this renders as

![image](https://github.com/vidstack/player/assets/23323/eeb9847d-c494-41ac-bb2e-982aee37df94)

But with `1.11.7` it is

![image](https://github.com/vidstack/player/assets/23323/7262d5e9-9dc6-423e-8c17-a39c1918a0de)

There are no errors in the console.

The Default Layout works as expected.  If I focus the black video area and press spacebar the video plays.

### Expected Behavior:

I expected the layout to remain the same after upgrading.

### Steps To Reproduce:

Follow [the example](https://www.vidstack.io/docs/player/getting-started/installation/web-components?bundler=none&provider=video&styling=plyr-layout) in the docs to install using the Web Component and Plyr Layout.

### Environment:

- Framework: Web Component
- Node: 20.12.0
- OS: macOS:14.4.1
- Browser: Safari@17.4.1

**Comment by mihar-22** [comment]
Ah wow, messed up our bundles 😓 Sorry about that! Pushing out fix in a moment, just looking at two other important bugs.

**Comment by iamlaristo** [comment]
@mihar-22 i'm still experiencing the same issue on 1.11.17, was it merged or did I miss something?
