### ISSUE TITLE
Custom state pseudo classes deprecation warning

### ISSUE THREAD

**Issue by DamianGlowala** [vidstack/player#1229]
LMK if this isn't self-explanatory and I'll provide more info (v1.11.7-next):
![image](https://github.com/vidstack/player/assets/48835293/ac97643f-9f9e-4f6f-bef3-9604c1a4dc58)

**Comment by mihar-22** [comment]
We don't use custom state pseudo-classes to style native media controls? Are you sure the warning is related to our library?

**Comment by DamianGlowala** [comment]
Thanks for confirming. This is coming from Vimeo player CSS. I've just reported it to them and waiting for a response.

![image](https://github.com/vidstack/player/assets/48835293/cd5231e9-fafa-49d6-b3a4-4669afc10760)
