### ISSUE TITLE
Youtube embed's setting button is not functioning properly

### ISSUE THREAD

**Issue by Jiaqi-ingenium** [vidstack/player#1230]
### Current Behavior:

The YouTube embed's setting button only has the "playback" option and the "playback" option is not clickable.
![Screenshot 2024-04-03 at 2 40 09 PM](https://github.com/vidstack/player/assets/141245934/5b749015-f556-47c2-83a2-6e2569ec0a43)
Before this new release, it had functioning "Captions" and "playback" options.

Here is my current setup:
```html
<media-player title="" src="https://www.youtube.com/watch?v=xxx" load="visible" class="video">
      <media-provider>
        <media-poster src="https://img.youtube.com/vi/xxx/0.jpg" alt="Youtube embed thumbnails"></media-poster>
        <track src="./dist/assets/xxx.vtt" kind="subtitles" label="English" srclang="en-US" default data-type="vtt" />
        <track src="./dist/assets/xxx.vtt" kind="subtitles" label="French" srclang="fr" default data-type="vtt" />
      </media-provider>
      <media-video-layout></media-video-layout>
    </media-player>
``` 

### Expected Behavior:

Expected more working options under the setting button, such as "Accessibility" and "Captions"
![Screenshot 2024-04-03 at 2 47 34 PM](https://github.com/vidstack/player/assets/141245934/2f3ddc56-258a-441c-8af1-1dfa47971ef2)

### Environment:

Example:
- Framework: Using the new CDN setup for Youtube and the Default Theme
```html
  <link rel="stylesheet" href="https://cdn.vidstack.io/player/theme.css" />
  <link rel="stylesheet" href="https://cdn.vidstack.io/player/video.css" />
  <script src="https://cdn.vidstack.io/player" type="module"></script>
``` 
- Browser: Chrome

**Comment by Jiaqi-ingenium** [comment]
After clicking on the setting button, here is the console error:
![Screenshot 2024-04-03 at 2 57 23 PM](https://github.com/vidstack/player/assets/141245934/f4be23d3-40e8-417e-b170-6ebcb3242500)

**Comment by mihar-22** [comment]
I can't repro, it might be because of some old locally stored rgb values. Clearing your local storage should do the trick.

**Comment by Jiaqi-ingenium** [comment]
> I can't repro, it might be because of some old locally stored rgb values. Clearing your local storage should do the trick.

Thanks for the reply, it was caused by some local js and it has been resolved.
