### ISSUE TITLE
[iOS] RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by sukijun** [vidstack/player#1231]
### Environment:

- Framework: React
- Meta Framework: Next.js
- Node: 21.6
- Device: iPhone X
- OS: iOS@16.7.7
- Browser: Safari

![Screenshot at Apr 04 2-05-52 PM](https://github.com/vidstack/player/assets/92907658/12061899-6283-4411-9405-9a0f872d0165)

![Screenshot at Apr 04 2-12-24 PM](https://github.com/vidstack/player/assets/92907658/dc6bfc54-8356-46d7-a124-68e969de5135)

https://github.com/vidstack/player/assets/92907658/06977282-9d0a-49eb-8e39-89928599bbb8

**Comment by mihar-22** [comment]
I’ll reopen this once a [repro](https://github.com/vidstack/player/blob/main/.github/REPRO.md) is provided. I don’t know what’s causing the issue in your screenshots.
