### ISSUE TITLE
https://cdn.vidstack.io/player/audio.css is 404

### ISSUE THREAD

**Issue by grussellduco** [vidstack/player#1232]
Following instructions here

https://www.vidstack.io/docs/player/getting-started/installation/javascript?styling=default-layout&provider=audio&install=cdn

 but https://cdn.vidstack.io/player/audio.css is 404ing causing my application to break.

**Comment by mihar-22** [comment]
Apologies, I was reworking our builds and messed up the CDN styles. It just got fixed, give the CDN a moment to update.
