### ISSUE TITLE
How to hide menu button in default layout?

### ISSUE THREAD

**Issue by DamianGlowala** [vidstack/player#1233]
Given the following Vue template:
```
<template>
    <media-player
        :src="src"
        playsinline
    >
        <media-provider />

        <media-video-layout />
    </media-player>
</template>
```
... how to entirely remove the following button?

![image](https://github.com/vidstack/player/assets/48835293/3f481146-f0b1-4417-802e-5d72eeb953cd)

I feel like there isn't much room for flexibility/composability at the moment, unless I missed relevant sections in the docs which describe how to achieve this. Thank you!

**Comment by mihar-22** [comment]
Hey Damian! This is not really an issue, please open questions in discussions or Discord :) You can hide it using CSS or you can opt to create your own layout (see our [examples](https://github.com/vidstack/examples)). There's tons of flexibility in our library, but unfortunately we don't have slots for our Web Component library yet like we do for React (add/replace existing content in our layout).

```css
.vds-settings-menu {
  display: none;
}
```

Also note our menus don't render anything when not open so there's no performance issue for leaving it.
