### ISSUE TITLE
Poster position incorrect with `VidstackPlayer.create`

### ISSUE THREAD

**Issue by Mister-Hope** [vidstack/player#1238]
![image](https://github.com/vidstack/player/assets/33315834/e6eda9ef-3315-4eb9-b840-df04810a2914)

![image](https://github.com/vidstack/player/assets/33315834/035b12c2-a104-42c4-85b7-93e2ad69efad)

Code:

```ts
import { VidstackPlayer, VidstackPlayerLayout } from "vidstack/global/player";
import "vidstack/player/styles/default/theme.css";
import "vidstack/player/styles/default/layouts/audio.css";
import "vidstack/player/styles/default/layouts/video.css";

// ...

await VidstackPlayer.create({
  src: [
    {
      src: 'https://files.vidstack.io/agent-327/720p.mp4',
      type: 'video/mp4',
    },
    {
      src:  'https://files.vidstack.io/agent-327/720p.avi',
      type: 'video/avi',
    },
    {
      src:  'https://files.vidstack.io/agent-327/720p.ogv',
      type: 'video/ogg',
    },
  ],
  tracks: [
    {
      src: 'https://files.vidstack.io/agent-327/subs/english.vtt',
      label: 'English',
      language: 'en-US',
      kind: 'subtitles',
      default: true,
    },
    {
      src: 'https://files.vidstack.io/agent-327/subs/spanish.vtt',
      label: 'Spanish',
      language: 'es-ES',
      kind: 'subtitles',
    },
    {
      src: 'https://files.vidstack.io/agent-327/subs/french.vtt',
      label: 'French',
      language: 'fr-FR',
      kind: 'subtitles',
    },
    {
      src: 'https://files.vidstack.io/agent-327/subs/german.vtt',
      label: 'German',
      language: 'ge-GE',
      kind: 'subtitles',
    },
    {
      src: 'https://files.vidstack.io/agent-327/subs/italian.vtt',
      label: 'Italian',
      language: 'it-IT',
      kind: 'subtitles',
    },
    {
      src: 'https://files.vidstack.io/agent-327/subs/russian.vtt',
      label: 'Russian',
      language: 'ru-RU',
      kind: 'subtitles',
    },
    // Chapters
    {
      src: 'https://files.vidstack.io/agent-327/chapters.vtt',
      kind: 'chapters',
      language: 'en-US',
      default: true,
    },
  ],
  poster: "https://files.vidstack.io/agent-327/poster.png",
  layout: new VidstackPlayerLayout({
    colorScheme: "light",
  }),
})
```

I see that a video is displayed to preload these medias, but it's not hidden.

I did not add any extra style and I confirm that the video element used to preload is not hidden correctly, at least it's not me displaying it:

![image](https://github.com/vidstack/player/assets/33315834/eacca150-9dea-4f51-b843-5ee165637664)

**Comment by mihar-22** [comment]
I don’t understand what’s happening here. Can you show the HTML you’re targeting and I don’t see a target config. If you can provide a repro that would help me understand.

https://github.com/vidstack/player/blob/main/.github/REPRO.md

**Comment by Mister-Hope** [comment]
The target is a Vue ref HTMLDivElement, mainly like this:

```vue
<template>
  <div ref"vidstack"></div>
</template>

<script setup>
import { ref } from 'vue'

const vidstack = ref()

// ...

onMounted(async ()=> {
  await VidstackPlayer.create({
    target: vidstack.value
  })
})
```

It should be equal to `target: HTMLDivElement`

**Comment by mihar-22** [comment]
Thank you, I’ll test this tomorrow and get back to you.

**Comment by Mister-Hope** [comment]
Some updates, a reproducion can be found at https://vuepress-theme-hope.github.io/v2/components/zh/guide/media/vid-stack.html, the component can be found at https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/components/src/client/components/VidStack.ts

The style file is here: https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/components/src/client/styles/vidstack.scss

And I double check that our normalize style on `<img>` and `<video>` has no effect on VidStack.
