### ISSUE TITLE
Types broken with `MediaProviderAdapter `

### ISSUE THREAD

**Issue by Mister-Hope** [vidstack/player#1239]
See https://www.vidstack.io/docs/wc/player/api/providers/hls?styling=default-theme#loading

![image](https://github.com/vidstack/player/assets/33315834/4b2ee23a-4aaf-467f-8db6-23a0714f2992)

The docs says that we can set `library` property on `provider` to change how to load the provider (Background: JSDeliver is nearly inaccessible in China)

However, the provider has type `MediaProviderAdapter | null`, and there is no library field on `MediaProviderAdapter`:

![image](https://github.com/vidstack/player/assets/33315834/1f0ffab1-127e-4552-a7b6-c0adb2cdc20a)

**Comment by mihar-22** [comment]
That soft provider type checking was designed for CDN users so TS types are not considered there. You have some options:

Option 1. Use `player.provider` which will cast to the correct type:

```ts
if (player.provider?.type === 'hls') {
}
```

Option 2. Cast to `AnyMediaProvider`:

```ts
import type { AnyMediaProvider } from 'vidstack';

const provider = event.detail as AnyMediaProvider;
if (provider?.type === 'hls') {
}
```

Option 3. Cast the type yourself:

```ts
import type { HLSProvider } from 'vidstack';

if (provider?.type === 'hls') {
  const hls = provider as HLSProvider;
}
```

**Comment by Mister-Hope** [comment]
Hi, you may need to reopen this:

![image](https://github.com/vidstack/player/assets/33315834/221c8370-971d-4ccf-afee-c13ff774c73e)


The type is different with docs:

![image](https://github.com/vidstack/player/assets/33315834/07690c60-4d19-4d62-a081-c8d0867cc3d3)
![image](https://github.com/vidstack/player/assets/33315834/5d134cde-c1de-4975-ae75-366597222f86)

From the docs, VisStack is expecting dash package default import while the types is expecting `MediaPlayer` on it.

Please if one of this.

**Comment by Mister-Hope** [comment]
@mihar-22 reping
