### ISSUE TITLE
Audio Gain Slider component always hidden with Youtube/Vimeo videos

### ISSUE THREAD

**Issue by wplit** [vidstack/player#1244]
When I change the src to any Youtube/Vimeo video, the audio boost control is no longer able to be used.

aria-disabled=true is added to the slider, so it's always hidden.

<img width="990" alt="SCR-20240409-prcd" src="https://github.com/vidstack/player/assets/43051571/0af716c3-cee9-44f8-93e7-d155e918238e">

edit - I was building with web components, using default theme. Vidstack v1.11.16 Markup exactly as in [the docs](https://www.vidstack.io/docs/wc/player/components/sliders/audio-gain-slider?styling=default-theme).

I don't see the same issue with mp4, DASH or HLS providers, only when Youtube or Vimeo.

**Comment by mihar-22** [comment]
Audio boost uses the [`GainNode`](https://developer.mozilla.org/en-US/docs/Web/API/GainNode) API to amplify audio output. This is not available through embed APIs.
