### ISSUE TITLE
Loop interruption for multiple vimeo videos (qutoplay and loop enabled) when cvdeo exits viewport

### ISSUE THREAD

**Issue by Katrienvh** [vidstack/player#1245]
### Current Behavior:

When a Vimeo video is set to autoplay and loop, it fails to restart when it's out of the viewport.

This problem arises only when there are multiple videos playing concurrently, with the looping feature activated, and one of the playing videos is out of the viewport upon completion.

### Expected Behavior:

The first video should restart automatically upon completion, as the loop feature remains active regardless of whether it is within the viewport of the website

### Steps To Reproduce:

- On the example page provided, there are two Vimeo videos.
- When the first video begins playing automatically (autoplay), scroll down to the bottom of the page where the second video is located. Ensure that the first video is no longer visible on the screen. 
- Proceed to watch the second video until it restarts. 
- Then, scroll back up to the first video. If the first video has concluded and hasn't restarted, the issue manifests. 

**Reproduction Link:** [Codepen example](https://codepen.io/katrienvh/pen/OJGZZmy)

**Comment by liam-macann** [comment]
I can reproduce the issue with only a single video playing, but actually came to report Vimeo loops failing when the cursor is hovering over a video. This seems the case both with and without controls.

**Comment by Katrienvh** [comment]
I'm able to replicate the problem even when there's only one video on the webpage. Additionally,

@liam-macann I've observed quite a few more issues while hovering over the video, although it doesn't happen every time.
