### ISSUE TITLE
NPM repository

### ISSUE THREAD

**Issue by tiarebalbi** [vidstack/player#1248]
### Current Behavior:

Current repository on NPM is showing a very old version, by following the installation process, npm installed by default the version `0.6.x`.

https://www.npmjs.com/package/@vidstack/react

### Expected Behavior:

when running  `npm i @vidstack/react` install the latest version, as of today, 04/12, `1.11.17`

**Comment by tiarebalbi** [comment]
noticed that the latest tag is the one set to `0.6.x`

**Comment by mihar-22** [comment]
We're on pre-release at the moment, not main. The install docs show to run `npm i @vidstack/react@next`. We'll soon be on latest.
