### ISSUE TITLE
Opening the Settings Menu throws an Exception in some cases

### ISSUE THREAD

**Issue by PJUllrich** [vidstack/player#1249]
### Current Behavior:

When I open the `Settings` in some videos, the settings menu doesn't show and an exception is raised.

#### Demo video:

https://github.com/vidstack/player/assets/10426523/151ee766-bcbb-4fd9-b589-5a3768211cb6

#### Example Link

To replicate it, open this link, play the promo video at the top of the page, and the "Preview" video of the `What is Elixir?` lesson. A modal should open with a second player. If you click the settings gear in the second player, the error message is logged in the Console.

Interestingly, the other previews mostly work. It seems to depend on the video that you try to play (you'll also see that in the demo video above where it works for most videos, but not for some). I'm not sure how the "broken" videos are different from the "working" videos though.

https://indiecourses.com/catalog/c102d919-b43e-46c4-960d-8a473c4458da

#### Exception message

```
Uncaught TypeError: Cannot read properties of undefined (reading '$$')
    at kf.sb (app-55c9b97dfadc5a6a6e754056ade417f9.js?vsn=d:1:23262)
    at kf.W1 (app-55c9b97dfadc5a6a6e754056ade417f9.js?vsn=d:1:22920)
    at kf.connectedCallback (app-55c9b97dfadc5a6a6e754056ade417f9.js?vsn=d:1:21473)
    at wr.k (app-55c9b97dfadc5a6a6e754056ade417f9.js?vsn=d:69:4179)
    at wr.$ (app-55c9b97dfadc5a6a6e754056ade417f9.js?vsn=d:69:4253)
    at wr.g (app-55c9b97dfadc5a6a6e754056ade417f9.js?vsn=d:69:4639)
    at wr._$AI (app-55c9b97dfadc5a6a6e754056ade417f9.js?vsn=d:69:4085)
    at sf.setValue (app-55c9b97dfadc5a6a6e754056ade417f9.js?vsn=d:69:8929)
    at sf.hl (app-55c9b97dfadc5a6a6e754056ade417f9.js?vsn=d:69:11119)
    at sf.o (app-55c9b97dfadc5a6a6e754056ade417f9.js?vsn=d:69:11155)
```

```javascript
    function sb(t) {
        if (this.isConnected) {
            if (t) {
                t.keepAlive && t.forwardKeepAlive && (this.keepAlive = !0,
                this.setAttribute("keep-alive", ""));
                let e = this.$.$$.d;
                e && t.$.$$.f.append(e) <---- Error occurs here
            }
            this[ab]()
        }
    }
```

### Expected Behavior:

No exception is raised when I open the settings menu.

### Steps To Reproduce:

**Reproduction Link:** [How to create a repro?][repro]

[repro]: https://github.com/vidstack/player/blob/main/.github/REPRO.md

### Environment:

```
macOS Sonoma 14.4
Arc Browser Version 1.38.0 (48670)
theme: default
"vidstack": "^1.11.11"
```

**Comment by mihar-22** [comment]
Thanks for the detailed error report @PJUllrich! 

This seems strange as that specific error would only happen if the component instance (`$`) is destroyed. By default, the player destroys itself after two animation frame ticks after it's disconnected from the DOM and not connected back (unfortunate workaround since there's no such thing as "destroyed" for Custom Elements). 

This means the player component is somehow destroyed and then reconnected to the DOM. This can happen with routers which are diffing the DOM and remounting the player somehow after a set period of time. Is this possible in your case? If it is the case, you can add `keep-alive` like so `<media-player keep-alive>` and then call `player.destroy()` on the player DOM element when you are ready (e.g., `const player = document.querySelector("media-player")`).

If there's no JS managing any of this then that's definitely interesting and requires further digging. Outside of you calling destroy yourself, we'd need to figure out what's happening.

**Comment by bjarnef** [comment]
I noticed this as well using `vidstack@1.11.17`

In this case rendering two instances of a `Player.vue` in a modal and one inline.
If opening the modal first and closing the afterwards, it doesn't seem to open settings menu in inline player, but if opening settings menu directly in inline player it works and also afterwards in player opened in modal, but after closing modal the settings menu in inline player stops working.

Player.vue with Nuxt:

```
<script lang="ts" setup>
import { isHLSProvider, type MediaCanPlayEvent, type MediaProviderChangeEvent } from 'vidstack'
import type { MediaPlayerElement } from 'vidstack/elements'

// Import styles.
import 'vidstack/player/styles/default/theme.css'
import 'vidstack/player/styles/default/layouts/audio.css'
import 'vidstack/player/styles/default/layouts/video.css'

// Register elements.
import 'vidstack/player'
import 'vidstack/player/layouts'
import 'vidstack/player/ui'

const $player = ref<MediaPlayerElement>()

const embed = ref<{src?: string}>({ src:'' })

onMounted(async () => { 
    const dialogRef = inject('dialogRef') as any // which type?
    const params = dialogRef?.value?.data

    if (params) {
      embed.value.src = params.src
    }
})

const onProviderChange = (event: MediaProviderChangeEvent) => {
  const provider = event.detail
  // We can configure provider's here.
  if (isHLSProvider(provider)) {
    provider.config = {}
  }
}

// We can listen for the `can-play` event to be notified when the player is ready, but not used at the moment
const onCanPlay = (event: MediaCanPlayEvent) => {
}

const src = computed(() => embed.value.src ?? '');
</script>

<template>
    <media-player 
      class="player"
      :src="src"
      crossorigin
      playsinline
      @provider-change="onProviderChange"
      @can-play="onCanPlay">
      <media-provider>
        <media-poster
          class="vds-poster"
          alt="">
        </media-poster>
      </media-provider>    
      <!-- Layouts -->
      <media-audio-layout />
      <media-video-layout />
    </media-player>
</template>

<style lang="scss" scoped>
.player {
  --brand-color: #f5f5f5;
  --focus-color: #4e9cf6;

  --audio-brand: var(--brand-color);
  --audio-focus-ring-color: var(--focus-color);
  --audio-border-radius: 2px;

  --video-brand: var(--brand-color);
  --video-focus-ring-color: var(--focus-color);
  --video-border-radius: 2px;

  /* 👉 https://vidstack.io/docs/player/components/layouts/default#css-variables for more. */
}

.player[data-view-type='audio'] media-poster {
  display: none;
}

.player[data-view-type='video'] {
  aspect-ratio: 16 /9;
}
</style>
```

**Comment by PJUllrich** [comment]
@mihar-22 thank you, the `keep-alive` did the trick. Now, the chapters show and I don't see any error logs anymore! I'll close it for now because my issue has been fixed.
