### ISSUE TITLE
shortcut keys not working as expected

### ISSUE THREAD

**Issue by LiReNa00** [vidstack/player#1252]
### Current Behavior:
When I hold seek forward/backward shortcut key for long time it only goes forward by 10 sec 

### Expected Behavior:
It should keep seeking forward until key is released (this was the case before but with new ui ... it's like this now)

### Steps To Reproduce:
same default configurations as provided in docs of vidstack

**Comment by mihar-22** [comment]
Fixed in latest release `1.11.18@next`
