### ISSUE TITLE
cdn.vidstack.io is not accessable in some countries

### ISSUE THREAD

**Issue by mahdiar** [vidstack/player#1253]
Hi
Thanks for your nice player. I have a problem with new CDN. I can't use it in Iran so my visitors can watch videos in my sites.
Is it possible to have more CDNs or other ways for Iranians to use this?

Regards

**Comment by mihar-22** [comment]
We rely on [`https://jsdelivr.com`](https://jsdelivr.com) to deliver our packages as it's freely available and has the best performance in our testing. You'll need to find a suitable CDN for your country that supports NPM packages, or you can host the NPM package yourself which would require some more work for version control and so on. I'm not aware of any other alternative options, if you dig around you might find some.

All files are available in our [`@vidstack/cdn`](https://www.npmjs.com/package/@vidstack/cdn) package.

**Comment by mahdiar** [comment]
> We rely on [`https://jsdelivr.com`](https://jsdelivr.com) to deliver our packages as it's freely available and has the best performance in our testing. You'll need to find a suitable CDN for your country that supports NPM packages, or you can host the NPM package yourself which would require some more work for version control and so on. I'm not aware of any other alternative options, if you dig around you might find some.
> 
> All files are available in our [`@vidstack/cdn`](https://www.npmjs.com/package/@vidstack/cdn) package.

I have no issue with https://jsdelivr.com/ but just with cdn.vidstack.io. Maybe there is some limitation in cdn.vidstack.io.

**Comment by mihar-22** [comment]
Can you share the error or issue you’re facing?

**Comment by mahdiar** [comment]
Secure Connection Failed

An error occurred during a connection to cdn.vidstack.io. PR_END_OF_FILE_ERROR

Error code: PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
