### ISSUE TITLE
Youtube Poster not working as expected

### ISSUE THREAD

**Issue by IamManchanda** [vidstack/player#1265]
### Current Behavior:

Youtube Poster not working

### Expected Behavior:
Youtube Poster should work

### Steps To Reproduce:

```
<MediaPlayer src="youtube/_cMxraX_5RE">
    <MediaProvider />
     <DefaultVideoLayout icons={defaultLayoutIcons} />
</MediaPlayer>
```

**Reproduction Link:** [How to create a repro?][repro]

- https://github.com/IamManchanda/vidstack-youtube-prac
- https://github.com/IamManchanda/vidstack-youtube-prac/blob/main/src/app/page.js

[repro]: https://github.com/vidstack/player/blob/main/.github/REPRO.md

### Environment:

- Framework: React
- Meta Framework: Next.js
- Node: 20.12.2
- Device: Apple M1 Pro, MacBook Pro
- OS: MacOS 14.0
- Browser: Chrome@123

### Anything Else?

<img width="1511" alt="Screenshot 2024-04-24 at 1 22 01 AM" src="https://github.com/vidstack/player/assets/4970624/abc17441-e661-4d26-a35a-d342123b559e">

**Comment by mihar-22** [comment]
You haven't added a poster.

```tsx
<MediaPlayer>
  <MediaProvider>
    <Poster className="vds-poster" />
  </MediaProvider>
</MediaPlayer>
```

**Comment by IamManchanda** [comment]
@mihar-22 - Then it should be mentioned in the docs https://www.vidstack.io/docs/player/components/display/poster?styling=default-theme

**Comment by wplit** [comment]
> @mihar-22 - Then it should be mentioned in the docs https://www.vidstack.io/docs/player/components/display/poster?styling=default-theme

The docs you're linking to shows the poster element being added in the example code at the top.

**Comment by IamManchanda** [comment]
Sorry I think this link is where the update is needed https://www.vidstack.io/docs/player/getting-started/installation/react?provider=youtube&styling=default-layout
