### ISSUE TITLE
Thumbnails vtt file generation for Bunny CDN

### ISSUE THREAD

**Issue by piszczu4** [vidstack/player#1271]
I started to use Bunny CDN to host my video files. They produce several sprite files for a given video like below:

![image](https://github.com/vidstack/player/assets/88668060/de8459f3-0dd2-4990-8431-0cf379d7f75e)

Is it possible to somehow produce a vtt file that is compatible with vidstack player to use these thumbnails?

**Comment by Curetix** [comment]
Sure, you can link to multiple images in the VTT, something like this:

```VTT
WEBVTT

00:00:00.000 --> 00:00:30.000
yourdomain.com/yourpath/_0.jpg#xywh=0,0,284,160

00:01:00.000 --> 00:01:30.000
yourdomain.com/yourpath/_0.jpg#xywh=284,0,284,160

...

00:10:00.000 --> 00:10:30.000
yourdomain.com/yourpath/_1.jpg#xywh=0,0,284,160

...
```

If you know time interval between the sprites and their dimensions, it shouldn't be difficult to generate.

Ref: https://www.vidstack.io/docs/player/core-concepts/loading#vtt

**Comment by Curetix** [comment]
Let's do some math to figure these out.

The individual image files contain a 6x6 grid of sprites, except probably the last one, but I can't fully tell from your screenshot. So to get the total amount of sprites: `spriteCount = imageCount * 6 * 6 - (6 * 6 - spritesOnLastImage)`.

From that you can calculate the time interval between sprites using the duration of the video in seconds: `interval = Math.ceil(videoDuration / spriteCount)`. I'm rounding here since Bunny likely uses a nice round number as their interval, while our videoDuration might be off by a few (milli)seconds.

As for the sprite dimensions, take the dimensions of an image (_0.jpg for example) and divide them by six: `spriteWidth = imageWidth / 6; spriteHeight = imageHeight / 6`.

Bunny _probably_ uses the same time intervals and image/sprite dimensions for all videos, so you only to calculate these numbers once. Then you can generate a thumbnail VTT or [JSON](https://www.vidstack.io/docs/player/core-concepts/loading#json) for a video using it's duration.

**Comment by Bennycopter** [comment]
Hi there @piszczu4.  I ran into this same issue with BunnyCDN.  Here's some code to generate VTT files for Bunny's thumbnails.

All of our videos are 16:9 aspect ratio, but it sounds like you have some that are 4:3.  This is what's affecting the thumbnail sheet size to be different for you (16:9 videos have 1800x1008 thumbnail sheets; 4:3 videos have 1800x1350 thumbnail sheets).  You will need to keep track of that on your end and pass that data into this function.

There are three other properties that are required (thumbnailCount, length, guid), but you can query [Bunny's API](https://docs.bunny.net/reference/video_getvideo) for those.

```ts
const BUNNY_CDN_HOSTNAME = "....."; // whatever your CDN Hostname is from Bunny

function generateSkimThumbnailVtt(video: {
    // data from Bunny's API - https://docs.bunny.net/reference/video_getvideo
    thumbnailCount: number,
    length: number,
    guid: string,
    // data NOT from Bunny
    aspectRatio: "4:3"|"16:9",
}): string {
    const ROWS = 6;
    const COLS = 6;
    const FRAMES_PER_PAGE = ROWS * COLS;
    const FRAME_WIDTH = 300;
    const FRAME_HEIGHT = video.aspectRatio === "4:3" ? 225 : 168.75;

    const segments = ["WEBVTT"];

    const frameDuration = video.length / video.thumbnailCount;

    for (let frame = 0; frame < video.thumbnailCount; frame++) {
        const startTime = frame * frameDuration;
        const endTime = startTime + frameDuration;
        const pageNum = Math.floor(frame / FRAMES_PER_PAGE);
        const pageUrl = `https://${BUNNY_CDN_HOSTNAME}/${video.guid}/seek/_${pageNum}.jpg`;
        const frameX = frame % COLS;
        const frameY = Math.floor((frame % FRAMES_PER_PAGE) / ROWS);

        segments.push(
            // e.g.
            //00:00:07.000 --> 00:00:08.000
            //https://path/to/image.jpg#xywh=1260,0,180,101
            `${formatVttTimestamp(startTime)} --> ${formatVttTimestamp(endTime)}` + "\n" +
            `${pageUrl}#xywh=${frameX*FRAME_WIDTH},${frameY*FRAME_HEIGHT},${FRAME_WIDTH},${FRAME_HEIGHT}`
        )
    }

    return segments.join("\n\n");
}

function formatVttTimestamp(timeInSeconds: number): string {
    // I used Day.js for this function, but you can write your own if you don't use Day.js
    // INPUT = Time in seconds
    // OUTPUT = e.g. "00:12:34.567"
    const HmsPart = dayjs.duration(timeInSeconds, "seconds").format("HH:mm:ss");
    const msPart = (timeInSeconds % 1).toFixed(3).slice(1); // turns 3.14159 into ".142"
    return HmsPart + msPart;
}
```

**Comment by bruecksen** [comment]
@Bennycopter thanks for your `generateSkimThumbnailVtt ` thats exactly what I needed. Still at the beginning of switching to vidstack and wondering how do I set the thumbnails to the return of the method? Is there a way to set this programmatically after the initialization of the player?

**Comment by Bennycopter** [comment]
@bruecksen Sure thing!  I'm happy it helps.

On my site, I have an endpoint for generating thumbnail .vtt files on the fly.  The response from this endpoint is just the output from `generateSkimThumbnailVtt`.  So this is what I do:

```ts
document.querySelector("media-video-layout").thumbnails = // the URL to the endpoint, e.g. `/generated/video-thumbnails.vtt?id=${videoId}`;
```

[The Vidstack documentation](https://www.vidstack.io/docs/wc/player/core-concepts/loading?styling=default-theme#thumbnails) describes how to set it programmatically in other ways, like by generating `ThumbnailImageInit` and `ThumbnailStoryboard` objects.  I haven't tried those, though.

**Comment by bruecksen** [comment]
@Bennycopter thank you! That helps a little. But I still can't make it work not relying on a response. `ThumbnailStoryboard` seems to only work for a single image but not on multiple images? Or am I missing something here?

**Comment by Bennycopter** [comment]
Hi @bruecksen, it seems that `ThumbnailImageInit` can work with sprites (via `width`, `height`, `coords.x`, and `coords.y`).  If you use an IDE that has proper autocomplete, you can see what properties are available while writing code.

![image](https://github.com/vidstack/player/assets/50641358/1162e535-6a41-4334-a890-14fb8bf41981)

In case you don't have autocomplete, here's the type definition:
```ts
interface ThumbnailImageInit {
    url: string | URL;
    startTime: number;
    endTime?: number;
    width?: number;
    height?: number;
    coords?: ThumbnailCoords;
}
interface ThumbnailCoords {
    x: number;
    y: number;
}
```

**Comment by chrisspiegl** [comment]
I'd like to add my implementation for Bunny CDN based Sprite files (no need to generate the VTT blob).

Based on the docs, we can generate an array of images which have coordinates (see `ThumbnailImageInit` as suggested by @Bennycopter).

This makes it possible that you do not have to handle the destruction of the blob in any way (keeping things more readable along the way).

```ts
const ROWS = 6
const COLS = 6
const FRAMES_PER_PAGE = ROWS * COLS
const FRAME_WIDTH = 300

export function bunnyThumbnailJson({ thumbnailCount, length, guid, aspectRatio }: {
  thumbnailCount: number
  length: number
  guid: string
  aspectRatio: '16:9' | '4:3'
}): ThumbnailImageInit[] {
  const FRAME_HEIGHT = aspectRatio === '16:9' ? FRAME_WIDTH / (16 / 9) : FRAME_WIDTH / (4 / 5)
  const thumbnails: ThumbnailImageInit[] = []
  const frameDuration = length / thumbnailCount

  for (let frame = 0; frame <= thumbnailCount; frame++) {
    const startTime = Number((frame * frameDuration).toFixed(3))
    const endTime = startTime + frameDuration
    const pageNum = Math.floor(frame / FRAMES_PER_PAGE)
    const pageUrl = `${useRuntimeConfig().public.bunnyUrl}/${guid}/seek/_${pageNum}.jpg`
    const frameX = frame % COLS
    const frameY = Math.floor((frame % FRAMES_PER_PAGE) / ROWS)

    thumbnails.push({
      url: pageUrl,
      startTime,
      // endTime,
      width: FRAME_WIDTH,
      height: FRAME_HEIGHT,
      coords: {
        x: frameX * FRAME_WIDTH,
        y: frameY * FRAME_HEIGHT,
      },
    })
  }

  return thumbnails
}
```

## Usage with vue.js / nuxt:

In <setup> part:

```js
const thumbnailJson = computed(() => {
  const videoFile = libraryVideo.videoFile
  if (!videoFile?.length || !videoFile?.videoId) {
    return null
  }

  return videoFile.thumbnailCount
    ? bunnyThumbnailJson({
        thumbnailCount: videoFile.thumbnailCount || 150, // Default thumbnail count
        length: videoFile.length,
        guid: videoFile.videoId,
        aspectRatio: '16:9', // TODO: add aspect ratio to video file references
      })
    : null
})
```

In the template section:

```vue
<media-video-layout :thumbnails="thumbnailJson" />
```

Sidenote: This is currently prone to an error when your video file has multiple pages of seek JPG files, see https://github.com/vidstack/player/issues/1652 for reference.
