### ISSUE TITLE
An error occurs in player if used with vimeo video and private key, via query parameter.

### ISSUE THREAD

**Issue by SobeitB** [vidstack/player#1276]
### Current Behavior:

An error occurs in player if used with vimeo video and private key, via query parameter.

### Expected Behavior:

Display vimeo video without error

## Problem Solution
As I understand the error occurs because the query in the getVimeoVideoInfo function is not executed, because the hash is not passed as a query parameter, for example:
Without hash error:
https://vimeo.com/api/oembed.json?url=https://player.vimeo.com/video/903483828
With hash without error:
https://vimeo.com/api/oembed.json?url=https://player.vimeo.com/video/903483828?h=60401222e9.

In the function getVimeoVideoInfo it is necessary to pass hash and then to oembedSrc:
const oembedSrc = `https://vimeo.com/api/oembed.json?url=https://player.vimeo.com/video/${videoId}${hash ? `?h=${hash}` : ''}`;

**Comment by mihar-22** [comment]
Should be resolved by #1315 in the next release.
