### ISSUE TITLE
Problem loading base.css with webpack

### ISSUE THREAD

**Issue by acyment** [vidstack/player#1279]
### Current Behavior:

When I try to follow the docs for React-HLS-CSS I get the following error:
`Module not found: Error: Package path ./player/styles/base.css is not exported from package /app/node_modules/@vidstack/react (see exports field in /app/node_modules/@vidstack/react/package.json)
`
when importing like this:
`import '@vidstack/react/player/styles/base.css';`

I use Webpack 5

### Expected Behavior:

Successful compilation

### Steps To Reproduce:

1. Add the line import '@vidstack/react/player/styles/base.css
2. Try to run using webpack devserver

### Environment:

- Framework: React 18.3.1
- Node: 20.13.1
- Device: MacBook Pro 14 2021
- OS: MacOS 14.4.1 (code is actually running in Docker)
- Browser: N/A

**Comment by mihar-22** [comment]
I can't repro, it is included in [`exports`](https://github.com/vidstack/player/blob/main/packages/react/package.json#L91). If you can provide me a repro that I can check it out.
