### ISSUE TITLE
Player crashes in production build

### ISSUE THREAD

**Issue by booprodusan** [vidstack/player#1289]
### Current Behavior:

Whenever I try building for production with `npm run build` I experience this error: 
**Uncaught TypeError: Cannot read properties of undefined (reading 'media') at vidstack-BErtLkZy.js:295:54725**

Error in _vidstack-BErtLkZy.js:295:54725_ appears in line:
**const dn = chrome.cast.media.TrackType.TEXT**

### Expected Behavior: 

However, when I build for development with `npm run dev`, everything works as expected.

### Environment:

- Framework: Vue.js
- Node: 21.6.1
- OS: Ubuntu 22.04.4 LTS 64-bit
- Browser: Chrome@123.0.6312.105

**Comment by mihar-22** [comment]
You'll need to provide a repro to help me figure out what's going on here. What bundler are you using?

**Comment by izoukhai** [comment]
I'm having the exact same issue, did you solve it?

**Comment by booprodusan** [comment]
Yeah, changing build configuration in `vite.config.js` from 

```
build: {
        chunkSizeWarningLimit: 1500,
        rollupOptions: {
            output: {
                manualChunks(id) {
                    if (id.includes("node_modules")) {
                        return id.toString().split("node_modules/")[1].split("/")[0].toString();
                    }
                },
            },
        },
    },
```
to
```
build: {
        chunkSizeWarningLimit: 3500,
},
```

solved it.
