### ISSUE TITLE
Safari report NotAllowedError

### ISSUE THREAD

**Issue by cylinera** [vidstack/player#1293]
### Current Behavior:
When I use the play loading strategy, if the user opens the webpage with Safari browser and immediately clicks the play button, the playback will fail. The console will print "play request failed" and carry this error message.

**NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.**

### Expected Behavior:
Video plays as normal when user clicks the play button

### Environment:
- Framework: React
- Meta Framework: Next.js
- Node: v20.12.0
- Device: Apple M2 Pro
- OS: macOS Ventura
- Browser: Safari 16.6 (18615.3.12.11.2)

<img width="1315" alt="image" src="https://github.com/vidstack/player/assets/156406343/d36e4de7-8675-49b8-9d5a-d804cf5a61bb">

**Comment by rolandszoke-byborg** [comment]
Are you using autoplay? If so this issue is already reported here: https://github.com/vidstack/player/issues/1282#issue-2293779200
You need to turn off autoplay in Safari/iOS until it is fixed.

**Comment by mihar-22** [comment]
I'm not able to repro this error. It might've been fixed by another patch, try the next release when it comes out and let me know if it persists.
