### ISSUE TITLE
Bug with thumbnail.vtt and sprite png

### ISSUE THREAD

**Issue by nvtienlg** [vidstack/player#1295]
WEBVTT

00:00:00.000 --> 00:01:02.000
thumbnail.png#xywh=0,0,160,90

00:01:02.000 --> 00:01:34.000
thumbnail.png#xywh=160,0,160,90

00:01:34.000 --> 00:02:06.000
thumbnail.png#xywh=320,0,160,90

...

with url https://demo.com/path/thumbnail.vtt
player loads https://demo.com/thumbnail.png [Wrong]
instead of https://demo.com/path/thumbnail.png [Correct]

it works fine with jpg extension image

Tested with latest version via CDN, here is live demo for you
https://vip.upns.net/Jq_8rFweJJMhVoTC2ok0oQ/6s/d/qr/dqr15k/thumbnail.vtt
test it here: https://www.vidstack.io/player/demo?framework=react&view=player

Thank you

**Comment by mihar-22** [comment]
I can't repro this, the test link has expired. If you can provide a new link then I can reopen and test this issue, thanks!

**Comment by nvtienlg** [comment]
Hello,

Sorry forgot to update this. I found the root cause. It is not about file extensions, but url format
Let say my player page is at https://demo.com/player, thumbnail is at https://demo.com/{videoId}/thumbnail.vtt (same host with player).

So both settings bellow should work:
layout: new VidstackPlayerLayout({ thumbnails: 'https://demo.com/{videoId}/thumbnail.vtt' }),
layout: new VidstackPlayerLayout({ thumbnails: '/{videoId}/thumbnail.vtt' }),

But only first one is working
