### ISSUE TITLE
Poster not working with next/image

### ISSUE THREAD

**Issue by empz** [vidstack/player#1298]
### Current Behavior:

Poster doesn't show when using Next.js Image component as shown in the documentation page: https://www.vidstack.io/docs/player/components/display/poster?styling=tailwind-css#nextjs

### Repro 
https://stackblitz.com/edit/stackblitz-starters-xmrkb4?file=app%2Fplayer.tsx

**Comment by mehrabmp** [comment]
Any update?

**Comment by ranyu696** [comment]
Please fix it
