### ISSUE TITLE
webm file format is recognized as live video

### ISSUE THREAD

**Issue by ming535** [vidstack/player#1299]
### Current Behavior:

Wen I was using a `webm` file, the MediaPlayer by default uses "Live Stream" mode. Setting the value of "streamType" doesn't change the behavior.

### Expected Behavior:

1. `webm` url should not be considered as a "Live Stream";
2. Setting the "streamType" for `webm` file to "on-demand" should disable the "Live Stream" mode?

### Steps To Reproduce:
I made a webm video below to show the issue.

MediaPlayer without `streamType` defaults to "Live Stream"

```javascript
    <MediaPlayer src="https://yarx.s3.amazonaws.com/yR1eIHNkzlK2bkzrMhyk4.webm">
      <MediaProvider />
      <DefaultVideoLayout icons={defaultLayoutIcons} />
    </MediaPlayer>
```
MediaPlayer with `streamType` set to `on-demand` also makes the player to be "Live Stream"

```javascript
    <MediaPlayer src="https://yarx.s3.amazonaws.com/yR1eIHNkzlK2bkzrMhyk4.webm" streamType="on-demand">
      <MediaProvider />
      <DefaultVideoLayout icons={defaultLayoutIcons} />
    </MediaPlayer>
```

### Anything Else?

<img width="1012" alt="Screenshot 2024-06-05 at 23 18 00" src="https://github.com/vidstack/player/assets/7576663/cdc1ee57-2184-4bc3-ab17-944274eabb44">

We can see the left bottom corner, there is a "Live" indicator. Is this the expected behavior?

**Comment by ming535** [comment]
The issue was resolved by adding a `duration` to `MediaPlayer`.
Is this the expected behavior?

**Comment by mihar-22** [comment]
It's not but it would be an issue with video file itself, possibly how it was encoded. Closing as this is not an issue with the player itself, thanks!
