### ISSUE TITLE
semicolon in the dom

### ISSUE THREAD

**Issue by OmarTaheri** [vidstack/player#1300]
![image](https://github.com/vidstack/player/assets/86674378/37d09009-372c-4221-8b1c-45e24210cb2c) This should not be here, also the nextjs poster image dosnt work

**Comment by mihar-22** [comment]
The semicolon does not exist on latest from what I can see, make sure you're on the latest version. It might also be in your own code so check for that too. The poster image not working in Next.js is being looked into separately.

**Comment by OmarTaheri** [comment]
[heart]         Omar Taheri < 145981 > reacted to your message:
________________________________
