### ISSUE TITLE
play two subtitles at once

### ISSUE THREAD

**Issue by astronautfa** [vidstack/player#1305]
I want to be able to show two subtitles in different languages at once. From what I understand the source code is written in a way that only one subtitle is supported at all times. 

It would be great if we could play two subtitles simultaneously without changing the source code.

**Comment by mihar-22** [comment]
Unfortunately, this will require significant internal changes that is out of scope for us right now. As a workaround, I recommend merging the the two subtitle files into one.

**Comment by astronautfa** [comment]
thanks 

Could you guide me what steps I should take to make playing two separate subtitles playable at once? 

I really want to explore this feature and just a high level guidance could help me
