### ISSUE TITLE
Multiple `ThumbnailStoryboard` 

### ISSUE THREAD

**Issue by bruecksen** [vidstack/player#1310]
### Related Problem:

I can't programmatically set the thumbnails if I have multiple sprite images. This only works if I have an endpoint returning a vtt file. But I would like to be able to programmatically add thumbnails based on multiple sprite files.

### Describe:

It should be allowed to set thumbnails to an array of `ThumbnailStoryboard` objects. So that every `ThumbnailStoryboard` object could point to a different sprite image.

**Comment by Curetix** [comment]
You can use the JSON format as shown in the [docs](https://www.vidstack.io/docs/player/core-concepts/loading#json):

```ts
[
  { "startTime": 0, "endTime": 5, "url": "/media/thumbnail-1.jpg" },
  { "startTime": 5, "endTime": 10, "url": "/media/thumbnail-2.jpg" }
]
```

Or with coordinates like a VTT:

```ts
[
  { "startTime": 0, "endTime": 5, "url": "/media/thumbnail-1.jpg#xywh=0,0,284,160" },
  { "startTime": 5, "endTime": 10, "url": "/media/thumbnail-1.jpgxywh=284,0,284,160" }
  // ...
  { "startTime": 100, "endTime": 105, "url": "/media/thumbnail-2.jpgxywh=0,0,284,160" }
]
```

**Comment by bruecksen** [comment]
@Curetix thank you!

**Comment by chrisspiegl** [comment]
Through researching a bunch in this repository, the docs, and other issues… I found a solution where the JSON file setup is more clear and human readable by using `ThumbnailImageInit` as defined in 

https://github.com/vidstack/player/blob/3d18eeac5a9087112f72fc19f6e72f782384af7a/packages/vidstack/src/components/ui/thumbnails/thumbnail-loader.ts#L308-L324

This is a bit more clean than the solution with the coordinates based on the `#xywh=0,0,284,160` format in the URL part.

**The code example I am using is provided here:** https://github.com/vidstack/player/issues/1271#issuecomment-2973317536
