### ISSUE TITLE
Nuxt3 SSR Hydration mismatch

### ISSUE THREAD

**Issue by azuryel** [vidstack/player#1312]
### Current Behavior:

 When i follow the doc for a Nuxt3 installation and copy paste the media-player into my component i got an SSR mismatch error, also the video are displaying while loading ( SSR ) but as soon as i got the Hydration mismatch ( after component mounted) the video are not available to play or not displaying

### Expected Behavior:

No SSR mismatch -- poster show during load --> video display after can play == true

### Steps To Reproduce:

Fresh nuxt3 install, fresh vidstack install , following the doc 

**Reproduction Link:** [How to create a repro?][repro]

[repro]: https://github.com/vidstack/player/blob/main/.github/REPRO.md

**Comment by mihar-22** [comment]
Everything is working as expected in my testing. The hydration warning is annoying but I can't fix that at the moment. You can remove the warning by adding the following:

```html
<media-player v-warning="false">
```

**Comment by mihar-22** [comment]
Everything is working as expected in my testing but the hydration warnings are annoying. We can't fix this at the moment but we might create official Vue wrapper for our library that should resolve this. Looking into it for 1.0. 

ℹ️  For now you can consider rendering the player client-side only using the `<ClientOnly>` Nuxt component.

**Comment by mihar-22** [comment]
Bind to props and make sure internals are wrapped with `ClientOnly`. Reference for anyone in the future to avoid this issue:

```vue
<script setup>
import "vidstack/bundle";

const title = ref("Sprite Fight"),
  src = ref("https://files.vidstack.io/sprite-fight/720p.mp4");
</script>

<template>
  <media-player .title="title" .src="src">
    <ClientOnly>
      <media-provider>
        <media-poster
          class="vds-poster"
          src="https://files.vidstack.io/sprite-fight/poster.webp"
        ></media-poster>
      </media-provider>
      <media-video-layout
        thumbnails="https://files.vidstack.io/sprite-fight/thumbnails.vtt"
      ></media-video-layout>
    </ClientOnly>
  </media-player>
</template>
```
