### ISSUE TITLE
DRM Support

### ISSUE THREAD

**Issue by rohankm** [vidstack/player#1317]
Hi,
I have been checking out the docs i dont find support for drm. can someone please help?

**Comment by mihar-22** [comment]
We haven't streamlined DRM and we don't have guides just yet. It's managed by `hls.js` (the provider we use to stream HLS). See the [hls.js API](https://github.com/video-dev/hls.js/blob/master/docs/API.md#drmsystems).  

Also check out [configuring hls.js](https://www.vidstack.io/docs/player/api/providers/hls?styling=default-theme#configuring) in our docs.

**Comment by rohankm** [comment]
> We haven't streamlined DRM and we don't have guides just yet. It's managed by `hls.js` (the provider we use to stream HLS). See the [hls.js API](https://github.com/video-dev/hls.js/blob/master/docs/API.md#drmsystems).
> 
> Also check out [configuring hls.js](https://www.vidstack.io/docs/player/api/providers/hls?styling=default-theme#configuring) in our docs.

Hi is there any way to integrate shaka player with Vidstack instead of hls or dash?

**Comment by mihar-22** [comment]
Nope. Check the docs for all providers.
