### ISSUE TITLE
Can't start video with YouTube provider when autoplay request fails

### ISSUE THREAD

**Issue by DerStimmler** [vidstack/player#1325]
### Current Behavior:

When I enable `autoPlay`, use the HLS provider and reload a page with a video on it, the autoplay request fails as expected because of the browsers autoplay policy. Also corresponding events are triggered and errors are written to the console.
![image](https://github.com/vidstack/player/assets/43130816/971b68b9-0af7-41b9-8c59-241bd76ffff4)
But it's still possible to click on the play button to start the video manually.

However when I use the YouTube provider, again the autoplay request fails but no events are triggered nor something is written to console. Also the player stays in the loading state and I can't click the play button to start the video manually.

### Expected Behavior:

YouTube provider should have same behavior like HLS provider when autoplay fails. It should still be possible to start the video manually.

### Steps To Reproduce:

1. Enable autoplay
2. Set a YouTube video as player source
3. Reload the page

### Environment:

- Framework: Angular v18
- Node: 20
- Device: PC
- OS: Windows
- Browser: Chrome@126
- vidstack: 1.11.24

**Comment by DerStimmler** [comment]
maybe related to #1316

**Comment by zcesur** [comment]
I'm having the same issue with the latest vidstack version (1.12.9)

![](https://github.com/user-attachments/assets/5ee283ff-f375-4f0a-b27b-fb4a40bb982b)

- Framework: JavaScript & Web Components
- Node: 20.10.0
- Device: PC
- OS: Ubuntu 24.04
- Browser: Chrome 127
