### ISSUE TITLE
Tailwind utilities conflict with default layout

### ISSUE THREAD

**Issue by kevinschweikert** [vidstack/player#1326]
I am using a fresh Elixir Phoenix project with a default Tailwind and Esbuild setup. Esbuild and Tailwind are running as standalone binaries. 
The styles get correctly imported, but there seems to be an issue/conflict with the tailwind utilities.

### Current Behavior:

![image](https://github.com/vidstack/player/assets/54439512/130d8181-35b7-407b-8a39-bd6b9210448c)

### Expected Behavior:

![image](https://github.com/vidstack/player/assets/54439512/b87335a7-2382-4e98-839b-425d945dd983)

### Steps To Reproduce:

1. Import Default Layout styles in `app.js` like in https://www.vidstack.io/docs/player/getting-started/installation/javascript?provider=hls&styling=default-layout&install=npm
2. To get the correct styles, remove `@tailwind utilities;` in `app.css`

### Environment:

- Framework: Phoenix / JavaScript
- Meta Framework: esbuild
- Node: v22.3.0
- Device: MacBook
- OS: macOS 14.5 (23F79)
- Browser: Arc Version 1.49.0 (51346)

**Comment by mihar-22** [comment]
Thanks for reporting! I don't understand, what is the conflict exactly?

**Comment by mihar-22** [comment]
The first image is the small layout (mobile) and the second is the large layout (desktop). See [Default Video Layout > Sizing](https://www.vidstack.io/docs/wc/player/components/layouts/default-layout?styling=default-theme#size) for how you can configure it. If I misunderstood then I'm happy to reopen.
