### ISSUE TITLE
Error causing builds to fail in Cloudflare Pages local preview

### ISSUE THREAD

**Issue by ramiroazar** [vidstack/player#1329]
### Current Behavior:

Vidstack React causing `wrangler pages dev` to fail in Cloudflare Pages project using Remix template.

### Expected Behavior:

Running `wrangler pages dev` should start a local server successfully.

### Steps To Reproduce:

1. [Set up a new project](https://developers.cloudflare.com/pages/framework-guides/deploy-a-remix-site/#setting-up-a-new-project)
2. [Install Vidstack React](https://www.vidstack.io/docs/player/getting-started/installation/react?provider=hls&styling=default-layout)
3. Run preview (ie. `npm run preview` or `npm run build && wrangler pages dev`)

### Environment:

- Vidstack: @vidstack/react@1.11.24
- Framework: React
- Meta Framework: Remix
- Node: 22.2.0
- Device: iMac@2020
- OS: macOS@14.5
- Browser: Chrome@126.0.6478.127

### Anything Else?

This seems related to https://github.com/vidstack/player/pull/1198 as the errors look virtually identical, though in this case it's related to `@vidstack/react` instead of `vidstack`.

<img width="815" alt="Screenshot 2024-07-01 at 3 57 39 PM" src="https://github.com/vidstack/player/assets/3581503/ee24b76d-4161-4031-883c-47c905747873">

This is working when running the Remix local server instead using `npm run dev` or `remix vite:dev`.

It's also working when the project is built in Cloudflare Pages using `npm run build` or `remix vite:build`.

The `vidstack` package using [Web Components](https://www.vidstack.io/docs/player/getting-started/installation/web-components?bundler=none&provider=hls&styling=default-layout) also works as expected.

**Comment by Wekananda** [comment]
Its happening to me when deploying or using cloudflare wrangler in version v1.12.13-next using nextjs framework with tailwind
