### ISSUE TITLE
unexpected token { in iOS<17

### ISSUE THREAD

**Issue by kevin-appelt** [vidstack/player#1333]
### Current Behavior:

When using vidstack on iOS < 17, we receive an `unexpected token {`

### Expected Behavior:

Vidstack should work also in iOS < 17

### Steps To Reproduce:

We use `import {VidstackPlayer, VidstackPlayerLayout} from 'vidstack/global/player';`

There was a fix for the react version: https://github.com/vidstack/player/commit/5720ce369b868bdaf5ebbcd718b5e26e4069fa25
But I guess it's not fixed in other versions.

### Environment:

- Framework: JavaScript
- Device: iPhone@12mini
- OS: iOS@16
- Browser: Safari@16

Device and Browser does not really matter as long as its iOS < 17

**Comment by mihar-22** [comment]
This is not an issue on our end, it needs to be handled by your bundler. We ship the latest syntax for our NPM version to allow for everyone to bundle and polyfill accordingly for their app and users. The Next.js fix was because the bundler itself wasn’t doing what it should.

**Comment by ljs19923** [comment]
@mihar-22 what's the solution with NextJs? I have the same problem with Safari < 17
