### ISSUE TITLE
CDN down? Source map error 404 when loading player

### ISSUE THREAD

**Issue by DaforLynx** [vidstack/player#1335]
New to this vidstack stuff. I'm using the pure CSS version for audio and found the media player to not appear at all. Inspecting its element gave a warning:
```
Source map error: Error: request failed with status 404
Resource URL: https://cdn.vidstack.io/player/theme.css
Source map URL: /sm/51d48ccd6b...
```
Seems like something similar happened a few months ago as reported here #1232 .

**Comment by mihar-22** [comment]
Source maps don't work at the moment, not important though. If you can't get it to work then join our Discord and share your code and what you've tried so we can help.
