### ISSUE TITLE
Incorrect timestamp intervals in Safari.

### ISSUE THREAD

**Issue by vorillaz** [vidstack/player#1336]
### Current Behavior:

I am on Safari (Version 17.0 - Webkit 19616.1.27.211.1 / MacOS 14.0 Sonoma (23A344)) and the player upon playing seems to periodically glitch, take a step back on time.

### Expected Behavior:
When start playing, the interval timestamps should be progressing in time.

### Steps To Reproduce:

I've created a minimal reproduction example with a sample video
Codesandbox: https://codesandbox.io/p/sandbox/vidstack-src-switch-desktop-to-mobile-forked-tx2jrz
Demo: https://tx2jrz.csb.app/

Open up the demo in Safari and try to seek backwards or forward, there is a tiny glitch in the time slider and an error is logged.

### Environment:

Example:
- Framework: React
- Node: 16.0.0
- Device: Mac
- OS: MacOS 14.0 Sonoma
- Browser: Safari

### Anything Else?
There are two bugs reported in the Webkit project that might be related:

https://github.com/WebKit/WebKit/commit/a5d771514da3dec2c3944c4e5aefa7d9c6c1b18e
https://bugs.webkit.org/show_bug.cgi?id=235087

**Comment by mihar-22** [comment]
Thanks for reporting! Sadly can't properly repro the issue, the sandbox is not working. I haven't found it with other media so it's most likely an issue specific to the packaging or encoding of the tested files on Safari (not something in our player that we can resolve). If you can provide me a generalized repro I'm happy to try again and reopen the issue. Thanks!

**Comment by vorillaz** [comment]
Hey @mihar-22 
That was my bad.
You can retry with the live demo here https://tx2jrz.csb.app

Full code can be found here, https://codesandbox.io/p/sandbox/vidstack-src-switch-desktop-to-mobile-forked-tx2jrz

The bug is reproducible with any version of Safari, just seek back and forth and the timeline jitters back in time.
