### ISSUE TITLE
Remotion better licensed alternative 

### ISSUE THREAD

**Issue by no-1ne** [vidstack/player#1337]
Currently remotion seems to be available as a provider and its licensing is not very friendly..Would you consider https://github.com/redotvideo/revideo an MIT licensed library

**Comment by mihar-22** [comment]
We won't be adding new providers for the mean time. How is the Remotion license not fair?

**You are eligible to use Remotion for free if you are:**

- an individual
- a for-profit organization with up to 3 employees
- a non-profit or not-for-profit organization
- evaluating whether Remotion is a good fit, and are not yet using it in a commercial way

Seems super fair.
