### ISSUE TITLE
Warning: `Added non-passive event listener to a scroll-blocking <some> event`

### ISSUE THREAD

**Issue by Curetix** [vidstack/player#1338]
### Current Behavior:

Using the (React) Vidstack player causes these warnings to be logged to the console:

`[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

![image](https://github.com/vidstack/player/assets/15160542/e3dc4c5b-00d1-48dd-a9f5-85a8923fb31d)

### Expected Behavior:

The warning isn't logged.

### Steps To Reproduce:

**Reproduction Link:** [How to create a repro?][repro]

[repro]: https://stackblitz.com/edit/vidstack-examples-zrewr9

### Environment:

- Framework: React
- Meta Framework: Next.js
- Node: 20
- Device: PC
- OS: Windows 11 
- Browser: Brave 1.67

**Comment by mihar-22** [comment]
Are you sure it's related to the player? I can't repro in Brave. If you can provide a repro or some instructions on what triggers the warning then I'm happy to reopen :)

**Comment by Curetix** [comment]
Yup, should be related to the player. Though the warning is only logged when the devtools are already open before the player loads. This is with the latest version of Chrome, no extensions installed:


https://github.com/vidstack/player/assets/15160542/f9cd7103-dceb-4825-ab04-f3640a9252a0

**Comment by mihar-22** [comment]
Strange, can't repro no matter what I do. Hm. If you can trace down the line that's causing it then I can see what's up. The line shown in the video is when the event listener is added but the issue would be a call above in the stack trace. Otherwise, not entirely sure what's happening here.

**Comment by Curetix** [comment]
Weird that you're not getting the warning, maybe it's OS related? I traced it, and it seems to be the `touchstart` listener from `ToggleButton`. 

https://github.com/vidstack/player/assets/15160542/2eff7e42-bcf9-4db9-b0f2-e7bc5978b6d2
