### ISSUE TITLE
Doesn't build basic vanilla js example with parcel2

### ISSUE THREAD

**Issue by selim13** [vidstack/player#1341]
### Current Behavior:

[parcel2](https://parceljs.org/) is failing to build a [basic vanilla js example from documentation](https://www.vidstack.io/docs/player/getting-started/installation/javascript?provider=video&styling=default-layout&install=npm).

```
> parcel build index.js

🚨 Build failed.

@parcel/core: Failed to resolve 'vidstack/global/player' from './index.js'

  /home/selim13/www/test/vidstack-test/index.js:1:54
  > 1 | import { VidstackPlayer, VidstackPlayerLayout } from 'vidstack/global/player';
  >   |                                                      ^^^^^^^^^^^^^^^^^^^^^^^^
    2 | 
    3 | const player = await VidstackPlayer.create({

@parcel/resolver-default: Cannot load file './global/player' from module 'vidstack'
```

### Expected Behavior:

The basic vanilla js example should work.

### Steps To Reproduce:

Copy [basic vanilla js example from documentation](https://www.vidstack.io/docs/player/getting-started/installation/javascript?provider=video&styling=default-layout&install=npm) to index.js, then:
```
npm init -y
npm i -D parcel
npm i vidstack@next 
npx parcel build index.js
```

Or use reproduction example: 
https://github.com/selim13/vidstack-parcel2-bug-repro
```
npm i
npm run build
```

### Environment:

- Ubuntu 20.04
- node v20.15.1
- npm 10.7.0

package.json
```json
{
  "name": "vidstack-test",
  "version": "1.0.0",
  "scripts": {
    "build": "parcel build index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "devDependencies": {
    "parcel": "^2.12.0"
  },
  "dependencies": {
    "vidstack": "^1.11.25"
  }
}
```

index.js
```js
import { VidstackPlayer, VidstackPlayerLayout } from 'vidstack/global/player';

VidstackPlayer.create({
  target: '#target',
  title: 'Sprite Fight',
  src: 'youtube/_cMxraX_5RE',
  poster: 'https://files.vidstack.io/sprite-fight/poster.webp',
  layout: new VidstackPlayerLayout({
    thumbnails: 'https://files.vidstack.io/sprite-fight/thumbnails.vtt',
  }),
});
```

**Comment by mihar-22** [comment]
You'll need to [enable package exports](https://parceljs.org/features/dependency-resolution/#package-exports) for it work. Simply add the following to your `package.json`:

```json
{
  "@parcel/resolver-default": {
    "packageExports": true
  }
}
```
