### ISSUE TITLE
Current time is incorrect at end of clipped video

### ISSUE THREAD

**Issue by vorillaz** [vidstack/player#1342]
### Current Behavior:

Through the new remote API (thanks btw) #1330 you can setup the clip end and clip start timestamps of the video. Upon playing and stopping the timeline resets to the original duration.

### Expected Behavior:

Upon changing the clipping timestamps the progress should stay consistent.

### Steps To Reproduce:

1. Visit https://codesandbox.io/p/sandbox/vidstack-src-switch-desktop-to-mobile-forked-tx2jrz?file=%2Fsrc%2Fplayer.tsx%3A145%2C5-145%2C31 or https://tx2jrz.csb.app/
2. Click the "Set start to 2 and end to 5" button.
3. Play the video
4. Upon stopping the thumb of the timeline gets reset to the previous duration (~10s)

**Reproduction Link:** 
https://tx2jrz.csb.app/

### Environment:
- Framework: React

**Comment by mihar-22** [comment]
I'm not able to repro the issue or maybe I don't understand. I pressed "set start to 2 and end to 5", the duration is correctly 3 seconds, playing and pausing doesn't cause any reset.

**Comment by vorillaz** [comment]
Hi @mihar-22 , here's how to reproduce:
1) Start player.
2) Press the `set start to 2 and end to 5` button.
3) Wait for the clip to finish, once done observe the progress thumb stuck in the middle of the video.
