### ISSUE TITLE
Vite plugin produces type errors

### ISSUE THREAD

**Issue by genu** [vidstack/player#1343]
### Current Behavior:
Enabling the vite plugin in a nuxt setup produces this type error:

![CleanShot 2024-07-09 at 18 30 29@2x](https://github.com/vidstack/player/assets/928780/70e2b697-dc96-4acd-98ea-042acaa49d66)

### Error:
```bash
Type 'Plugin<any> | Plugin<any>[]' is not assignable to type 'PluginOption'.
```

### Workaround

I'm able to make the type error go away if I do:
```ts
plugins: [vidstack({ include: /player\// }) as unknown as PluginOption],
```

**Comment by mihar-22** [comment]
I just tested this in Nuxt and I can't reproduce the issue. It's likely you're ending up with a different version of Vite being resolved for `vidstack` and a different version for Nuxt in `defineNuxtConfig`. A repro is required for me to dig further and reopen the issue if necessary.

**Comment by koszzz** [comment]
I also encountered this problem.
I used`"nuxt": "^4.3.1",
        "vidstack": "^1.12.13",
        "vue": "^3.5.28"`
