### ISSUE TITLE
Cannot replay audio files < 1 second

### ISSUE THREAD

**Issue by insertmike** [vidstack/player#1347]
### Current Behavior:

After completion of playing an audio asset which has duration < 1 seconds, currentTime hangs forever, making it impossible to replay.

### Expected Behavior:

Appropriate handling of short audio events and ability to replay.

### Steps To Reproduce:

`Environment:` Latest
`Config:` Audio/Default
`Run:` Use audio assets < 1 seconds and plug it in default examples.

**Reproduction Link:** [How to create a repro?][repro]

[repro]: https://github.com/vidstack/player/blob/main/.github/REPRO.md

### Environment:
- Latest prod

**Comment by insertmike** [comment]
Note, this is high priority bug, as there is no easy workaround.

**Comment by insertmike** [comment]
@mihar-22 can we have a look at this? If it's a quick fix, it's definitely worth it!

**Comment by mihar-22** [comment]
This is working in my brief testing, you'll need to provide a reproduction as you skipped over it in the issue report. Closing until provided, thanks!
