### ISSUE TITLE
VLC.js integration

### ISSUE THREAD

**Issue by hobodrifterdavid** [vidstack/player#1350]
Hello. I wonder if you might be able to comment on the feasability of using VLC.js as as a video playing backend with a vidstack UI controls.

A couple of links:
https://nivethan.dev/devlog/running-vlc-in-the-browser.html
https://videolabs.io/communication/vlcjs-demo/vlc.html

Here's an earlier attempt I found to integrate into videojs:

https://github.com/Afterster/videojs-vlc/blob/master/lib/videojs-vlc.js

If you think it's a reasonable thing to do, perhaps you could give any thoughts about possible issues and offer an outline for how to approach the job, I can give it a shot.

Thanks

**Comment by mihar-22** [comment]
The VLC.js library uses WASM and renders to a canvas with it's own state tracking and events. This would require a new provider implementation in our library. It's possible but unfortunately we don't intend on adding any more providers at this time. It's quite time consuming. 

You're free to try and create a PR for it by seeing the Architecture docs on our site and then looking at similar implementations for our other providers. We don't have a public plugin system like Video.js at the moment so I can't offer much else.
