### ISSUE TITLE
Errors when adding multiple text tracks

### ISSUE THREAD

**Issue by stsrki** [vidstack/player#1355]
I'm trying to convert my existing video component, which uses Plyr, into this new library. I have followed the documentation and was able to do everything so far, but now I'm stuck on text tracks.

**My code**

```js
if (options.source.tracks && options.source.tracks.length > 0) {
    plyr.player.textTracks.clear();

    for (const track of options.source.tracks) {
        plyr.player.textTracks.add(track);
    }
}
```

**Errors in the console**

![image](https://github.com/user-attachments/assets/b07b749a-f537-4f0c-9f2f-07708008297e)

---

The video still can play, but there is another issue. All tracks are selected, even though I have defined one of the tracks with `default=true`.

![image](https://github.com/user-attachments/assets/eb613127-a9da-471b-a5ea-5c2af0c60071)

**Comment by mihar-22** [comment]
Thanks for reporting! A [reproduction](https://github.com/vidstack/player/blob/main/.github/REPRO.md) is required for me to debug this issue. I'll reopen when a valid one is provided.
