### ISSUE TITLE
Legacy CDN files contain previous version chunks

### ISSUE THREAD

**Issue by AgentSmith0** [vidstack/player#1357]
### Current Behavior:

In the cdn files there is a problem with references to other cdn scripts.
Take a look at v1.11.30: https://cdn.jsdelivr.net/npm/vidstack@1.11.30/cdn/with-layouts/vidstack.js
Why are there references to files from the last version (v1.11.29)?!?

### Expected Behavior:

The files work correctly...

### Steps To Reproduce:

Just see the example file on jsdelivr.

**Comment by mihar-22** [comment]
I'll get that fixed but they're old anyway, we've moved to https://cdn.jsdelivr.net/npm/@vidstack/cdn
