### ISSUE TITLE
Extra Space With playsInline on iOS

### ISSUE THREAD

**Issue by shmaltz** [vidstack/player#1366]
I added a media player to my site with `playsInline` and on android Firefox it displays properly but on iOS Safari it displays with extra padding/margin underneath the player. I am not sure if it's padding or margin as I can't check on mobile.

**![vidstack-padding](https://github.com/user-attachments/assets/3e7c3f7a-66ff-4076-bf72-d96f34c0fa71)**

**Expected Behavior:**
I expect the video player to be displayed properly.

**Steps To Reproduce:**
```
<media-player load="eager" title="<?php echo $title; ?>" src="youtube/<?php echo $youtube_id; ?>" playsInline="true" crossOrigin="true">
  <media-provider>
    <media-poster
      class="vds-poster"
      src="<?php echo $thumbnail; ?>"
    ></media-poster>
  </media-provider>
  <media-video-layout thumbnails="<?php echo $thumbnail; ?>"></media-video-layout>
</media-player>
```

**Environment:**
Version: 1.11.30
Framework: Web Components
PHP/JS
Device: iPhone XR
OS: iOS 15.4.1
Browser: Safari

**Comment by mihar-22** [comment]
This seems specific to your app and styles, need a [repro](https://github.com/vidstack/player/blob/main/.github/REPRO.md) to provide any guidance.

**Comment by skerbis** [comment]
This happens because of 

iframe.vds-youtube[data-no-controls] {
  height: 1000%; 
}

in all Safari Versions mobile and Desktop @shmaltz set it to 100%, it will be fixed
