### ISSUE TITLE
Youtube thumbnail issue

### ISSUE THREAD

**Issue by lihsaa591** [vidstack/player#1373]
### Current Behavior:

![image](https://github.com/user-attachments/assets/ebd4c51d-d0e3-464c-beb3-d0f4ca0a31bf)

### Expected Behavior:

![image](https://github.com/user-attachments/assets/97ee8532-206e-4078-8b5a-5f84e57be679)

### Steps To Reproduce:

**Reproduction Link:** [How to create a repro?][repro]

[repro]: https://github.com/vidstack/player/blob/main/.github/REPRO.md

### Anything Else?

Is this intended?

![image](https://github.com/user-attachments/assets/4dd34ea8-1a6a-4cc9-82b7-43c40fc1f6fc)

**Comment by mihar-22** [comment]
Add a poster:

```tsx
import { MediaPlayer, MediaProvider, Poster } from '@vidstack/react';

<MediaPlayer>
  <MediaProvider>
    <Poster className="vds-poster" />
  </MediaProvider>
</MediaPlayer>
```
