### ISSUE TITLE
Media Menu Items in settings menu no longer display (v1.12.6) 

### ISSUE THREAD

**Issue by wplit** [vidstack/player#1389]
Since 1.12.6 the 'media-menu-items' in the menu component no longer displays when the media menu button is clicked (display:none is no longer removed on the media-menu-items component)

So when clicking playback, accessibility, etc in the settings menu we don't see the menu items to be control the settings.

(using web components)

**Comment by taran2k** [comment]
Was just about to open an issue on this. Some additional info:

The issue appears at any time when trying to access the submenu (i.e. the menu you get when once clicking on 'Accessibility', 'Playback' or 'Audio').

[Recording](https://github.com/user-attachments/assets/4dda754f-b1e5-4c2a-aeb1-d037dfe46c24)

The behaviour we expect is for the submenu to be toggled to visible when its button is pressed:
![Sreenshot](https://github.com/user-attachments/assets/500d71dd-0606-4eb7-bbe6-9bd183470e62)

This should happen automatically, but now can only be corrected manually by removing the `display: none;` style attribute:
![Schermafdruk van 2024-08-12 12-34-09](https://github.com/user-attachments/assets/23af6cca-0cba-4feb-a0fc-77cd766bf0ea)

**Comment by taran2k** [comment]
Seems to me [5fd9db2](https://github.com/vidstack/player/commit/5fd9db2070ad3d779429c53511e45f497154aa3d) is causing the issue, specifically these lines:

```
 66 +  const { expanded } = this.#menu;
 67 +  if (!this.el || !expanded()) return;
```
