### ISSUE TITLE
Video qualities unavailable for YouTube provider

### ISSUE THREAD

**Issue by apudiu** [vidstack/player#1391]
### Current Behavior:

Whatever YT video I play with the player, it is always blurry. After inspecting, I found that `player.qualities` has no quality available! I tried to trigger the `auto` quality option `player.remoteControl.requestAutoQuality()` but that didn't help, Maybe because the player has no quality options in the first place.

How to load qualities for YouTube videos?

### Expected Behavior:

I've used `Plyr` before. My expectation was that this should've qualities available automatically. Or a way to load YT video qualities (in the docs).

### Steps To Reproduce:

1. Use YouTube provider
2. Check `player(instance).qualities`
3. Try to trigger `auto` quality & that does nothing

I wanted to trigger `auto` quality when the user goes fullscreen so a better quality can be played automatically.

**Reproduction Link:** I believe that this issue doesn't require a repo

### Environment:

- Meta Framework: Next.js 14.2
- Node: 20
- Device: PC
- OS: Ubuntu@24.04
- Browser: Chrome@127
- @vidstack/react: ^1.11.29

Edit: Important context, initially player initializes at a small size (it's around 640px in width), So the quality is being set is okay for that size, The issue is, I've no option to change to a better quality even though the video has lots quality available in YT. Due to this when the user switches to fullscreen video stays blurry.

**Comment by mihar-22** [comment]
You cannot control the quality level of the YouTube embed, there is no API to do so. It is auto by default.

**Comment by apudiu** [comment]
Thanks @mihar-22, The issue is auto quality is not working for me. When the video loads in a small size it never switches to a better resolution when the player is in full-screen mode.

**Comment by empz** [comment]
Uhm, I'm experiencing the same issue here. Using native embed works well, using Vidstack Player does not. So it's not a limitation of the YouTube embed...
