### ISSUE TITLE
Dash videos skip to end

### ISSUE THREAD

**Issue by snipcola** [vidstack/player#1396]
I created a demonstration using `@vidstack/react@1.12.9`.
When using a dash source, the video timestamp is sometimes set to the end.

I have uploaded the demo to Vercel: https://vidstack-dash-bug.vercel.app
I have also attached a video which demonstrates the issue.

https://github.com/user-attachments/assets/47d61b63-5b02-474d-84a2-eaf57b82a839

**Comment by mihar-22** [comment]
This is most likely becuase the stream is not being detected as VOD and rather live. For VOD content, the playlist needs the type set to "static" or you need to provide the stream type to the player like so:

```tsx
<MediaPlayer streamType="on-demand">
```

Link: https://www.vidstack.io/docs/player/core-concepts/loading?styling=default-theme#stream-type

**Comment by snipcola** [comment]
I tried setting that via `streamType: "on-demand"`, it doesn't seem to help. I'm using JavaScript, so my current set-up looks something like:
```js
import { VidstackPlayer, VidstackPlayerLayout } from "vidstack/global/player";

const player = await VidstackPlayer.create({
  target: PLAYER_ELEMENT,
  src: DASH_URL,
  layout: new VidstackPlayerLayout({
    menuContainer: PLAYER_ELEMENT,
    hideQualityBitrate: true,
    noAudioGain: true,
    seekStep: 5,
  }),
  viewType: "video",
  streamType: "on-demand",
  keyTarget: document,
  crossOrigin: true,
  playsInline: true,
  autoPlay: true,
  hideControlsOnMouseLeave: true,
  logLevel: "silent",
  preload: "metadata",
  load: "eager",
  posterLoad: "eager",
});
```
