### ISSUE TITLE
Thumbnails not displayed properly when not 16:9

### ISSUE THREAD

**Issue by Benny739** [vidstack/player#1399]
### Current Behavior:
Thumbnails are always shown as 16:9 images

### Expected Behavior:
Thumbnails are shown in their correct aspect ratio

### Steps To Reproduce:
Use this thumbnail vtt: 
https://vod-qa-hdd-01.b-cdn.net/3InDYWsdUyklwEfMCl9j/4fd25367-d81f-41d2-bf19-d96a792292ae/SBxIka8QxPmBwPiM2Ygk.vtt

### Anything Else?

vidstack:
![CleanShot 2024-08-16 at 20 45 02@2x](https://github.com/user-attachments/assets/1d17cf62-62eb-45ac-bc58-9c1dc8b5217b)

plyr:
![CleanShot 2024-08-16 at 20 45 59@2x](https://github.com/user-attachments/assets/3249ecaf-2c2f-48f8-bd6d-f9a4bf49a88a)

Same problem in the chapter view
![CleanShot 2024-08-17 at 13 45 35@2x](https://github.com/user-attachments/assets/89fb75ce-3045-45b2-8ffa-db1f2a035831)

**Comment by Benny739** [comment]
This fix broke Thumbnails for all our videos. Also 16/9 aspect ratio is not working anymore.
![CleanShot 2024-09-17 at 18 35 59@2x](https://github.com/user-attachments/assets/c82f34df-caca-4b28-b019-a6ae895068c5)

**Comment by mihar-22** [comment]
In this case, specify the desired aspect ratio using CSS:

```css
.vds-video-layout {
  --media-thumbnail-aspect-ratio: 16 / 9;
}
```

👉 [Default Layout > CSS Variables](https://www.vidstack.io/docs/player/components/layouts/default-layout?styling=default-theme#css-variables)

**Comment by Benny739** [comment]
@mihar-22 
The css syntax in calc is wrong:

> Current implementations require that for the * and / operators, one of the operands has to be unitless. For /, the right operand must be unitless. For example font-size: calc(1.25rem / 1.25) is valid but font-size: calc(1.25rem / 125%) is invalid.

https://developer.mozilla.org/en-US/docs/Web/CSS/calc#rules_and_best_practices_while_using_calc
