### ISSUE TITLE
Video play state toggles on quality change

### ISSUE THREAD

**Issue by taran2k** [vidstack/player#1407]
### Current Behavior:
Instead of the video continuing playback when changing the video's quality, the playback state toggles to play or pause, depending on its current state. This means that if I pause a video and then change the quality, the video would start playing. If I play a video and change the quality, the video would pause.

[current](https://github.com/user-attachments/assets/40fa1b0d-dea9-47b8-8881-42f1fa353cb6)

### Expected Behavior:

Wanted behaviour would be for the video to just keep its current playback state (playing or paused) throughout any quality changes.

### Environment:
- Framework: Vue 2.7

**Comment by ZoltanDalmadi** [comment]
Can confirm, does the same with React as well.
