### ISSUE TITLE
Audio boost causes silence for audio view

### ISSUE THREAD

**Issue by wplit** [vidstack/player#1413]
Issue can be seen on the demo - https://www.vidstack.io/player/demo

Go to the audio player and try to boost the audio, the player goes silent.

Also experiencing the same when using web components on the v1.12.9 version.

**Comment by mdapper** [comment]
I'm seeing the same problem, if a try to change the boost slider the audio goes silent. In the console appear the following message:

```
MediaElementAudioSource outputs zeroes due to CORS access restrictions for [LINK TO AUDIO HERE]
```

Tested on Chrome 128 on Windows 10 and Safari on iOS 17.6.1.

The audio only goes silent after I try to change the boost. I can hear again after refreshing the page.

**Comment by mihar-22** [comment]
Unfortunately I can't repro this bug as well. It's working across Chrome, Safari, and Firefox in my testing. In mdapper case it requires setting crossorigin on the player.
