### ISSUE TITLE
Implement Google Widevine DRM and Apple fairplay DRM to protect against piracy

### ISSUE THREAD

**Issue by jasonkaplan79** [vidstack/player#1438]
### Problem:
Videos can be pirated easily (even if you host videos using .m3u8 files), using chrome extensions.

### Describe:
Implement Google Widevine DRM and Apple fairplay DRM, to protect against video piracy. 
This would prevent videos from being downloaded by inspecting source, or using a chrome extension. Also, recording the screen while the video is playing would turn off the visuals, so that only the sound is audible.

**Comment by Curetix** [comment]
This is already supported by hls.js, you just to configure the DRM for your source. See the [hls.js docs](https://github.com/video-dev/hls.js/blob/master/docs/API.md#drmsystems) and [how to configure](https://www.vidstack.io/docs/player/api/providers/hls#configuring) the hls provider with Vidstack.

**Comment by jasonkaplan79** [comment]
@Curetix Thank you for the response. 

I'm looking at your links to the [hls.js docs](https://github.com/video-dev/hls.js/blob/master/docs/API.md#drmsystems). Implementing Widevine would require a license server to provide licenses with keys to authorized users, is that correct? If that is the case, then there is no way to self-host and to be 100% independent? (I am told there isn't, but I am not very knowledgeable on this topic)

In the remote case that it is possible, a tutorial or codebase for implementing Widevine / DRM encryption with Vidstack would be SO helpful. 🙌

**Comment by Curetix** [comment]
Yeah, that's pretty much it. You'd have to use a third-party hosting service that offers DRM protection, like Mux or Bunny - but it's usually an enterprise feature and therefore expensive.

There are a couple of less complex ways to protect your videos from "easy" downloading, refer to [this article from Mux](https://www.mux.com/blog/if-someone-can-watch-it-they-can-steal-it-securing-video-content-on-the-internet).

**Comment by jasonkaplan79** [comment]
@Curetix thank you for clarifying and for the link. So I guess there is no "free" way to do it...
