### ISSUE TITLE
Changing The Menu css

### ISSUE THREAD

**Issue by kissyfaceDev** [vidstack/player#1440]
### Related Problem:

the current Menu is Heavy on lower-end devices , tv's included , i noticed a strange behavior where it slows down a bit before opening . 

### Describe:

Can the default Menu layout css  be simpler , and maybe instead of the opening effect the menu could just be display none or opacity 0 , when not active ,  and also can the quality option be outside the playback ,

**Comment by mihar-22** [comment]
Our library is built in a way that you can build/design it however you like. Feel free to check out the examples and docs to get started.

**Comment by kissyfaceDev** [comment]
> Our library is built in a way that you can build/design it however you like. Feel free to check out the examples and docs to get started.

thank you , but how do i remove the preset backdrop filter on the menu background ?
