### ISSUE TITLE
Persist playback speed

### ISSUE THREAD

**Issue by alopatindev** [vidstack/player#1496]
It would be nice if the speed setting could survive page refresh, similar to YouTube.

**Comment by mihar-22** [comment]
Check out the [storage](https://www.vidstack.io/docs/player/core-concepts/loading?styling=default-theme#storage) option for storing and resuming player/media state.

**Comment by alopatindev** [comment]
Oh, it seems it actually stores and resume the speed correctly. For some reason I was sure it doesn't. If it actually didn't — I don't reproduce it anymore.
