### ISSUE TITLE
How to avoid automatic fullscreen on android?

### ISSUE THREAD

**Issue by aahrvatska** [vidstack/player#1504]
Hi, on android if click play, video is automatically played in full screen mode (and screen is rotated). How can I avoid this. I want to go to fullscreen only when I click on fullscreen button, otherwise I expect video to stay as it is. Please help!

I'm pretty sure this is not bug, but I still need help.

**Comment by mihar-22** [comment]
Set playsinline on the player. It’s in the installation docs.

**Comment by aahrvatska** [comment]
Thank you!!!!
