### ISSUE TITLE
Deployment not found 

### ISSUE THREAD

**Issue by anime-kun32** [vidstack/player#1506]
### URL: vidstack.io
I wanted to use the player so I went to the docs and found this 
![Screenshot_20241116-111721](https://github.com/user-attachments/assets/0e327a4e-61fb-487f-8f1f-8c3201e9c2e4)

**Comment by mihar-22** [comment]
Working on it, changing provider

**Comment by mihar-22** [comment]
It's back up

**Comment by anime-kun32** [comment]
Thanks
