### ISSUE TITLE
Rel for Youtube

### ISSUE THREAD

**Issue by DevolderLouise** [vidstack/player#1510]
### Describe:

Is there a way we can hide the related video's for Youtube when the video comes to an end? Or at least show video's from the same channel? I know that Youtube has parameters for this but when I try to use this it doesn't work or maybe I am using it the wrong way? I don't immediately find this in the docs. The related video's are also shown sometimes when the video is on a loop, it happens when the video is not in the viewport or when you change tabs and then go back to the video

**Comment by mihar-22** [comment]
Nope, this cannot be changed.

**Comment by brenjt** [comment]
Any plans to allow changing parameters or customizing the parameters that are placed on the URL so one can add the `rel=1` attribute?
