### ISSUE TITLE
map files missing from cdn.vidstack.io

### ISSUE THREAD

**Issue by aahrvatska** [vidstack/player#1526]
Video can not be loaded on Safari browser (iPhone), browser reporting error that these files are missing (404):

https://cdn.vidstack.io/sm/f7c8e421fe7a96957bbdb183157b7f64b55473a5dbd39add21677c7d58140dfe.map
https://cdn.vidstack.io/sm/e2e7cdacd9e0c42b50f25770ecd0b238e0a40062ec9bdac98fbd59761dffa12d.map
https://cdn.vidstack.io/sm/79d503dbbfdc0155ce1feb7293451ab250128a615b96c3a84f4a7941a411889e.map
https://cdn.vidstack.io/sm/f39311a35b328d8da937837128949a70e558bb2ae27fc3ba97760d6eb420c46a.map

What can I do? Where can I find these files? Please help!

![Screenshot 2024-12-01 192827](https://github.com/user-attachments/assets/af8ca8d9-6913-4708-92d8-0759b6d04ff6)

**Comment by mihar-22** [comment]
Duplicate #1525
