### ISSUE TITLE
Provider: LBRY

### ISSUE THREAD

**Issue by tomByrer** [vidstack/player#174]
API/tech overview: https://lbry.tech/

Current (new) web portal for videos: https://odysee.com

They claim 20_000_000 users, 'trending' videos get only 10s-100s of viewers, but does have several larger personalities like [Tim Pool](https://odysee.com/@timcast:c9) with 100_000 followers.

Some clues:
https://lbry.com/faq/video-publishing-guide
https://lbry.tech/playground
https://lbry.org/tavern/

**Comment by mihar-22** [comment]
Closing as this is a really old request and not something we're looking to support any time soon. Thanks!
