### ISSUE TITLE
Cross-component communication channel

### ISSUE THREAD

**Issue by mihar-22** [vidstack/player#24]
## Tasks

- [ ] Design and implement an interface for enabling components to communicate with each other.

## Notes

It's important to be aware that components will mount the DOM at different times, so the final solution will need account for this.

**Examples**

- Controls needs to be aware of components such as captions/settings to implement collision detection.
- IconLibrary needs to be aware of icons so when the icon library changes all icons can be redrawn.
- Settings needs to be aware of any controller that will be used to open/close it.

## References

- https://github.com/vidstack/player/blob/main/docs/architecture/ui-patterns.md#component-communication

**Comment by mihar-22** [comment]
Disregard this for now as we might not actually require a complex communication channel as the use-cases are specific and small for now (as shown in the examples). We can revisit this in the future if needed.

**Comment by tomByrer** [comment]
I don't think UI components should communicate with each other directly; they should always check in with a central state (eg in core).  If they need to obtain information, they can subscribe.
