### ISSUE TITLE
Vidstack Player Beta

### ISSUE THREAD

**Issue by mihar-22** [vidstack/player#580]
It's Beta time -> https://github.com/vidstack/player/discussions/626.

---

This is a general issue to highlight we're currently working towards a Beta release of the library. You'll find all related issues in our [Beta project board](https://github.com/vidstack/player/projects/2). 

## Goals

The primary goal moving into Beta is to open the player up to the public so we can start gathering feedback on the road to [1.0](https://github.com/vidstack/player/projects/1). We're still stress testing this player in a variety of ways at Reddit, but we need more diversity in feedback, especially around the UI building/customization.

Related to this primary goal are the following:

- A stable player foundation/architecture.
- A stable foundation for player UI building and styling.
- Comprehensive documentation and examples.

Stable here simply means no more breaking changes.

## Non-Goals

Reaching feature parity with Vime/Plyr. This means that not all providers and player functionality will be available in Beta. This goal is planned for our [1.0](https://github.com/vidstack/player/projects/1) release which should sharply follow the Beta release. _Why?_ Simply because we feel it's more important to get the player into more hands at this early stage, so we can gather feedback before we move forward. To note, we might still build some features out during Beta in-parallel with 1.0 if time permits.

## FAQ
 
❓ **_Which providers will be supported in the Beta?_**

- [HTML5 Audio](https://github.com/vidstack/player/blob/main/src/providers/audio/AudioElement.ts)
- [HTML5 Video](https://github.com/vidstack/player/blob/main/src/providers/video/VideoElement.ts)
- [HLS Video](https://github.com/vidstack/player/blob/main/src/providers/hls/HlsElement.ts) (via [`hls.js`](https://github.com/video-dev/hls.js/))

❓ **_What functionality will be available?_**

We currently support the entire native [HTMLMediaElement spec](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) which includes everything like `autoplay`, `playsinline`, `paused`, `muted`, `volume`, etc. 

You can find all currently supported [properties here](https://github.com/vidstack/player/blob/main/src/media/MediaContext.ts), and [events here](https://github.com/vidstack/player/blob/main/src/media/events.ts).

❓ **_What UI components are available?_**

You can find them [here](https://github.com/vidstack/player/tree/main/src/ui), but the list might be deceiving as more functionality than what's visible at the surface is or will be possible. We'll provide more information on that soon.

❓ **_Will any framework integration wrappers be available?_**

The only one that is planned for the Beta release is React, since other frameworks now completely support web components. The React integration will also be our opportunity to test out SSR options. 

Other integration wrappers such as Svelte/Vue are definitely still being considered for both SSR and better DX reasons.

## Comments

If you have any concerns/questions/requests for this Beta release, please let us know below👇  It's important to note that having solid reasons, accompanied with potential business use-cases and examples for why something should be prioritized, is going to go much further than suggesting you simply want something.

**Comment by sparkktv** [comment]
I use Plyr on my website and just wanted to know a few things about this 'merger'. Can we continue to use Plyr if we choose to? Also will YouTube/Vimeo support come like Plyr has?

**Comment by mihar-22** [comment]
Hey @sparkktv, I've [answered these questions](https://github.com/sampotts/plyr/issues/2408#issuecomment-1022677177) over in the Plyr announcement since it's related to the repo 👍

**Comment by mihar-22** [comment]
It's Beta Time -> https://github.com/vidstack/player/discussions/626.
