### ISSUE TITLE
Which package manager?

### ISSUE THREAD

**Issue by marcelgruber** [vidstack/player#606]
The repo appears to currently be using `npm`. Is this the long term plan? Thoughts on `yarn`? What about [https://pnpm.io/](https://pnpm.io/)?

**Comment by mihar-22** [comment]
For now `npm` is great as we don't have any complex workspace/monorepo requirements. From a performance perspective `npm` v7+ has no issues keeping up with `yarn` or `pnpm` once a lockfile is present (in my experience). It also becomes a bother having to setup installation for `pnpm` in CI, or warn contributors that they have to use `pnpm` (not a big deal but slight hurdle). 

As soon as we require a monorepo setup we'll definitely switch straight over to `pnpm`. What do you like using and why?

**Comment by marcelgruber** [comment]
I concur on all points. `npm` is more than sufficient for now. 

I don't have a strong preference. I usually just use whatever a repo ships with because it's one less thing to worry about, but as far as I can tell, `pnpm` is the most compelling long term solution. 

Feel free to close this issue, unless we want to keep it open for additional discussion?
