### ISSUE TITLE
Audio Error

### ISSUE THREAD

**Issue by studywithdesign** [vidstack/player#623]
It's showing an error while using @vime/react in the next js

`Error: Cannot find module './Audio'`

`Require stack:
- D:\web\studywithdesign2\node_modules\@vime\react\dist\cjs\components\index.js
- D:\web\studywithdesign2\node_modules\@vime\react\dist\cjs\index.js
- D:\web\studywithdesign2\.next\server\pages\index.js
- D:\web\studywithdesign2\node_modules\next\dist\server\require.js
- D:\web\studywithdesign2\node_modules\next\dist\server\load-components.js
- D:\web\studywithdesign2\node_modules\next\dist\build\utils.js
- D:\web\studywithdesign2\node_modules\next\dist\build\output\store.js
- D:\web\studywithdesign2\node_modules\next\dist\build\output\index.js
- D:\web\studywithdesign2\node_modules\next\dist\cli\next-dev.js
- D:\web\studywithdesign2\node_modules\next\dist\bin\next`

**Comment by mihar-22** [comment]
This is the Vidstack Player, not Vime.
