### ISSUE TITLE
Missing import file extensions in dist/* breaks Node module resolution.

### ISSUE THREAD

**Issue by plauclair** [vidstack/player#631]
I'm trying to get this working in a NextJS SSR setup, but Node's module resolution is failing because the imports in the build version are missing file extensions. Unfortunately in NextJS, the module resolver cannot be set in such a way to have it work otherwise unless Babel is used with custom transforms.

See https://nodejs.org/api/esm.html#esm_mandatory_file_extensions. I believe this is a requirement when package.json's `type` is `module`.

**Comment by mihar-22** [comment]
Yep, noticed that too. I've fixed this and also added SSR support in the `monorepo` branch. It should be ready by tomorrow night.

**Comment by plauclair** [comment]
Awesome! Thanks!
