### ISSUE TITLE
SvelteKit  warning : A11y: <video> elements must have a <track kind="captions">

### ISSUE THREAD

**Issue by rhscjohn-dev** [vidstack/player#648]
With your March 2022 release now using the HTML5 `<video>` element, SveleteKit throws A11y warning:  A11y: `<video>` elements must have a `<track kind="captions">`svelte(a11y-media-has-caption).

For documentation purposes, the `<video>` element should be as follows.
```
    <video
      controls
      src="https://media-files.vidstack.io/720p.mp4"
      poster="https://media-files.vidstack.io/poster-seo.png"
      preload="none"
    >
      <track kind="captions" />
    </video>
```

**Comment by mihar-22** [comment]
Thanks @rhscjohn-dev! I'll add a note to the Svelte docs.
