### ISSUE TITLE
SvelteKit example issue

### ISSUE THREAD

**Issue by rhscjohn-dev** [vidstack/player#650]
I am trying to reproduce your SvelteKit example and I am having an issue.

The player ends up being the size of the poster.
![Screenshot 2022-04-05 171716](https://user-images.githubusercontent.com/60523782/161850772-25b5a1cf-16f9-4062-b29d-17524571a395.png)

While the {#await  . . . } block is processing I get a flash of the HTML5 video player(that is triple the size of the poster image) and when the  {:then player} block is executed; the player is the size of the poster image.

I can click on the the tiny player and i get this: 
![Screenshot 2022-04-05 172442](https://user-images.githubusercontent.com/60523782/161852411-4cd6fc18-294b-4673-8425-0f3744495d0e.png)

page.svelte
```
<script>
  import LazyPlayer from "$lib/LazyPlayer.svelte";
</script>

<LazyPlayer
  src="https://media-files.vidstack.io/720p.mp4"
  poster="https://media-files.vidstack.io/poster-seo.png"
/>
```

LazyPlayer.svelte
```
<script>
  export let src;
  export let poster;
</script>

{#await import("$lib/player.svelte")}
  <!-- Render video if JavaScript is disabled. -->
  <video {src} controls preload="none">
    <track kind="captions" />
  </video> />
{:then player}
  <svelte:component this={player.default} {src} {poster} />
{/await}
```

player.svelte
```
<script>
  import "@vidstack/player/define/vds-media.js";
  import "@vidstack/player/define/vds-video.js";

  export let src;
  export let poster;
</script>

<vds-media>
  <vds-video controls {poster}>
    <video {src} controls preload="none">
      <track kind="captions" />
    </video>
  </vds-video>
</vds-media>
```
Project Directory
![Screenshot 2022-04-05 173301](https://user-images.githubusercontent.com/60523782/161853544-a7c41c9a-47ef-4bd4-a54f-cec513c31e8d.png)

**Comment by mihar-22** [comment]
Closing this as the issue is stale and we'll have Svelte integrations coming soon that can SSR :)
