### ISSUE TITLE
SKIN OR THEME

### ISSUE THREAD

**Issue by kinseria** [vidstack/player#651]
Is there any vidstack player skin or theme or how could I create one.

**Comment by robinlahtinen** [comment]
Vidstack Player would be awesome if it was as easy to use like Plyr, with it having sensible defaults for plug-and-play use (UI being the most important factor). Currently Vidstack doesn't replace Plyr without spending time on building user interface and other missing or barebone features, which cost man-hours. I still like the idea of Vidstack as it currently is!

**Comment by mihar-22** [comment]
It’s mentioned in the docs that it’s on the roadmap. We definitely understand and there’ll be a much easier/quicker setup path in the near future :)

**Comment by mihar-22** [comment]
Our UI components now contain a default look out of the box which should speed up development.

Skins are tracked here: 

- [Community Skin Discussion](https://github.com/vidstack/player/discussions/702)
- [Community Skin](https://github.com/vidstack/player/issues/73)
- [Plyr Skin](https://github.com/vidstack/player/issues/74)
