### ISSUE TITLE
Not able to make work in angular +2

### ISSUE THREAD

**Issue by dhertzb** [vidstack/player#664]
ERROR: 
![image](https://user-images.githubusercontent.com/45174543/175393569-307198ac-e934-43c6-9fdd-514058965117.png)

in the component:

![image](https://user-images.githubusercontent.com/45174543/175393827-71a1983d-9014-4a35-857e-3f8c52bf6605.png)

tsconfig.json

![image](https://user-images.githubusercontent.com/45174543/175393998-e20e652b-3f9f-46b3-8426-ad30c709f324.png)

**Comment by Destreyf** [comment]
@dhertzb Were you able to get this working?

I am about to start experimenting with this video player but my immediate reaction to this would be related to the version of angular/typescript you're using.

**Comment by mihar-22** [comment]
Closing this now since we've released new packages, if issue persists we can open a new ticket :)
