### ISSUE TITLE
Licence question

### ISSUE THREAD

**Issue by thagxt** [vidstack/player#670]
I am considering several options for my next project, and **Vidstack** seems to be the best one. I would like to know from you, if **Vidstack** will remain under `MIT licence` after `version 1.0` and if all options like **YouTube** and **Vimeo** will also be available under the same licence?!

thank you

**Comment by mihar-22** [comment]
Hey @thagxt everything in this repo, including any providers we add in the future, will be under the MIT license now and after the 1.0 release. Hope that helps!
