### ISSUE TITLE
Documentation: `singlePlayback` bug 🐛 

### ISSUE THREAD

**Issue by pietrop** [vidstack/player#676]
**Describe the bug**

There seems to be an issues with [Single Playback](https://www.vidstack.io/docs/player/react/components/media/media-sync/#single-playback) example `singlePlayback`

>The `singlePlayback` property will ensure that only one media provider is playing at any given moment. All providers that are registered with `<MediaSync>` and playing will be paused if a new provider begins to play

**To Reproduce**
1. Go to [Single Playback](https://www.vidstack.io/docs/player/react/components/media/media-sync/#single-playback) 
2. Click on first player
3. Click on second player
5. See error, both players are playing at the same time

**Expected behavior**

You'd expect to only have one player playing at a time, and if the second one is click while the first one is playing, the first one should pause.

>The `singlePlayback` property will ensure that only one media provider is playing at any given moment. All providers that are registered with `<MediaSync>` and playing will be paused if a new provider begins to play

**Screenshots**

![bug singlePlayback](https://user-images.githubusercontent.com/4661975/200128740-26533a62-929c-4bbe-8069-48cff15a2404.gif)

**Additional context**

Tbh I don't know if the bug is with the demo on the documentation site or the functionality itself. (I guessing probably the latter)

Happy to contribute with a PR with a bit of guidance on how to best tackle this.

**Comment by mihar-22** [comment]
Thanks for bringing this up. Interesting, this may be a browser/device issue? I just tested on Desktop Chrome and it's working fine. As mentioned in Discord, we're in the middle of a tooling upgrade but we can come right back to this after next week 👍

**Comment by pietrop** [comment]
Sounds good, thanks! happy to test it again when ready (not urgent on my end)

**Comment by josh-tt** [comment]
Same issue here in Chrome version 108.0.5359.98 (Official Build) (arm64). In safari 15.6.1  it doesn't want to load at all (showing the html5 controls), but not playing on click.

**Comment by mihar-22** [comment]
Closing for now as this as `<vds-media-sync>` has temporarily been removed as we review it. If the issue persists with the new implementation we can open a new ticket :)
