### ISSUE TITLE
Documentation: `MediaVisibility` bug 🐛

### ISSUE THREAD

**Issue by pietrop** [vidstack/player#677]
**Describe the bug**

>The `<MediaVisibility>` component can be used to manage the playback/volume state of a provider as page/viewport visibility changes. The [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) and [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) are used to detect visibility changes, including minimizing the browser window, device sleep, changing tabs, or scrolling the provider in and out of view.

**To Reproduce**
1. Go to [Viewport Visibility](https://www.vidstack.io/docs/player/react/components/media/media-visibility/#viewport-visibility)
2. Scroll down to get the video out of video
4. See error, video is not pausing

**Expected behavior**

>Scrolling down away from player will pause playback

**Screenshots**

![bug MediaVisibility](https://user-images.githubusercontent.com/4661975/200128884-a802f24a-c435-4d7f-beaa-49fcdd515ab5.gif)

**Additional context**

I think [Page Visibility](https://www.vidstack.io/docs/player/react/components/media/media-visibility/#page-visibility) has as a similar 🐛

**Comment by mihar-22** [comment]
Same notes as #676

**Comment by mihar-22** [comment]
Closing for now as this as `<vds-media-visibility>` has temporarily been removed as we review it. If the issue persists with the new implementation we can open a new ticket :)
