### ISSUE TITLE
Documentation: `BufferingIndicator` top of page import example might be (slightly) confusing

### ISSUE THREAD

**Issue by pietrop** [vidstack/player#682]
The `BufferingIndicator` top of page import example might be (slightly) confusing

>We don't provide a buffering indicator component out of the box because you can easily create one with some HTML, CSS, and [media attributes](https://www.vidstack.io/docs/player/react/getting-started/styling/#media-attributes).

Which I think it's fair, the example below it's good. 

But the import at the top of the page might be a bit confusing? (I am guessing it might be autogenerated?)

```js
import { BufferingIndicator } from '@vidstack/player-react';
```
- [Doc page in github `player/apps/site/pages/docs/player/[lib]/[2]components/[3]ui/[5]buffering-indicator/index.md`](https://github.com/vidstack/player/blob/d6f6b409fc69517bde2cc2f98ef1b7251588f19a/apps/site/pages/docs/player/%5Blib%5D/%5B2%5Dcomponents/%5B3%5Dui/%5B5%5Dbuffering-indicator/index.md)
- doc page [Buffering Indicator](https://www.vidstack.io/docs/player/react/components/ui/buffering-indicator/#styling)

Screenshot 

<img width="1269" alt="Screen Shot 2022-11-05 at 3 50 03 PM" src="https://user-images.githubusercontent.com/4661975/200138351-e3f3c25c-94f5-4726-9d62-3548cfff33e3.png">

Same for the `API` tab on that page

**Comment by mihar-22** [comment]
Yep another bug from when we migrated our docs over. This also applies to the [Controls](https://www.vidstack.io/docs/player/components/ui/controls/) docs. We need to not show the import snippets for those respective components [here](https://github.com/vidstack/player/blob/main/apps/site/pages/docs/player/%5Blib%5D/%5B2%5Dcomponents/%40markdoc/component_import.svelte). Something like adding the following:

```html
<script>
import { elementTagName } from '$src/stores/element'; 

const invalidElements = new Set(['vds-buffering-indicator', 'vds-controls']);

$: hideSnippets = invalidElements.has($elementTagName);
</script>
```

**Comment by pietrop** [comment]
Tried here https://github.com/vidstack/player/pull/684 but I still see the code snippets when I run the preview of the site locally. Not sure I did the change correctly?

**Comment by mihar-22** [comment]
My bad, forgot to mention we need to an additional `if` clause.

```html
{#if $comingSoonElement}
  <p>This component is not available yet.</p>
{:else if !hideSnippets && $jsLib === 'react'}
  <CodeFence lang="tsx" code={react[0]} highlightedCode={react[1]} copy />
{:else if !hideSnippets}
  <CodeFence lang="js" code={js[0]} highlightedCode={js[1]} copy />
  <CodeFence lang="html" title="cdn" code={cdn[0]} highlightedCode={cdn[1]} copy />
{/if}
```

**Comment by pietrop** [comment]
Ok, great, that worked, thanks. I've also added some logic to remove the `API` tab (which was then empty) for those two pages. https://github.com/vidstack/player/pull/684
