### ISSUE TITLE
`ReferenceError: throttle is not defined` in production build of a NextJS project

### ISSUE THREAD

**Issue by SimpleIndian** [vidstack/player#685]
**Describe the bug**

Timeslider is not working in production build in a Nextjs application. 
Not able to drug or move the thumb, also the look is different

after checking the console i saw this error. 

```js
Uncaught ReferenceError: throttle is not defined
    at new iS (276.9dd1b3dceef59929.js:21:10599)
    at uQ (framework-7751730b10fa0f74.js:9:84368)
    at o4 (framework-7751730b10fa0f74.js:9:107344)
    at o3 (framework-7751730b10fa0f74.js:9:107226)
    at o1 (framework-7751730b10fa0f74.js:9:107094)
    at o0 (framework-7751730b10fa0f74.js:9:106957)
    at oQ (framework-7751730b10fa0f74.js:9:104078)
    at lf (framework-7751730b10fa0f74.js:9:45454)
    at framework-7751730b10fa0f74.js:9:101676
```
on dev tool source
![image](https://user-images.githubusercontent.com/58888934/200606833-6d764257-fc82-4309-92de-ad338fdbacc7.png)

**To Reproduce**
1.  This is the player source code https://gist.github.com/SimpleIndian/704bdc8afae9543554c5875c5c441974
2.  Used it in a component. https://gist.github.com/SimpleIndian/0958b66ab556e62af62d12da57aabb22
3.  Build for production, view the production site
4.  Should be able to see the bug

**Expected behavior**
Time slider should work as it is working in dev mode  ( refer to screenshot )

**Screenshots**

### In dev mode
![image](https://user-images.githubusercontent.com/58888934/200605340-af9657ac-34b7-4a92-9849-a6f9771b3a08.png)

### Production build
![image](https://user-images.githubusercontent.com/58888934/200604011-924c5bb6-d7a0-4ab3-8657-35453c5272ee.png)

**Desktop:**
 - OS: Windows 10 21H1
 - Browser : Brave Version 1.45.118  Chromium: 107.0.5304.91 (Official Build)  (64-bit)
 
![image](https://user-images.githubusercontent.com/58888934/200607242-664f88d7-6122-40fe-9b5c-dcf9651ea514.png)

**Comment by nodgear** [comment]
Same issue here, anywhere `debounce` and `throttle` are imported has this problem, including the gesture component

**Comment by nodgear** [comment]
I'm willing to attempt a fix if @mihar-22 has any idea about the issue and guides us towards what is causing it so i can take a look.

`debounce` and `throttle` are imports from the [just library](https://github.com/angus-c/just/) and are used on components but.
checking for `just` issues [i found this one](https://github.com/angus-c/just/issues/332) 

@SimpleIndian could you update the peer dependency of `just-throttle` and `just-bounce` and test?

**Comment by nodgear** [comment]
Context for others:
1.6.5 was an attempt to fix by tagging just lib as external, doesn't seem to work (sadly).
the issue still happens in production

**Comment by mihar-22** [comment]
Closing this now since we've released new packages, if issue persists we can open a new tick.
