### ISSUE TITLE
When is v1 launching?

### ISSUE THREAD

**Issue by thagxt** [vidstack/player#704]
What happened with Vidstack version 1? It was scheduled for release in November, according to the official website, but November is basically over. Any news? Thanks

**Comment by mihar-22** [comment]
Working hard to get to 1.0 but there’s a lot of work, especially considering we had to build our own Web Components tooling to ensure framework integrations work as expected.

Pretty much all popular OSS projects are late and don’t set a date for a good reason. It’s best to just release when we’re ready and not have anyone wait on a date.

We have ongoing discussions for our packages and skins, and we have a release dropping this week with lots of new things. We’re confident that after our next release we have everything we need to finally push forward.

Sorry about all the delays but we’re getting there!

**Comment by thagxt** [comment]
Absolutely, rushing and releasing bugs is no good. Thanks for the update, I'll gladly wait. :)
