### ISSUE TITLE
Changing the source dinamically

### ISSUE THREAD

**Issue by nodgear** [vidstack/player#705]
Reading the API it doesn't seem possible to add video sources dinamically

Example: Fetching the stream URL on `useEffect` and adding that stream as source for the player
Remounting the whole component when the data is pulled is a bad design (plus, in this use case the data will not be removed but rather swapped)

I have tried the following:

```ts
// on useEffect:
const episodeData = await retrieveEpisodeM3U8()

const source = document.createElement('video')
source.src = episodeData.sources[0].src
provider.current!.appendChild(source)
provider.current!.startLoadingMedia()

// component
return (
    <Media ref={player}>
      <Hls poster="https://media-files.vidstack.io/poster.png" controls ref={provider}>
        <video poster="https://media-files.vidstack.io/poster-seo.png" />
      </Hls>
    </Media>
)
```
Am i doing this wrong?
Is there any way to do this with Vidstack or Vime that doesn't envolve remounting the video component when fetching data?

There's similar issues on Vime repository, this could be done with plyr by invoking HLS and appending the media
On video.js it's easily done by the loadMedia / src methods.

**Comment by mihar-22** [comment]
It looks like you’re appending the source on the wrong element. It’s currently on the provider, it should be on <video>.

**Comment by nodgear** [comment]
In this code i'm creating a `video` element 
Adding the source attribute 
And then apennding `video` to the `provider`

> Source: HTMLVideoElement


----
I ended up getting it to work by modifying the existing video element and changing the source, i guess the observable took care of it, but the player jumps in size and style when the source is changed... for now i'm remounting the player.
