### ISSUE TITLE
unified provider wrapper

### ISSUE THREAD

**Issue by tomByrer** [vidstack/player#708]
Ideally a separate project where all providers are wrapped so there is a single API surface to use them all.
Then this wrapper can be used in other players, like your other 2, I might make one with Mitosis, etc.

Once you have a few examples, people can add their own provider, so hopefully it will save you work in long-run.

I thought of something similar long ago for [VideoJS](https://github.com/videojs/video.js/issues/5974), where their 'tech' is exported without UI.

**Comment by mihar-22** [comment]
We're partially there with this issue in the latest `0.1.0` release. We moved the base provider API including props/methods/events and so on up to the `<vds-media>` element. 

I've also thought about exposing providers as modules that you can set on the media element but not sure how to approach it yet. It's a little out of scope so we can visit this after we reach 1.0 - I don't want to delay it any further then it has been by tooling issues.

**Comment by mihar-22** [comment]
Our latest release `0.2.2` has this type of functionality now baked in on the `<media-player>` element. We have provider tech (no longer elements) and auto-provider detection based on the current source.
