### ISSUE TITLE
Add ability to increase playback speed to 1.5/2 x

### ISSUE THREAD

**Issue by nikitavoloboev** [vidstack/player#709]
**Is your feature request related to a problem? Please describe.**

This is a must have feature I need before integrating video on my site. I didn't find it yet implemented. Hope it's possible to add.

**Describe the solution you'd like**

<img width="450" alt="image" src="https://user-images.githubusercontent.com/6391776/208299085-b124189e-c479-498b-9b12-1978d8acd06f.png">

Basically this feature to increase playback speed. 

Also as bonus hotkeys like `>` to increase playback speed from keyboard. Similar to YouTube.

**Describe alternatives you've considered**

Alternative is to use another video embedding system but I do like this library.

**Comment by mihar-22** [comment]
Hey @nikitavoloboev!

Ye playback rate API is a must. I'm in the middle of a migration but I should be wrapping up very soon. I'll try to get playback rate support in for you this week 👍 However, keyboard support will be coming in a little later right before we start building our community skin.

**Comment by nodgear** [comment]
You can select the video component and do it manually if you're in a rush.

```ts
 this._provider = media.provider
   
  //[...]
  
  public switchPlaybackSpeed(speed: number) {
    if (!this._provider) { return }

    const video = this._provider.querySelector('video') // or just select the video element in any other way
    video.playbackRate = speed
  }
  ```

**Comment by thehydrogen** [comment]
@mihar-22 This has already been implemented, no? I think this can be closed as completed

**Comment by mihar-22** [comment]
Yep! Thanks @thehydrogen!
