### ISSUE TITLE
Cannot Find Module /react-dom/server

### ISSUE THREAD

**Issue by Eltik** [vidstack/player#717]
**Describe the bug**
Importing the new version of Vidstack results in an error being thrown.

**To Reproduce**
1. Install `react@17.0.0` and `react-dom@17.0.0` or later with NextJS (and likely React).
2. Run `npm i vidstack @vidstack/react`.
3. Import `vidstack/styles/base.css` and `@vidstack/react`:
```typescript
import 'vidstack/styles/base.css';
import { Media, Video } from '@vidstack/react';
```
4. Compile

**Expected behavior**

**Screenshots**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/76538547/213248853-5bdf54b4-747a-44e7-8dd9-6d9942159905.png">
Complete error in console:
```
error - Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/eltik/Documents/Coding/a/node_modules/react-dom/server' imported from /Users/eltik/Documents/Coding/a/node_modules/maverick.js/dist/server/react.js
Did you mean to import react-dom/server.js?
    at new NodeError (node:internal/errors:393:5)
    at finalizeResolution (node:internal/modules/esm/resolve:260:11)
    at moduleResolve (node:internal/modules/esm/resolve:879:10)
    at defaultResolve (node:internal/modules/esm/resolve:1087:11)
    at nextResolve (node:internal/modules/esm/loader:161:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:831:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:413:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  page: '/watch/[id]/[provider]/[watchId]'
}
```

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.0
 - Browser: Google Chrome
 - Version: Vidstack v0.0.2 ran with create-t3-app

**Additional context**
Code used:
```typescript
import 'vidstack/styles/base.css';
import { Media, Video } from '@vidstack/react';

export default function Watch(props: any) {

    return (
    <>
        <Head>
       </Head>
       <main className={styles.main}>
                        <Media className={styles.videoplayer}>
                <AspectRatio ratio="16/9">
                    <HLSVideo poster={props.info.anilist.bannerImage ? props.info.anilist.bannerImage : props.info.anilist.coverImage.extraLarge}>
                        <video className={styles.main_video} preload="none" src={props.sources?.sources[props.sources.sources.length - 1].url ? props.sources?.sources[props.sources.sources.length - 1].url : "https://media-files.vidstack.io/720p.mp4"} controls></video>
                        {props.sources?.subtitles?.map((subtitle: any) => {
                            return <track kind="subtitles" src={subtitle.url} label={subtitle.language} default={subtitle.default} />
                        })}
                    </HLSVideo>
                </AspectRatio>
            </Media>
        </main>
    </>
   );
}
```
And the full file: https://sourceb.in/cjrSbZrR5V

`package.json`:
```json
{
  "dependencies": {
    "@vidstack/react": "^0.0.2",
    "animejs": "^3.2.1",
    "crypto-js": "^4.1.1",
    "node-html-parser": "^6.1.4",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-icons": "^4.7.1",
    "vidstack": "^0.0.2"
  }
}
```
I've tried running it with later versions of react (latest, v18.0.2, etc.) and encounter the same issue. I've also tried using vidstack version 0.0.1.

**Comment by TDanks2000** [comment]
> I just tried modifying the `react.js` file in `/node_modules/maverick.js/dist/server/react.js`. This import works:
> 
> ```ts
> import { renderToStaticMarkup } from 'react-dom/server.js';
> ```
> 
> However I now get the error `window is not defined`. <img alt="image" width="961" src="https://user-images.githubusercontent.com/76538547/213250649-93b48669-56f9-4899-a3fa-11ceff685d0e.png"> File is in `/node_modules/vidstack/dist/server/chunks/chunk-KI5KSLHN.js`. Line:
> 
> ```ts
> /(iPhone|iPod)/gi.test((_a = window.navigator) == null ? void 0 : _a.platform);
> ```

same problem using nextjs

**Comment by mihar-22** [comment]
Thanks for reporting! I'll be looking into this today.

**Comment by mihar-22** [comment]
I found a few issues including incorrect Node exports (resulting in browser bundle being imported server-side, attempting to access `window`, and also React 18 is working towards preserving state whilst re-mounting so I had to make sure we don't destroy at the wrong time. 

It's all fixed, I'll be releasing it tomorrow including few other changes.

**Comment by TDanks2000** [comment]
> I found a few issues including incorrect Node exports (resulting in browser bundle being imported server-side), attempting to access `window`, and also React 18 is working towards preserving state whilst re-mounting so I had to make sure we don't destroy at the wrong time.
> 
> It's all fixed (successfully dev/build in Next). I'll be releasing it tomorrow including few other changes.

hey was just wondering, when will there be an update to vidstack. no rush was just wondering?

**Comment by mihar-22** [comment]
Massive React updates dropping tomorrow :)

**Comment by TDanks2000** [comment]
> Massive React updates dropping tomorrow - including out of the box Next.js support (SSR + React 18)

When's the new update dropping for vidstack?

**Comment by mihar-22** [comment]
Latest release is out and all issues should be resolved - we can re-open if needed:

https://github.com/vidstack/player/discussions/722
