### ISSUE TITLE
Error: Minified React error #61

### ISSUE THREAD

**Issue by Eltik** [vidstack/player#723]
**Describe the bug**
Building a Next/React app with Vidstack results in an error when visiting the page.

**To Reproduce**
1. Install the latest version of Vidstack.
2. Use `<HLSVideo>` and add children (untested).
3. Build the project and server it.
4. See error.

**Expected behavior**
No error when building a NextJS project using Vidstack (works fine locally).

**Screenshots**
![image](https://user-images.githubusercontent.com/76538547/214446390-9d27d331-0b81-4fe0-9984-fcf2793bc13c.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome and Safari on both MacOS and iOS.
 - Version: `"@vidstack/react": "^0.1.0"` and `"vidstack": "^0.1.0"`.

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16.0.2
 - Browser: Chrome and Safari

**Additional context**
I have a built version of this on my test Vercel app:
https://anifytv.vercel.app/watch/151252/Enime/53616c7465645f5ff5c5dd062dcaed54b55f5ee01c1750f2652c04615134953a0e067f6643bedde62437114ee29234f3d0619dd83c2b98963ee2ccc33208c1f9
Everything works fine locally, just not on the public version. Visiting the link in the error results in this:
![image](https://user-images.githubusercontent.com/76538547/214446755-efb1a8fb-902c-4968-bc75-8084b41c2c46.png)
`props.dangerouslySetInnerHTML` must be in the form `{__html: ...}`. Please visit https://reactjs.org/link/dangerously-set-inner-html for more information.

**Comment by mihar-22** [comment]
Oh damn we're mangling the `_` property so it's targetting `__html`. I'll patch it now. Thanks!!

**Comment by mihar-22** [comment]
Fixed in `0.1.1`! Thanks again for letting me know.

**Comment by Eltik** [comment]
No problem tysm
