### ISSUE TITLE
User-idle attribute not working as expected

### ISSUE THREAD

**Issue by thekendog** [vidstack/player#724]
I'm a little confused about the user-idle attribute.  Based on the controls documentation here...

[https://www.vidstack.io/docs/player/components/layout/controls#usage](https://www.vidstack.io/docs/player/components/layout/controls#usage)

...it seems like user-idle attribute should be set to "true" when there is no interaction with the player and removed when there is.  However, all tests I've done and even on the main Vidstack site I see the exact opposite.  When there is interaction with the player the user-idle attribute is set to "true" and it is removed when there is no interaction.  I think this is a bug but I am not sure.

**Comment by mihar-22** [comment]
Ye I shouldn't code when I'm that tired, in an effort to fix it last night I completely messed it up 😅 Patching it now.

**Comment by thekendog** [comment]
Ha. It happens.  Been there myself.

**Comment by mihar-22** [comment]
This should now be resolved in `0.1.4`, let me know if you run into any issues again. Thanks 👍
