### ISSUE TITLE
The requested module 'maverick.js/react' does not provide an export named 'createReactContextProvider'

### ISSUE THREAD

**Issue by steveyout** [vidstack/player#725]
**Describe the bug**
``` The requested module 'maverick.js/react' does not provide an export named 'createReactContextProvider' ```

i get thi error when importing vidstack in nextjs 13.
am using the lates version of vidstack 0.1.5

**Comment by mihar-22** [comment]
Just tested works on my end, possibly try deleting your `node_modules` and lockfile, installing again, and seeing if it works.

**Comment by steveyout** [comment]
> Just tested works on my end, possibly try deleting your `node_modules` and lockfile, installing again, and seeing if it works.

i tried with no success but fixed it by installing with ```yarn```
