### ISSUE TITLE
Error: [vidstack] no media context was found - did you forget to provide it?

### ISSUE THREAD

**Issue by steveyout** [vidstack/player#727]
Error: [vidstack] no media context was found - did you forget to provide it?

Am getting this error while using ```useMediaState()``` .
am using js instead of typescript

**Comment by nodgear** [comment]
No code, no logs... kinda hard to help you there.

- Are you sure you're calling useMediaState() from inside the <MediaProvider> Element?
This hoook is supposed to be used on your UI (inside the provider) as mentioned here: [Documentation](https://www.vidstack.io/docs/react/player/core-concepts/state-management#media-element)

- Do you have your media provider in place?

**Comment by steveyout** [comment]
i fixed it by declaring the media provider in ```_app.js(nextjs)```
