### ISSUE TITLE
Multiple players freeze the whole page

### ISSUE THREAD

**Issue by saaymeen** [vidstack/player#731]
**Describe the bug**
When using more than one instance of the player (in React), the whole page freezes and becomes unresponsive. Reloading the page does not work (loading process becomes stuck once the player files are hit).

**To Reproduce**
1. Create a Next.js app
2. Dynamic import the player components with `{ ssr: false }`
3. Render multiple `<MediaPlayer />`

**Expected behavior**
Page displays multiple videos.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser FF, Safari, Chrome

**Comment by mihar-22** [comment]
Resolved in `0.2.3` @saaymeen. Thanks for reporting!
