### ISSUE TITLE
Tailwind Not Variant

### ISSUE THREAD

**Issue by mihar-22** [vidstack/player#739]
I'm not entirely sure whether Tailwind supports `:not(...)` variants. If it doesn't then we should add not variants ourselves such as `not-media-paused`.

**Comment by danestves** [comment]
You can totally use `:not` inside Tailwind using arbitrary classes https://www.kindacode.com/snippet/using-not-selector-in-tailwind-css/#Example_1

```html
<h1 class="text-blue-500 text-4xl [&:not(h1)]:text-red-500 [&:not(h1)]:text-2xl">KindaCode.com</h1>
```

https://play.tailwindcss.com/z5FVszLi0k

![CleanShot 2023-02-09 at 11 14 42](https://user-images.githubusercontent.com/31737273/217852812-28e6bd42-42bc-4bbe-8dc9-78d99afce290.png)
