### ISSUE TITLE
Player controls no longer show on hover when video has ended

### ISSUE THREAD

**Issue by thehydrogen** [vidstack/player#783]
### Current Behavior:
Player controls do not show on hover, or do not disappear (depending on your hover state when the video ended) once a video has ended.

### Expected Behavior:
Hovering continues to work normally.

### Steps To Reproduce:

HLS video and Vidstack version 0.3.1

### Environment:
- Framework: Vue
- Meta Framework: Nuxt
- Node: 17
- Device: Mobile & Desktop
- OS: Windows, Linux
- Browser: Firefox@109, Chrome@107

**Comment by thehydrogen** [comment]
Tested on Vidstack v0.3.2, the problem persists

**Comment by mihar-22** [comment]
Thanks for reporting, fixed in `0.3.3`!
