### ISSUE TITLE
Browser Native UI showing up

### ISSUE THREAD

**Issue by no-1ne** [vidstack/player#793]
On this page, https://www.vidstack.io/docs/react/player/providers/video

seeing browser native controls, 
![Screenshot 2023-03-14 1 59 34 PM](https://user-images.githubusercontent.com/11027129/224941597-3e1f15c9-acc7-4d4a-9a59-a8c265b0f52f.png)

Browser: Version 110.0.5481.181 (Official Build) (64-bit)

**Comment by Gravy59** [comment]
I think that's intentional because they haven't made a skin yet
