### ISSUE TITLE
HLS Source switching causes level to drop to 0, then loop=true brings it back down each time.

### ISSUE THREAD

**Issue by iDVB** [vidstack/player#795]
### Current Behavior:
1. Load HLS Video1
2. Video is loaded at level 2 (top level)
3. Switch src to Video2
4. Video is loaded at level 3 (top level)
5. Switch src to Video1
6. Video is loaded at level 0

### Expected Behavior:
Would like the level to be maintained or passed thru to the next load when src is switched.

### Example:
https://codesandbox.io/p/sandbox/videobackground-level-err-qywfos

**Comment by nodgear** [comment]
You'd have to set the level yourself on source change.
This is HLS behavior, not vidstack.
HLS automatically picks the level by default (-1)
