### ISSUE TITLE
No way to get Safari iOS to use HLSProvider

### ISSUE THREAD

**Issue by iDVB** [vidstack/player#796]
### Current Behavior:
Safari iOS use the VideoProvider even when setting `preferNativeHLS=false`

### Expected Behavior:
I would think the default would be to use the HLSProvider even when the native is supported, and can be overridden if desired.
Also would think setting `preferNativeHLS=false` should definitely ensure HLSProvider is used.

### Steps To Reproduce:
https://codesandbox.io/p/sandbox/vidstack-ios-safari-not-using-hlsprovider-wothzd?file=%2Fpages%2Findex.js

Is this because HLS.js isn't supported in iOS? Just [read that here](https://github.com/video-dev/hls.js/issues/2367#issuecomment-530939229) but not believing my eyes since I feel like we have it working in other players?

**Comment by nodgear** [comment]
Tested the docs on iPhone XR Safari @ https://www.vidstack.io/docs/player/providers/hls
HLS Seems to be working fine for me, unless the doc is using a different package version it should be fine.

**Comment by iDVB** [comment]
Sorry I had to **update** the sandbox as I edited it later by mistake.

**Comment by mihar-22** [comment]
Ye that's right, hls.js is _not_ supported on iOS Safari on iPhone because Media Source Extensions is not. You can see [here](https://caniuse.com/?search=MediaSource) that `MediaSource` is supported only on iPad.
