### ISSUE TITLE
Rendering without a `src` prop and adding it after causes player to fail

### ISSUE THREAD

**Issue by iDVB** [vidstack/player#797]
### Current Behavior:
https://codesandbox.io/p/sandbox/vidstack-empty-src-issue-r41eik?selection=%5B%7B%22endColumn%22%3A21%2C%22endLineNumber%22%3A28%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A28%7D%5D&file=%2Fpages%2Findex.js

1. Render `MediaPlayer` without a `src` prop.
2. Add `src` prop to `MediaPlayer` after the fact.
3. Notice it does not load. However native video element does.

### Expected Behavior:

Would expect it to perform as does the native video element which loads fine the moment you add a src prop value.

**Comment by mihar-22** [comment]
Thanks for reporting! Fixed in f3f5bc1d1a3efc3715ba94d219f773f2c5856e05
