### ISSUE TITLE
currentTime is a non-finite value on mount for vod

### ISSUE THREAD

**Issue by ElBouhaliMohamed** [vidstack/player#798]
Sometimes on vods currentTime is non-finite on mount and causes a runtime error. (https://gist.github.com/ElBouhaliMohamed/d634701b1ebd1a60c0a507f5413e0e9d)

When the error happens it seems like vidstack thinks the source is a livestream even tho its a normal video. An hls source in this case. 
![image](https://user-images.githubusercontent.com/28925237/227637292-5d4cb973-8df8-4a7f-9314-a36140b9454b.png)

Tested with nextjs 13.2.4 and vidstack/react 0.4.2

**Comment by mihar-22** [comment]
Fixed in c3be82a0f36cdeefcb5c4402aa7df4b22ce7300d
