### ISSUE TITLE
Can any Demo be added?

### ISSUE THREAD

**Issue by Reqrefusion** [vidstack/player#800]
I was actually using Plyr for my own small project, but I was having some problems and when I looked at the Github page, I saw the Vidstack announcement. I've searched a bit but haven't found any demos. There are no demos on the site or anywhere else. While Plyr can even make changes to the demo with codepen templates, this is a huge shortcoming. Likewise, Vime has a very nice demo. When you first enter the sites of JWPlayer and Video.js, which are intended to be alternatives, the demo welcomes us immediately. For example, I didn't want to mess with it too much because I couldn't see the demo. I think demos showing all the features should be added as soon as possible. This is how the differences and advantages with Plyr and Vime should be shown.

**Comment by billygozutok** [comment]
👋 Turan, thank you for sharing your thoughts about having a player demo, and how important it was for you while you were trying to make sense of our library. We are completely aware of this issue and intend on solving it as soon as we have the player skins ready. For example, we're thinking about building our demo with a sandbox experience so developers can completely understand firsthand what's happening, and how it's been built.

In the meantime, we shared on [Twitter](https://twitter.com/vidstackjs/status/1633618925882834944) what one of our community member has built with our library. Feel free to check it out.
