### ISSUE TITLE
Media player src does not follow redirects

### ISSUE THREAD

**Issue by lqmanh** [vidstack/player#801]
### Current Behavior:

When `src` is set to a URL that returns 30x response, the video player doesn't load.

### Expected Behavior:

The video player should be usable as normal.

### Steps To Reproduce:

1. Generate a shortened URL like https://shorturl.at/avQ34, which resolves to https://media-files.vidstack.io/720p.mp4
2. Set it to `src` prop of `<media-player>`
3. Nothing happens...

### Environment:

- Framework: Web Components
- Node: 18
- OS: Linux
- Browser: Firefox

**Comment by mihar-22** [comment]
Hey @lqmanh! 

Thanks for reporting. If you're dealing with a proxy or redirect you need to provide the `type` otherwise the player can't determine which provider to load.

**HTML**

```html
<media-player>
  <media-outlet>
    <source src="..." type="video/mp4" />
  </media-outlet>
</media-player>
```

**React**

```jsx
<MediaPlayer src={{ src: "...", type: "video/mp4" }}>
```
