### ISSUE TITLE
Seeking with shortcuts does not work correctly

### ISSUE THREAD

**Issue by Curetix** [vidstack/player#803]
### Current Behavior:

Seeking using the arrow keys seems broken in 0.4.3. Seeking forwards always jumps to 10 seconds, and seeking backward jumps to the start of the video.

### Expected Behavior:

The player should seek five seconds forward or backward from the current position, as it did before.

### Steps To Reproduce:

Vite react-ts template with Vidstack player added based on documentation:
https://stackblitz.com/edit/vitejs-vite-zzfss5?file=src%2FApp.tsx&terminal=dev

Focus the player and seek to a random position using the progress bar. Press the right arrow key, and the video will jump to 10 seconds. Press the left arrow key, and the video will jump to 0 seconds.

### Environment:

- Framework: React
- Node: 16
- Device: Desktop
- OS: Windows
- Browser: tested on latest Chrome & Firefox

### Anything Else?

Downgrading to 0.4.2 fixes the issue.

**Comment by mihar-22** [comment]
Fixed in `0.4.4`!

**Comment by Curetix** [comment]
> Fixed in `0.4.4`!

Thank you!
