### ISSUE TITLE
Live Stream docs 

### ISSUE THREAD

**Issue by marksteven** [vidstack/player#821]
### URL:

URL
(https://www.vidstack.io/docs/player/components/display/live-indicator)

### Describe:
Documentation gives a number of examples of indicators showing if there is a live steam or not on the player.
Test site I made to try it out (pasted below)was using all examples with the final one being the Tailwind version in documents.

Outcome was Live video source showed up when I turned it on, sent it out to server and back , but often only after 1 or 2 page refreshes did it appear often with a freeze frame initially replacing the Poster.
Player shows up fine including the "LIVE" text underneath in grey
 but controls never showed up.
So do  I have it wrong or something is missing?

Do understand this is still Beta so this might not yet be implemented yet, or more likely I have it wrong.

Documentation states
This component will contain no content, sizing, or role when the current stream is not live.

However when there was a live stream present I am assuming it should now show a play bar and Live in red as per page example.
![live](https://user-images.githubusercontent.com/3622273/236368036-5116049e-e990-42d4-944b-76bfb2b66276.png)

So am I not importing something or do you need to add more CSS for this to work?

Test Page used is below
````
Imported the following 
import 'vidstack/styles/base.css';
import 'vidstack/define/media-player.js';
plus just in case
import 'vidstack/define/media-live-indicator.js';


<main>
<media-player
  src="https://TESTSTREAM.LKdd8d33N9Z6.m3u8"
  poster="{livelogo}"
  aspect-ratio="16/9"
  stream-type="live"
  data-live
  controls
  >
  <media-outlet />
  <div class="media-controls-container">
    <div class="media-controls">
      <media-live-indicator class="flex h-12 w-12 items-center justify-center text-white">
        <div
          class="live-edge:bg-red-500 live-edge:text-white font-sans-serif rounded-sm bg-gray-400 py-px px-1 text-xs font-bold uppercase tracking-widest text-slate-800"
        >
          live
        </div>
      </media-live-indicator>
 
    </div>
  </div>
  </media-player >  
</main>
````

**Comment by mihar-22** [comment]
I read over this a few times and I don't understand the issue 😅 It'd be nice if you could state it again with a clear description, maybe in the form "I'm expecting X, but I'm receiving Y."

**Comment by marksteven** [comment]
Hi Mihar Sorry I will try again.
The test page (above) I was trying to stream a live stream to the player (m3u8) and make the Live light up as per documentation.
The player worked fine with the live stream. but the "live" indicator did not react.
I was assuming it should go red when a live stream was present.
Given this was beta still I was not sure if I had implemented it correctly and required more, or just that the controls for "live" are not present yet to trigger the change.

**Comment by mihar-22** [comment]
The live indicator will be red when playback is at the live edge (https://www.vidstack.io/docs/player/api/live#live-edge). If you can provide a HLS manifest or stream for me to look at then I can maybe provide better feedback.

Do note, if the stream loads too slowly it will fall off the live edge which will require clicking "LIVE" to seek back to the edge. 

You can also try the following:


- First, try increasing the [tolerance](https://www.vidstack.io/docs/player/api/live#tolerance) to a number that works for you (i.e., what's a tolerance you're okay with). Default is 10, try bumping it up in 5s increments (15, 20, 25, ...). 

- Configure HLS  [`liveSyncDurationCount`](https://github.com/video-dev/hls.js/blob/master/docs/API.md#livesyncdurationcount). Increasing the value may provide enough buffer to stay live. See the [configure](https://www.vidstack.io/docs/player/providers/hls#configuring) section in our docs for how to set it.
