### ISSUE TITLE
Qualities with same height and different bitrate not showing in menu

### ISSUE THREAD

**Issue by codercms** [vidstack/player#838]
When playing an HLS stream that has 2 or more quality levels with the same height but different bitrates, you cannot select a quality with different bitrates.
Cause of this problem is this part of code: https://github.com/vidstack/player/blob/main/packages/vidstack/src/player/ui/menu/quality/menu-items.tsx#LL87C96-L87C96

It's just searching quality level by height, but height may not be unique.
Here is test stream to reproduce issue - https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8

<details>

![image](https://github.com/vidstack/player/assets/4526911/7f84b9ae-b05c-47e2-982f-587362b6019b)

</details>

**UPD**:
Possible solutions are:
* Search quality level by height + bitrate (or anything else), e.g. create ID for each quality level when enumerating quality levels from HLS.js
* Group quality levels by height and use only one with highest bitrate

**Comment by mihar-22** [comment]
Thanks for reporting @codercms! We'll have this fixed for the next release which should be real soon!
