### ISSUE TITLE
[Community Skin] Programmatically changing src changes the skin from desktop to mobile view

### ISSUE THREAD

**Issue by JorrinKievit** [vidstack/player#854]
### Current Behavior:
When changing the src programmatically, the community skin switches to mobile. When you toggle fullscreen, the view is back to desktop.

### Expected Behavior:
The skin should stay in the desktop view after changing sources.

### Steps To Reproduce:
Codesandbox for reproduction: 
https://codesandbox.io/s/vidstack-src-switch-desktop-to-mobile-h4ev8b

### Environment:
- Version 0.6.1
- Framework: React
- Node 18
- Browser: Chrome

**Comment by mihar-22** [comment]
Thanks for the repro! Should be resolved in `0.6.4` :)
