### ISSUE TITLE
Subtitles are positioned wrong on dynamic change and may freeze browser.

### ISSUE THREAD

**Issue by jontyparab** [vidstack/player#856]
### Current Behavior:

Dynamically changing the src and tracks on the player and outlet sometimes renders the captions at wrong position. This often happens with .srt subtitles (and maybe .vtt too). On changing the captions and performing quick jumps using time slider or with arrow keys when that exact time stamp is reached for the cue it freezes the entire page. I have noticed spike in CPU usage when it occurs and only way to lower it is by closing the tab (since page is unresponsive). I have completely integrated  jassub but it doesn't seem to occur with those type of captions. 

### Expected Behavior:

The captions should be visible normally with proper position and not freeze the browser tab on jumps. The expected behaviour does work before changing the captions dynamically but after change it doesn't.

### Steps To Reproduce:

1. Load the video and tracks. (src attribute on media-player and track elements inside media-outlet).
2. Let a cue appear on screen then save that current time.
3. Change the src and tracks for the same or other media while setting the time for video to current time.
4. The cue is shown up, instead of default position. (Problem 1)
5. After quick jumps around that cue's time the browser freezes. (Problem 2)

### Environment:

- Framework: Vue
- Node: v18.13.0
- Device: Desktop
- OS: Ubuntu 22.04.2 LTS
- Browser: Chrome@114

### Anything Else?
I have tried the same steps as above for the same media file and tracks but with captions OFF. The browser **does not** freeze in that case so I am assuming it is because of the captions only. 

#### Note: I noticed that the browser freeze occurs around the wrongly positioned subtitle only. So maybe those problems are related.

Problem 1: Screenshots
Before change
![after dynamic](https://github.com/vidstack/player/assets/64889444/094c3dd3-31d9-4970-9995-eabb6bf816d8)

Only the cue at current time is positioned at top after change. Previous and subsequent cues are okay.
![image](https://github.com/vidstack/player/assets/64889444/204dcadf-322f-4930-9166-9b517034ca78)

**Comment by mihar-22** [comment]
Thanks for the detailed report! Looking into it but it's going to be a tough find. I'll start with seeing how updates are handled in our underlying captions library and go from there.

**Comment by mihar-22** [comment]
I'd love for you test it again in latest `0.6.6` and let me know if the issues have been resolved. I think they should be but not certain about the browser freezing issue because I can't repro.

**Comment by jontyparab** [comment]
Yes both the issues are resolved in `0.6.6`. Thank you!
