### ISSUE TITLE
Shaking layouts

### ISSUE THREAD

**Issue by Mister-Hope** [vidstack/player#859]
https://www.vidstack.io/

When hovering (and moving) on audio progress bar the audio player will bounce up and down quickly due to the display and hidden of time.

I am afraid this may affect user layout when audio player is placing directly below other elements?

**Comment by mihar-22** [comment]
That's only on the home page (not the actual skin) to avoid overlapping with the video player. We're being super lazy because we have a new site design coming for 1.0 so it's just temporary.
