### ISSUE TITLE
Custom keyboard shortcuts

### ISSUE THREAD

**Issue by Curetix** [vidstack/player#868]
### Describe:

Add a new prop for custom keyboard shortcuts, where you could pass the player the key(s) in the [current aria syntax](https://old.vidstack.io/docs/react/player/api/keyboard#configuring-shortcuts) and a JavaScript function to be executed for that key.

It could look like this:

```tsx
<MediaPlayer
  customKeyShortcuts={[
    {
      keys: "k",
      fn: (e) => doSomething(),
    },
    {
      keys: "j",
      fn: (e) => doSomethingElse(),
    },
  ]}
/>;
```

**Comment by mihar-22** [comment]
In the next release shortly you can provide arrays and callbacks like so:

```tsx
<MediaPlayer
  keyShortcuts={{
    // Space-separated list
    togglePaused: 'k Space', 
    // Array
    seekForward: ['j', 'J', 'ArrowRight'],
    // Callback
    fooBar: {
      keys: 'l',
      callback(keyboardEvent) {}
    }
  }}
>
```
