### ISSUE TITLE
[Feature Request]: Extendability of provided components

### ISSUE THREAD

**Issue by jbjhjm** [vidstack/player#872]
I found it to be a good moment to start migrating custom vime-implementation to vidstack :)
All in all a great experience, well-thought and very stable it seems! ❤️

### Problem:

At the moment it is pretty difficult to write custom components based on the provided base components.

This is because 
a) Component classes are  not exported
b) no registration function for custom components is being exported

Example:

Let's assume I want to create a custom TimeSlider cause I need a behavior change in one method.
Currently this means:
a) install maverick.js as direct dependency to allow access to registerLiteCustomElement
b) get access to the component constructor by tricky workarounds only working with window.customElements
c) write ugly closure definition setup to make it work

```ts
defineCustomElements().then(()=>{

	const TimeSlider = window.customElements.get('media-time-slider') as any;
	
	class CustomTimeSlider extends TimeSlider._component {
		static el = defineElement<any>({
			tagName: 'media-time-slider-custom',
			props: {
				...TimeSlider._component.el.props,
			},
			store: TimeSlider._component.el.store,
		});
		
		protected _seek(time: number, percent: number, event: Event) {
			console.log('do custom stuff')
		}
		
	}

	registerLiteCustomElement(CustomTimeSlider as any)
})


```

### Describe:

I think that by exporting components and providing a register function this can be made much more enjoyable :D 
I imagine it to work like this (pseudo code):

```ts
// easy access to component ctor
import { TimeSlider } from 'vidstack/elements/ui/time-slider';

class CustomTimeSlider extends TimeSlider {
	// this could even be further simplified e.g. el = inheritElement(TimeSlider, {...custom})
	static el = defineElement<any>({
		tagName: 'media-time-slider-custom',
		props: TimeSlider.el.props,
		store: TimeSlider.el.store,
	});
		
	protected _seek(time: number, percent: number, event: Event) {
		console.log('do custom stuff')
	}	
}

// allow defineCustomElements to take custom elements :D
defineCustomElements(CustomTimeSlider)

```

### Alternatives:

One could even go one step further and allow for overrides of standard Components.
That way it'd be possible to change a single Component inside Community Skin... without switching to an entirely custom skin.

What do you think? Any plans for such mechanisms?

**Comment by mihar-22** [comment]
Ye exactly this is coming in the next release :) You can import the components, extend, and register as you see fit.

```ts
import { MediaPlayer } from 'vidstack/elements';

class MyPlayer extends MediaPlayer {
}

window.customElements.define("my-player", MyPlayer);
```

I'll need to eventually add docs on how to extend these components and use props/state. Also Maverick will be bundled out of the box and you won't need to install it.
