### ISSUE TITLE
Video player stuck at loading 

### ISSUE THREAD

**Issue by shahzaib414** [vidstack/player#884]
### Current Behavior:

I am using this [document](https://www.vidstack.io/docs/react/player/getting-started/installation) but when I try to load the video, the player stuck in loading
 
### Expected Behavior:

Should be able to play video

### Steps To Reproduce:

Steps Mentioned in this document

### Environment:

- Framework: React

### Anything Else?
![Screenshot 2023-07-21 at 20 00 05](https://github.com/vidstack/player/assets/23331073/9f9c5881-b9f3-48ff-9f6c-af36fa1f1996)

**Comment by shahzaib414** [comment]
@mihar-22  Hi 👋  i am getting error because of CORS issue. even YouTube video is not working

**Comment by coderreco** [comment]
How did you solve this @shahzaib414 ?

**Comment by AsbDaryaee** [comment]
Hi, I have the same Issue Here, I have an address that redirects to my S3 object storage. First, I get 302 redirect from from src address and after that, I receive CORS Error and Vidstack can't load the video. On the other hand, I tested my src link with native HTML video player and Other Players and they could play my video without any issue.

- This is my src Link:
`https://media.callno.ir/file/callno-filecloud/fcl-a6269ef5-4553-4137-a04b-3f05866ac830.mp4`

Can you please help me with this issue? @mihar-22

Thank you BTW :)

**Comment by mcfriend99** [comment]
Anyone ever solved this??
