### ISSUE TITLE
Google Cast - Web Sender

### ISSUE THREAD

**Issue by ewenmic** [vidstack/player#885]
### Related Problem:

Casting content with Google Cast (Apple AirPlay is already supported in the community player)

### Describe:

Add the ability to provide a Google Cast receiver ID to a vidstack player to enable Google Cast logic along with a community player button.

### Alternatives:

I've been able to get this codelab to work with a standard video player, but not with vidstack:
https://developers.google.com/cast/codelabs/cast-videos-chrome

**Comment by ThaUnknown** [comment]
chromecast is..... annoying, while this will work fine for providers like `video` or `hls` [sometimes, not all chromecast devices support HLS to my understanding] it won't work for things like youtube, vimeo or local [blob] files, this could however be remedied by creating a custom chromecast app which essentially runs a website with only the vidstack player, is the scope of this only audio and video?

**Comment by mihar-22** [comment]
This has been implemented and released in `1.10@next` [see release notes](https://github.com/vidstack/player/discussions/1116). The scope is only video and HLS providers at the moment.  Supporting embeds for this is out of scope and not something I'm willing to explore right now. Thanks!

**Comment by natesct** [comment]
Please add AirPlay and googleCastButtons for audio or least make it optional. I added buttons manually and it works 100%.
