### ISSUE TITLE
Controls stay visible after skipping through the video using arrow keys

### ISSUE THREAD

**Issue by ai25** [vidstack/player#902]
### Current Behavior:
When pressing and holding ArrowLeft or ArrowRight to skip through the video, the controls show but do not disappear after the set timeout.

### Expected Behavior:

The controls should show when holding down the arrow keys, but disappear after the user has been idle for the programmed timeout.

### Steps To Reproduce:

1. Go to [](https://vidstack.io)
2. Play the video
3. Press and hold ArrowRight to fast-forward
4. Wait 3 seconds, which is the default user-idle timeout, and notice the controls not disappearing.

### Environment:

- OS: Manjaro
- Browser: Chrome@115

### Anything Else?

Note that this only happens when you hold the button, just pressing it works as expected.

**Comment by mihar-22** [comment]
This was resolved a while ago, forgot to close.
