### ISSUE TITLE
Feature Request: Resume Play

### ISSUE THREAD

**Issue by 0x416C65** [vidstack/player#903]
# Resume Play

I suggest implementing a "Resume Play" feature, allowing users to resume video playback from where they left off.

## Benefits:

1. Enhances user experience.
2. Increases user retention.

Thank you for considering.

**Comment by Nzent** [comment]
Yeah this feature will be awesome for offline player apps ❤️🔥

**Comment by sidis405** [comment]
You can specify `current-time` to the player. So provided you store that somewhere else you can still feed it in and have it pick up wherever you want.

**Comment by mihar-22** [comment]
Our new storage feature covers this, see [1.10@next release notes](https://github.com/vidstack/player/discussions/1116).
