### ISSUE TITLE
Multiples Instance of Vidstack : Only one onCanPlay function is called :/ #904

### ISSUE THREAD

**Issue by ljs19923** [vidstack/player#905]
Hi, in my react nextjs code I have multiples instances of vidstack in my page. Unfortunately one one onCanPlay function is called in this case :/ doesnt matter if all of my instances have the same or a different url

each instance is in a component, in the same parent component

 <MediaPlayer
          playsinline
          aspectRatio={wideView ? 16 / 9 : 1 / 1}
          load={"eager"}
          onCanPlay={onCanPlay}
          onLoad={onLoad}
          src={[
            {
              src: !isEncoding ? videoUrl : "",
              type: "video/mp4",
            },
          ]}
          loop
          autoplay={false}
          ref={player}
          onPlaying={onPlaying}
          muted={true}
        >
          <MediaOutlet></MediaOutlet>
        </MediaPlayer>
        
  function onCanPlay(event: MediaCanPlayEvent) {
    console.log("onCanPlayCalled")
  }
  
  Do you have an idea why?
  Thanks a lot

**Comment by mihar-22** [comment]
It'll be resolved in the next release, it's a bug in how we're handling callbacks internally.

**Comment by ljs19923** [comment]
Thanks a lot for your answer

**Comment by Mellis84** [comment]
As above, do you have an idea roughly when the next release with this fix will be dude? thanks!
