### ISSUE TITLE
Vimeo Provider

### ISSUE THREAD

**Issue by mihar-22** [vidstack/player#945]
We'll be adding the Vimeo provider to ensure we reach feature parity with Vime/Plyr. I've mentioned many times that I'm not a fan of these embeds as they're very limited and suck for both devs and users, but it's more important we don't leave anyone behind who wants to migrate over from Vime/Plyr.

We'll add support for detecting and loading Vimeo videos via the player `src` attribute. Examples:

- `src="vimeo/411652396"`
- `src="https://vimeo.com/411652396"`
- `src="https://player.vimeo.com/video/411652396"`

The embed can be configured via the provider change event:

```ts
function onProviderChange(provider) {
  if (isVimeoProvider(provider)) {
    // configure it here
  }
}
```

❓ _When will it be ready?_

It'll be ready before we officially announce 1.0. It should be within the month.

**Comment by stepanjakl** [comment]
Hi @mihar-22, what's the status on the support of Vimeo embeds? :)

**Comment by mihar-22** [comment]
We're getting there, it'll be part of our 1.0 release. I don't have an exact date but this is one of the features I'll be working on in the coming week/s.
