### ISSUE TITLE
Console Errors Occur When Navigating with Playing Media

### ISSUE THREAD

**Issue by mostafaznv** [vidstack/player#950]
### Current Behavior:

I encounter console errors when the video/audio player is playing, and I try to navigate to another page without pausing the player.

### Expected Behavior:

Navigating without encountering console errors.

### Steps To Reproduce:

1. Play a video or audio.
2. Try to navigate the route when media is playing.
3. Console error.

### Environment:

- Framework: Vue
- Meta Framework: Laravel Mix / Laravel Nova
- Node: 18.18.0
- Device: Mac
- OS: 14.0
- Browser: Chrome@117.0.5938.149

### Workaround

If I pause the player `onBeforeUnmount`, the console error will be resolved.

```js
onBeforeUnmount(() => {
    player.value?.pause()
})
```

### Reproduction Link:

https://stackblitz.com/edit/vitejs-vite-2aklei?file=src%2Fpages%2Fmedia.vue

### Screenshot

![Screenshot 1402-07-18 at 4 56 27 in the afternoon](https://github.com/vidstack/vidstack/assets/7619687/d451793f-cb31-4afb-99d3-becf1e1d427d)

**Comment by mihar-22** [comment]
Just checking what player version is this on?

**Comment by mostafaznv** [comment]
^1.1.11

**Comment by mostafaznv** [comment]
Reproduction Link:

https://stackblitz.com/edit/vitejs-vite-2aklei?file=src%2Fpages%2Fmedia.vue

**Comment by mihar-22** [comment]
Thanks for taking the time report. This issue has been resolved in `1.2.0`.

**Comment by mostafaznv** [comment]
Thank you for addressing the previous console error; it has been resolved. However, I have come across another issue:

```
Uncaught TypeError: Cannot read properties of null (reading 'setDisplay')
```

I'm having difficulty pinpointing the root cause of this error. It occurs sporadically and seems to be related to the destruction of the player, regardless of whether it is playing content or not.

**Comment by mostafaznv** [comment]
I attempted to create a reproduction link, and in doing so, encountered an error. However, the error message I received in this state is different from the one I encountered on my localhost:


https://stackblitz.com/edit/vitejs-vite-2aklei?file=src%2Fpages%2Findex.vue
```
TypeError: Cannot read properties of undefined (reading '$$')
```

localhost (another source code, but it's a multi-tab too):
```
Uncaught TypeError: Cannot read properties of null (reading 'setDisplay')
```

**Comment by mihar-22** [comment]
Found the issue. I'll release fix today soon.
