### ISSUE TITLE
Styling issues on Chromium 87

### ISSUE THREAD

**Issue by AgentSmith0** [vidstack/player#956]
### Current Behavior:

Player doesn't draw correctly, but buttons work. (no JavaScript issues, just CSS)

### Expected Behavior:

Gets drawn correctly, since browser support is there: https://caniuse.com/custom-elementsv1

### Steps To Reproduce:

1. Open in Chromium 87
2. See that the player doesn't get drawn correctly

### Environment:

- Framework: Any
- Device: Any
- OS: Any
- Browser: Chrome@87

### Anything Else?

How the player looks on Chromium 87:
![example](https://github.com/vidstack/vidstack/assets/67276662/1ac52be0-2ea8-458f-87a5-03ddc5791db3)

**Comment by mihar-22** [comment]
Hey AgentSmith! Chromium 87 is [outdated and no longer supported](https://caniuse.com/mdn-css_selectors_where). However, we might still remove the `:where` selectors as it's causing [issues with CSS resets](https://github.com/vidstack/player/issues/957). Follow that issue for any updates.

**Comment by mihar-22** [comment]
I'll come back to considering a CSS file without `:where`, but can't guarantee because Chromium 87 is so old. You can show native controls by adding the `controls` to the player:

```tsx
<MediaPlayer controls>
```
