### ISSUE TITLE
Tailwind Preflight Reset is Crushing Player Button Styles

### ISSUE THREAD

**Issue by miketdonahue** [vidstack/player#957]
### Current Behavior:

Tailwind's aggressive CSS reset called "Preflight" is clobbering some of the styling, specifically `<button>` styling, in the Player "Settings" menu. (See screenshot below). Disabling Tailwind's Preflight fixes the styling.

### Expected Behavior:

The Player CSS should account for aggressive CSS reset's being used (they are common), and inject **all** styles necessary to ensure the appropriate output or increase the specificity to negate the reset.

### Steps To Reproduce:

Load up the Player in an app using the default settings from Tailwind CSS.

### Environment:

- Framework: React
- Meta Framework: Next.js
- Node: 18.0.0
- Browser: Chrome v117
- Player: Default Layout

### Anything Else?

<img width="430" alt="image" src="https://github.com/vidstack/vidstack/assets/8016033/b48fe452-7af8-461b-bc32-1678f82269a6">

**Comment by mihar-22** [comment]
Should be all fixed in `1.2.0`. Thanks for reporting! I didn't remove the `:where` selectors (relevant to other issue) as they ensure user styles always win, and don't clog up devtools styles inspector. Considering Chromium 87 is outdated and not supported, it should be okay.
