### ISSUE TITLE
Scrolling does not work [iOS Safari]

### ISSUE THREAD

**Issue by enchorb** [vidstack/player#962]
### Current Behavior:

Using `vidstack@next` latest version. Cannot scroll or do any gestures (pinch to zoom) on video on iOS.

**Comment by mihar-22** [comment]
I tested this on iOS 16.6.1 and everything works as expected. What version are you testing on?

**Comment by enchorb** [comment]
iOS 17.0.3

**Comment by enchorb** [comment]
Any updates here? @mihar-22 can you also share your working example.

**Comment by mihar-22** [comment]
This should be resolved in the next release shortly today. If it's not happy to re-open.

**Comment by enchorb** [comment]
Still an issue on `1.4.7`, can this be re-opened
