### ISSUE TITLE
Changing a slider's (Volume/Time) value with your keyboard should not alter other sliders

### ISSUE THREAD

**Issue by giliamverheide** [vidstack/player#965]
### Current Behavior:

- Changing the value of a `VolumeSlider` with the left/right arrows on your keyboard also changes the `TimeSlider` value (and current media time).
- Changing the value of a `TimeSlider` with the up/down arrows on your keyboard also changes the `VolumeSlider` value.

### Expected Behavior:

Whether you use up/down arrow keys or left/right arrow keys to change a slider's value, it should not alter the value of any other sliders.

### Steps To Reproduce:

Use your keyboard to focus the VolumeSlider, then press the left/right arrow keys on your keyboard to change the volume. You'll notice the TimeSlider and media's current time also change.

If you change the TimeSlider value with your keyboard by pressing the up/down arrow keys, it will also change the VolumeSlider value.

https://stackblitz.com/edit/vidstack-examples-rcsa7c?file=src%2Fcomponents%2Fsliders.tsx

### Environment:

- Framework: React 18
- @vidstack/react: 1.3.0
- Browser: Chrome

**Comment by mihar-22** [comment]
Thanks for reporting! Strangely, it seems these issues only exist when orientation is vertical. I'll look into it.

**Comment by giliamverheide** [comment]
> Thanks for reporting! Strangely, it seems these issues only exist when orientation is vertical. I'll look into it.

That's what I thought first too, but in the stackblitz project, if I change the orientation of the volume slider to horizontal and reload the same problem occurs.

Another thing I noticed, which is probably due to how the different sliders handle `step` differently, is that the value changes differently depending on if you use up/left or left/right arrow keys and the displayed value can go above 100%. At least for the vertical slider in stackblitz.

This video was recorded on https://www.vidstack.io/
Also note that pressing up/down will scroll the page (shift + up will not).

https://github.com/vidstack/player/assets/15910702/fd13e6b9-07ad-4b71-9d1f-953187966143

**Comment by mihar-22** [comment]
Really good catches. Thanks for finding them.

**Comment by mihar-22** [comment]
> If you focus the "vertical" slider and press up/down keys for the first time, the value will shift by 15% and not 5%.

I can't repro this 🤷  This might be a iframe specific bug.

> [The docs](https://www.vidstack.io/docs/player/components/sliders/volume-slider?styling=default-theme#volumeslider.value) state VolumeSlider.Value type prop is 'current' by default, but if you don't pass this prop, it seems 'pointer' is used.

Thanks, fixed! Default is now `pointer` for all. The format default is more appropriate too now. For time slider the format is time by default, and volume percent.

>  Changing a slider's value with arrow keys can affect another slider's value, both for a horizontal and vertical (volume) slider.

I can't repro. This might be an iframe specific bug.

For iframe specific issues we'll stick to #951.

**Comment by giliamverheide** [comment]
> > If you focus the "vertical" slider and press up/down keys for the first time, the value will shift by 15% and not 5%.
> 
> I can't repro this 🤷 This might be an iframe specific bug.
> 
> > [The docs](https://www.vidstack.io/docs/player/components/sliders/volume-slider?styling=default-theme#volumeslider.value) state VolumeSlider.Value type prop is 'current' by default, but if you don't pass this prop, it seems 'pointer' is used.
> 
> Thanks, fixed! Default is now `pointer` for all. The format default is more appropriate too now. For time slider the format is time by default, and volume percent.
> 
> > Changing a slider's value with arrow keys can affect another slider's value, both for a horizontal and vertical (volume) slider.
> 
> I can't repro. This might be an iframe specific bug.
> 
> For iframe specific issues we'll stick to #951.

I can no longer reproduce the value jumping by 15%, but changing a slider's value still affects another slider's value in the stackblitz project above. (Stackblitz still has `"@vidstack/react": "^1.4.0"` installed)

https://stackblitz.com/edit/vidstack-examples-rcsa7c

I focus on the volume slider, press the right arrow key, the time slider moves right, same for shift + →.
Then I move focus to the time slider, press the down arrow key, volume goes down, same for shift + down.

Mac OS
Chrome Version 117.0.5938.149

https://github.com/vidstack/player/assets/15910702/6c4d50b7-44d2-47da-a753-2f0c9f1b20e5
