### ISSUE TITLE
Console error 'can't find variable: isHLSSupported' on 1.4.0

### ISSUE THREAD

**Issue by josh-attwood** [vidstack/player#970]
I am just trying out 1.4.0 and have noticed the error below when trying to load an HLS file, this is totally breaking HLS support for me at the minute.

```
[Error] ReferenceError: Can't find variable: isHLSSupported

	(anonymous function) (main.js:23540)
	./node_modules/vidstack/dist/dev/chunks/vidstack-81359291.js (main.js:23538)
	__webpack_require__ (main.js:32208)
	./node_modules/vidstack/dist/dev/chunks/vidstack-3ca98689.js (main.js:21184:99)
	__webpack_require__ (main.js:32208)
	./node_modules/vidstack/dist/dev/define/vidstack-player.js (main.js:32172:106)
	__webpack_require__ (main.js:32208)
	(anonymous function) (main.js:32475:93)
	(anonymous function) (main.js:32679)
	Global Code (main.js:32681)

```

**Comment by mihar-22** [comment]
Tested across different environments and couldn't repro. There's no misuse of `isHLSSupported`, I checked all calls. You could try simply clearing any caches and `rm -rf node_modules && npm i`.

**Comment by mihar-22** [comment]
I see... it might be related to side effects and how Webpack is treeshaking. I removed the potential issue line. Confident this should be resolved in the next release.
