### ISSUE TITLE
ControlsDelay prop not using value

### ISSUE THREAD

**Issue by wplit** [vidstack/player#972]
[using web components]

If I understand correctly, this should change the amount of time until the 'data-controls' attribute is removed, so the controls can hide. It seems to be always 2 seconds regardless of what value i give.

https://codepen.io/wplit/pen/mdaNyjz

**Comment by mihar-22** [comment]
Ah small mistake in your example. The attribute is `controls-delay`, you can't set properties like that.

```html
<media-player controls-delay="10000">
```

**Comment by wplit** [comment]
Hi,

When I change it to controls-delay="10000" it also doesn't use the value. (updated the codepen to show it)

Or do you mean that generally we shouldn't be setting the props like that, and always to use JS to get the instance and change it there?

**Comment by mihar-22** [comment]
Ye found the bug, will roll out soon tonight.
