### ISSUE TITLE
Touch related issues on mobile devices

### ISSUE THREAD

**Issue by MobinurRahaman** [vidstack/player#976]
### Issues

- When a user swipes on the video player using a touch device, the seekbar gets focused, and the video preview remains opened.
- The video player controls do not automatically hide after a touch interaction.

### Environment:
- OS: Android 10
- Browser: Chrome@117.0.5938.156

**Comment by mihar-22** [comment]
Thanks for reporting, found it! Fixed and will be released shortly in `1.4.5`.
