### ISSUE TITLE
autoplay causing browser to freeze

### ISSUE THREAD

**Issue by hornta** [vidstack/player#979]
### Current Behavior:
I'm getting this error only when I've enabled autoplay in certain cases.
```
ERROR MediaPlayer play request failed
vidstack-506910d5.js:3792 Element: 
vidstack-506910d5.js:3792 Trigger: DOMEvent {isTrusted: false, detail: undefined, trigger: DOMEvent, Symbol(DOM_EVENT): true, …}
vidstack-506910d5.js:3792 Error: 
vidstack-506910d5.js:3792 Time since last log: 0ms
vidstack-506910d5.js:3795 Stack Trace
```

This is because the actual error is `play() failed because the user didn't interact with the document first.`.

### Expected Behavior:

It shouldn't freeze the browser on this type of error.

### Environment:

Vite, React 18.2, Chrome, Win11

**Comment by mihar-22** [comment]
Thanks for the report! Fixed, releasing shortly today.
