### ISSUE TITLE
Sometimes vidstack player doesn't show duration of mp4 or mp3 files

### ISSUE THREAD

**Issue by AgentSmith0** [vidstack/player#981]
### Current Behavior:

In Firefox I often see that vidstack somehow doesn't get the duration of mp4 or mp3 files, it only shows 0:00, but the video/audio is playing fine. Sometimes it loads the duration correctly, sometimes not. In Chromium or with HLS streams I haven't seen problem. I have also seen this problem somtimes on the official examples at stackblitz.

### Expected Behavior:

Show duration correct and reliably for mp4 and mp3 files.

### Steps To Reproduce:

1. Create a vidstack player with and mp4 or mp3 file
2. Load the page a view times in Firefox (also try private mode and with cleared cache, etc.)
3. See that the duration sometimes doesn't load correctly

### Environment:

Example:
- Framework: CDN
- OS: Linux
- Browser: Firefox v118

**Comment by mihar-22** [comment]
Thanks for reporting! Found the issue in our initial duration update, rolling fix out today in `1.4.8`!
