### ISSUE TITLE
Scrolling does not work [iOS Safari]

### ISSUE THREAD

**Issue by enchorb** [vidstack/player#987]
Using vidstack@next latest version. Cannot scroll or do any gestures (pinch to zoom) on video on iOS.

Re-Opened: https://github.com/vidstack/player/issues/962

**Comment by mihar-22** [comment]
Finally found the issue, resolved and will be released in `1.5.3` shortly today.

**Comment by enchorb** [comment]
Fixed! Thanks!

**Comment by ljs19923** [comment]
Hello, are you sure this bug is fixed? I have it :/ When my video is playing, Im not able to touch the screen to scroll to windowScroll of my page, on iOS ( Works on ipad, not on iphone)

`  <MediaPlayer
                      playsinline
                      webkit-playsinline
                      load={"eager"}
                      onCanPlay={onCanPlay}
                      src={[
                        {
                          src: block.videoUrlFile,
                          type: block.videoUrlFile.includes("mux.com")
                            ? "application/x-mpegurl"
                            : "video/mp4",
                        },
                      ]}
                      autoplay
                      loop
                      ref={player}
                      onPlaying={onPlaying}
                      muted={false}
                      controls
                    >
                      <MediaOutlet></MediaOutlet>
                    </MediaPlayer>`
