### ISSUE TITLE
Crossorigin error because of empty.vtt in src of track

### ISSUE THREAD

**Issue by ennair** [vidstack/player#993]
### Describe:

When adding a Track not of type 'vtt' when rendered the src will become 'https://cdn.jsdelivr.net/npm/vidstack@next/empty.vtt' instead of the src I provided. Is there a reason why this is done? 

This causes me some cross origin issues, which is not needed. If my provided source is returned the cross origin issue is solved. 

How I made my track with an srt file:
`<Track
              src='https://www.example.com/subtitle.srt'
              kind='captions'
              type='srt'
              label='English'
              language='en'
            />`

Screenshot of generated track at the moment:
`<track id="" src="https://cdn.jsdelivr.net/npm/vidstack@next/empty.vtt" label="English" kind="captions" srclang="en">`

This is the line of code which adds the empty.vtt, https://github.com/vidstack/player/blob/c8fec6c5f909df1d604953d537a87d9c5d8e6a54/packages/vidstack/src/core/tracks/text/render/native-text-renderer.ts#L71 

Why is an empty.vtt file added as src? Is it possible to show our own src instead? That would solve my cross origin error.

**Comment by mihar-22** [comment]
Hey there!

SRT is not supported natively so we need to map it to VTT. Unfortuantely loading and managing custom tracks in iOS Safari is a pain in the ass. It seems that one of the only consistent ways to show custom VTT cues is to load an empty VTT text track (`empty.vtt` file).

I haven't documented it but in this case you'll need to make sure to add `crossorigin` to the player.

```html
<media-player crossorigin>
```

```jsx
<MediaPlayer crossorigin>
```

**Comment by ennair** [comment]
Thanks for the explanation! I now get why it is in. 

And is it possible to provide our own empty.vtt file? In which case it uses our own empty.vtt file instead of the default.
