### ISSUE TITLE
Flickering dark overlay when captions appear/disappear

### ISSUE THREAD

**Issue by sedubois** [vidstack/player#998]
### Current Behavior:

Using default layout, a dark overlay is added on top of the whole video image when any caption is being displayed, which disappears as soon as no caption is visible (i.e. when the speaker is pausing his speech). It results in the video flickering between a lighter and darker version which is quite disturbing to the eye.

### Expected Behavior:

No dark overlay should be shown on the entire video, even if there are captions displayed.

### Steps To Reproduce:

1. install Vidstack following steps 1-7 of [install procedure](https://www.vidstack.io/docs/player/getting-started/installation/cdn?provider=video&styling=default-layout), CDN, video, Default Layout
2. replace the media-player src with the URL of an HLS video containing subtitles
3. load the player and enable subtitles
4. start playback and observe the flickering as captions appear and disappear

### Environment:

- Framework: n/a
- Meta Framework: n/a
- Node: n/a
- Device: macbook M2
- OS: Sonoma 14
- Browser: Firefox@120.0b7

### Anything Else?

You can see that the video darkens at the exact time when the subtitle appears:

https://github.com/vidstack/player/assets/4217871/c05fda1c-c9ec-4ebb-8e3f-c5129c31fb4d

**Comment by mihar-22** [comment]
I don't see this behaviour with the out of box settings. The darkened overlay is only shown when the controls are visible so not sure how that's possible?

**Comment by sedubois** [comment]
Here is a repro: https://github.com/sedubois/vidstack-issue-998

Generated as follows:
- rails new --css=tailwind vidstack-issue-998 && cd vidstack-issue-998
- rails db:create && rails g scaffold video && rails db:migrate
- [install](https://www.vidstack.io/docs/player/getting-started/installation/cdn?styling=default-layout&provider=video) Vidstack using steps 1-7 (CDN, video, default layout)
- replace demo video with [this HLS one](https://player.vimeo.com/external/883181011.m3u8?s=2b8356466aafd574171ab9e669ea52575887b041&logging=false) which has VTT subtitles
- rails server
- visit http://localhost:3000
- click CC to enable subtitles, and start video
- observe that when captions ("Line 2", "Line 3", "Line 4", "Line 5") appear, the video gets darkened

Screen recording:

https://github.com/vidstack/player/assets/4217871/2b904a42-6e45-469a-a3a7-ff60f2db429b

**Comment by sedubois** [comment]
For what it's worth, I don't observe this issue any more after having moved away from Default Theme to a custom Tailwind template.
