### ISSUE TITLE
Player layout jumps when loading poster

### ISSUE THREAD

**Issue by sedubois** [vidstack/player#999]
### Current Behavior:

Using default layout, when rendering a video with poster, the size of the poster and player jump (first smaller then get bigger). The poster is initially shown within the player with dark margins on the left/right sides, then those disappear, allowing the poster to expand further down and thus making the whole player taller. It results in a "jump" which is quite disturbing to the eye when the player loads.

### Expected Behavior:

The player should immediately have the correct size/layout, no margins should show up on the left/right sides of the poster, player height should stay constant.

### Steps To Reproduce:

1. install Vidstack following steps 1-7 of [install procedure](https://www.vidstack.io/docs/player/getting-started/installation/cdn?provider=video&styling=default-layout), CDN, video, Default Layout
2. use following code then load the page:

```html
      <media-player
        title="video title"
        src="https://stream.mux.com/VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU/low.mp4"
      >
        <media-provider></media-provider>
        <media-video-layout></media-video-layout>
        <media-poster
          class="vds-poster"
          src="http://localhost:3000/poster.png"
        ></media-poster>
      </media-player>
```

### Environment:

- Framework: n/a
- Meta Framework: n/a
- Node: n/a
- Device: macbook M2
- OS: Sonoma 14
- Browser: Firefox@120.0b7

### Anything Else?

https://github.com/vidstack/player/assets/4217871/408145c7-b14f-450a-86e7-b64efbddadc2

**Comment by mihar-22** [comment]
This is expected behaviour. Please see [avoiding layout shifts](https://www.vidstack.io/docs/wc/player/core-concepts/loading?styling=default-theme#avoiding-layout-shifts) in the docs.

**Comment by sedubois** [comment]
Thank you, I could fix it by ensuring the poster image has a 16/9 aspect ratio + adding Tailwind class `aspect-video` (i.e. 16/9 aspect ratio) on the `media-player`. 

Perhaps the Default Layout CSS could be updated to automatically set `aspect-ratio: 16 / 9` on `media-player`?

**Comment by wplit** [comment]
> Thank you, I could fix it by ensuring the poster image has a 16/9 aspect ratio + adding Tailwind class `aspect-video` (i.e. 16/9 aspect ratio) on the `media-player`.
> 
> Perhaps the Default Layout CSS could be updated to automatically set `aspect-ratio: 16 / 9` on `media-player`?

This is best for people to add themselves, no? The aspect ratio is one line of CSS, and everybody using the player may need different ratio.

**Comment by sedubois** [comment]
> This is best for people to add themselves, no? The aspect ratio is one line of CSS, and everybody using the player may need different ratio.

The Default Layout makes various decisions for people so this would just be an additional one. And it could be overridden by providing a CSS variable for it.

By setting the aspect ratio from the start, it would ensure a cleaner out-of-the-box experience, providing a better first impression with the player.

**Comment by mihar-22** [comment]
Good point @sedubois, I'll look into setting better defaults as long as it doesn't cause any unexpected issues.
